import dict_school

names = {
  "Ruby Heart": "健体红心",
# 神龛
  "Unnamed Shrine": "Unnamed Shrine",
  "Calling Shrine": "Calling Shrine",
  "Life Shrine": "Life Shrine",
  "Otherworldly Shrine": "Otherworldly Shrine",
  "Red Flame Shrine": "Red Flame Shrine",
  "Storm Cloud Shrine": "Storm Cloud Shrine",
  "Oaken Shrine": "Oaken Shrine",
  "Afterlife Shrine": "Afterlife Shrine",
  "Stillness Shrine": "Stillness Shrine",
  "Frozen Skull Shrine": "Frozen Skull Shrine",
  "Nightmare Shrine": "Nightmare Shrine",
  "Thunder Shrine": "Thunder Shrine",
  "Burning Shrine": "Burning Shrine",
  "Cruel Shrine": "Cruel Shrine",
  "Torment Shrine": "Torment Shrine",
  "Mystic Shrine": "Mystic Shrine",
  "Icy Shrine": "Icy Shrine",
  "White Candle Shrine": "White Candle Shrine",
  "Frostfire Shrine": "Frostfire Shrine",
  "Fae Shrine": "Fae Shrine",
  "Enveloping Shrine": "Enveloping Shrine",
  "Memory Shrine": "Memory Shrine",
  "Life Shrine": "Life Shrine",
  "Tundra Shrine": "Tundra Shrine",
  "Swamp Shrine": "Swamp Shrine",
  "Black Sky Shrine": "Black Sky Shrine",
  "Frozen Shrine": "Frozen Shrine",
  "Angelic Shrine": "Angelic Shrine",
  "Demonbane Shrine": "Demonbane Shrine",
  "Crackling Shrine": "Crackling Shrine",
  "Sandstone Shrine": "Sandstone Shrine",
  "Charred Bone Shrine": "Charred Bone Shrine",
  "Red Star Shrine": "Red Star Shrine",
  "Blue Sky Shrine": "Blue Sky Shrine",
  "Energy Shrine": "Energy Shrine",
  "Soulpower Shrine": "Soulpower Shrine",
  "Soulpower Shrine": "Soulpower Shrine",
  "Grove Shrine": "Grove Shrine",
  "Bright Shrine": "Bright Shrine",
  "Protection Shrine": "Protection Shrine",
  "Grey Bone Shrine": "Grey Bone Shrine",
  "Stoning Shrine": "Stoning Shrine",
  "Berserk Shrine": "Berserk Shrine",
  "Dragon Heart Shrine": "Dragon Heart Shrine",
  "Farsight Shrine": "Farsight Shrine",
  "Entropy Shrine": "Entropy Shrine",
  "Entropy Shrine": "Entropy Shrine",
  "Enervation Shrine": "Enervation Shrine",
  "Enervation Shrine": "Enervation Shrine",
  "Chaos Imp Shrine": "Chaos Imp Shrine",
  "Wyrmbrood Shrine": "Wyrmbrood Shrine",
  "Boon Shrine": "Boon Shrine",
  "Sniper Shrine": "Sniper Shrine",
  "Toxic Agony Shrine": "Toxic Agony Shrine",
  "Bone Splinter Shrine": "Bone Splinter Shrine",
  "Haunting Shrine": "Haunting Shrine",
  "Sword Shrine": "Sword Shrine",
  "Dagger Shrine": "Dagger Shrine",
  "Claw Shrine": "Claw Shrine",
  "Vigor Shrine": "Vigor Shrine",
  "Shell Shrine": "Shell Shrine",
  "Propagation Shrine": "Propagation Shrine",
  "Butterfly Wing Shrine": "Butterfly Wing Shrine",
  "Gold Skull Shrine": "Gold Skull Shrine",
  "Furnace Shrine": "Furnace Shrine",
  "Heavenstrike Shrine": "Heavenstrike Shrine",
  "Stormcharge Shrine": "Stormcharge Shrine",
  "Disintegration Shrine": "Disintegration Shrine",
  "Alchemist Shrine": "Alchemist Shrine",
  "Warped Shrine": "Warped Shrine",
  "Troubler Shrine": "Troubler Shrine",
  "Sphere Shrine": "Sphere Shrine",
  "Fire Claw Shrine": "Fire Claw Shrine",
  "Ice Claw Shrine": "Ice Claw Shrine",
  "Faewitch Shrine": "Faewitch Shrine",
  "Bomber Shrine": "Bomber Shrine",
  "Sorcery Shield Shrine": "Sorcery Shield Shrine",
  "Frost Faery Shrine": "Frost Faery Shrine",
  "Essence Shrine": "Essence Shrine",
  "Chaos Relay Shrine": "Chaos Relay Shrine",
  "Elemental Harvest Shrine": "Elemental Harvest Shrine",
  "Icy Spriggan Shrine": "Icy Spriggan Shrine",
  "Sunlight Shrine": "Sunlight Shrine",
  "Searing Shrine": "Searing Shrine",
  "Chaos Quill Shrine": "Chaos Quill Shrine",
  "Firefly Shrine": "Firefly Shrine",
  "Cauterizing Shrine": "Cauterizing Shrine",
  "Deathchill Chimera Shrine": "Deathchill Chimera Shrine",
  "Bloodrage Shrine": "Bloodrage Shrine",
  "Razor Shrine": "Razor Shrine",
}

names.update([(f"{k} Circle", f"{v}法阵") for (k,v) in dict_school.names.items() if k[0].isupper()])
