names = {
  "Unnamed Shrine": "Unnamed Shrine",
  "Calling": "Calling",
  "Life": "Life",
  "Otherworldly": "Otherworldly",
  "Red Flame": "Red Flame",
  "Storm Cloud": "Storm Cloud",
  "Oaken": "Oaken",
  "Afterlife": "Afterlife",
  "Stillness": "Stillness",
  "Frozen Skull": "Frozen Skull",
  "Nightmare": "Nightmare",
  "Thunder": "Thunder",
  "Burning": "Burning",
  "Cruel": "Cruel",
  "Torment": "Torment",
  "Mystic": "Mystic",
  "Icy": "Icy",
  "White Candle": "White Candle",
  "Frostfire": "Frostfire",
  "Fae": "Fae",
  "Enveloping": "Enveloping",
  "Memory": "Memory",
  "Life": "Life",
  "Tundra": "Tundra",
  "Swamp": "Swamp",
  "Black Sky": "Black Sky",
  "Frozen": "Frozen",
  "Angelic": "Angelic",
  "Demonbane": "Demonbane",
  "Crackling": "Crackling",
  "Sandstone": "Sandstone",
  "Charred Bone": "Charred Bone",
  "Red Star": "Red Star",
  "Blue Sky": "Blue Sky",
  "Energy": "Energy",
  "Soulpower": "Soulpower",
  "Soulpower": "Soulpower",
  "Grove": "Grove",
  "Bright": "Bright",
  "Protection": "Protection",
  "Grey Bone": "Grey Bone",
  "Stoning": "Stoning",
  "Berserk": "Berserk",
  "Dragon Heart": "Dragon Heart",
  "Farsight": "Farsight",
  "Entropy": "Entropy",
  "Entropy": "Entropy",
  "Enervation": "Enervation",
  "Enervation": "Enervation",
  "Chaos Imp": "Chaos Imp",
  "Wyrmbrood": "Wyrmbrood",
  "Boon": "Boon",
  "Sniper": "Sniper",
  "Toxic Agony": "Toxic Agony",
  "Bone Splinter": "Bone Splinter",
  "Haunting": "Haunting",
  "Sword": "Sword",
  "Dagger": "Dagger",
  "Claw": "Claw",
  "Vigor": "Vigor",
  "Shell": "Shell",
  "Propagation": "Propagation",
  "Butterfly Wing": "Butterfly Wing",
  "Gold Skull": "Gold Skull",
  "Furnace": "Furnace",
  "Heavenstrike": "Heavenstrike",
  "Stormcharge": "Stormcharge",
  "Disintegration": "Disintegration",
  "Alchemist": "Alchemist",
  "Warped": "Warped",
  "Troubler": "Troubler",
  "Sphere": "Sphere",
  "Fire Claw": "Fire Claw",
  "Ice Claw": "Ice Claw",
  "Faewitch": "Faewitch",
  "Bomber": "Bomber",
  "Sorcery Shield": "Sorcery Shield",
  "Frost Faery": "Frost Faery",
  "Essence": "Essence",
  "Chaos Relay": "Chaos Relay",
  "Elemental Harvest": "Elemental Harvest",
  "Icy Spriggan": "Icy Spriggan",
  "Sunlight": "Sunlight",
  "Searing": "Searing",
  "Chaos Quill": "Chaos Quill",
  "Firefly": "Firefly",
  "Cauterizing": "Cauterizing",
  "Deathchill Chimera": "Deathchill Chimera",
  "Bloodrage": "Bloodrage",
  "Razor": "Razor",
}
