names = {
  "Unblinking Eye": "Unblinking Eye",
  "Rock Collection": "Rock Collection",
  "Dragon Lord": "Dragon Lord",
  "Translocation Master": "Translocation Master",
  "Arch Enchanter": "Arch Enchanter",
  "Arch Sorcerer": "Arch Sorcerer",
  "Arch Conjurer": "Arch Conjurer",
  "Fire Lord": "Fire Lord",
  "Ice Lord": "Ice Lord",
  "Thunder Lord": "Thunder Lord",
  "Nature Lord": "Nature Lord",
  "Dark Lord": "Dark Lord",
  "Void Lord": "Void Lord",
  "Light Lord": "Light Lord",
  "Orb Lord": "Orb Lord",
  "Metal Lord": "Metal Lord",
  "Pyrophilia": "Pyrophilia",
  "Pyrostatic Charge": "Pyrostatic Charge",
  "Pyrostatics": "Pyrostatics",
  "Soul Harvest": "Soul Harvest",
  "Arcane Combustion": "Arcane Combustion",
  "Searing Heat": "Searing Heat",
  "Devourer of Nations": "Devourer of Nations",
  "Devourer of Champions": "Devourer of Champions",
  "Minion Regeneration": "Minion Regeneration",
  "Glittering Dance": "Glittering Dance",
  "Arcane Credit": "Arcane Credit",
  "Arcane Accounting": "Arcane Accounting",
  "Natural Healing": "Natural Healing",
  "Crackling Frenzy": "Crackling Frenzy",
  "Lightning Frenzy": "Lightning Frenzy",
  "Armor Melted": "Armor Melted",
  "Melting Armor": "Melting Armor",
  "Natural Vigour": "Natural Vigour",
  "Hunger": "Hunger",
  "Hungry Dead": "Hungry Dead",
  "Lightning Warp": "Lightning Warp",
  "Starfire": "Starfire",
  "Shock Value": "Shock Value",
  "Horror": "Horror",
  "White Flame": "White Flame",
  "Chaos Buddies": "Chaos Buddies",
  "Arcane Shield": "Arcane Shield",
  "Shielded Minions": "Shielded Minions",
  "Ghostfire": "Ghostfire",
  "Last Word": "Last Word",
  "Prince of Ruin": "Prince of Ruin",
  "Righteous March": "Righteous March",
  "Fiery Judgement": "Fiery Judgement",
  "Holy Thunder": "Holy Thunder",
  "Chastisement": "Chastisement",
  "Chaos Casting": "Chaos Casting",
  "Unholy Alliance": "Unholy Alliance",
  "Thorn Garden": "Thorn Garden",
  "Hypocrisy": "Hypocrisy",
  "Fae Stone Buff": "Fae Stone Buff",
  "Faestone": "Faestone",
  "Houndlord": "Houndlord",
  "Bone Guard": "Bone Guard",
  "Cracklevoid": "Cracklevoid",
  "Spider Spawning": "Spider Spawning",
  "Paralyzing Venom": "Paralyzing Venom",
  "Venom Spit": "Venom Spit",
  "Venom Spit": "Venom Spit",
  "Icy Vengeance": "Icy Vengeance",
  "Ice Tap": "Ice Tap",
  "Frostbite": "Frostbite",
  "Steam Anima": "Steam Anima",
  "Storm Caller": "Storm Caller",
  "Holy Water": "Holy Water",
  "Hibernation": "Hibernation",
  "Crystal Power": "Crystal Power",
  "Radiant Chill": "Radiant Chill",
  "Shatter Shards": "Shatter Shards",
  "Fragile": "Fragile",
  "Frozen Fragility": "Frozen Fragility",
  "Scalespinner": "Scalespinner",
  "Collected Agony": "Collected Agony",
  "Moonspeaker": "Moonspeaker",
  "Void Spikes": "Void Spikes",
  "Necrostatics": "Necrostatics",
  "Purestrike": "Purestrike",
  "Silkshifter": "Silkshifter",
  "Inferno Engines": "Inferno Engines",
  "Megavenom": "Megavenom",
  "Acid Fumes": "Acid Fumes",
  "Starcharged": "Starcharged",
  "Voidflame Lantern": "Voidflame Lantern",
}
