names = {
  "Fire": "火焰",
  "Lightning": "闪电",
  "Ice": "冰霜",
  "Nature": "自然",
  "Arcane": "奥法",
  "Dark": "黑暗",
  "Holy": "神圣",
  "Sorcery": "魔能",
  "Conjuration": "召唤",
  "Enchantment": "附魔",
  "Word": "真言",
  "Orb": "法球",
  "Dragon": "巨龙",
  "Translocation": "移位",
  "Metallic": "金属",
  "Eye": "视线",
  "Chaos": "混沌",
}
names.update([(k.lower(), v) for (k, v) in names.items()])
color = dict([(k, f"[{v}:{k.lower()}]") for (k, v) in names.items()])

filter = {
  "Fire": "火焰 (F)",
  "Lightning": "闪电 (L)",
  "Ice": "冰霜 (I)",
  "Nature": "自然 (N)",
  "Arcane": "奥法 (A)",
  "Dark": "黑暗 (D)",
  "Holy": "神圣 (H)",
  "Sorcery": "魔能 (S)",
  "Conjuration": "召唤 (C)",
  "Enchantment": "附魔 (E)",
  "Word": "真言 (W)",
  "Orb": "法球 (B)",
  "Dragon": "巨龙 (R)",
  "Translocation": "移位 (T)",
  "Metallic": "金属 (M)",
  "Eye": "视线 (Y)",
  "Chaos": "混沌 (O)",
}
