names = {
  # 从图鉴中提取
  "Goblin": "Goblin",
  "Giant Goblin": "Giant Goblin",
  "Armored Goblin": "Armored Goblin",
  "Red Goblin": "Red Goblin",
  "Lanky Goblin": "Lanky Goblin",
  "Psychic Goblin": "Psychic Goblin",
  "Goblin Void Demolitionist": "Goblin Void Demolitionist",
  "Goblin Fire Demolitionist": "Goblin Fire Demolitionist",
  "Goblin Siege Mechanic": "Goblin Siege Mechanic",
  "Bat": "Bat",
  "Vampire": "Vampire",
  "Vampire Bat": "Vampire Bat",
  "Giant Bat": "Giant Bat",
  "Toxic Bat": "Toxic Bat",
  "Flame Bat": "Flame Bat",
  "Flappy, Bat King": "Flappy, Bat King",
  "Void Bomber": "Void Bomber",
  "Void Rift": "Void Rift",
  "Giant Void Bomber": "Giant Void Bomber",
  "Giant Fire Bomber": "Giant Fire Bomber",
  "Void Cluster Bomber": "Void Cluster Bomber",
  "Fire Bomber": "Fire Bomber",
  "Flame Rift": "Flame Rift",
  "Fire Cluster Bomber": "Fire Cluster Bomber",
  "Fire Imp": "Fire Imp",
  "Furnace Imp": "Furnace Imp",
  "Chaos Imp": "Chaos Imp",
  "Ash Imp": "Ash Imp",
  "Firestorm Imp": "Firestorm Imp",
  "Giant Fire Imp": "Giant Fire Imp",
  "Krilt, Fire Imp King": "Krilt, Fire Imp King",
  "Void Imp": "Void Imp",
  "Insanity Imp": "Insanity Imp",
  "Rot Imp": "Rot Imp",
  "Imp Tablet": "Imp Tablet",
  "Spark Imp": "Spark Imp",
  "Copper Imp": "Copper Imp",
  "Giant Spark Imp": "Giant Spark Imp",
  "Xilet, Spark Imp King": "Xilet, Spark Imp King",
  "Ghost": "Ghost",
  "Void Ghost": "Void Ghost",
  "Giant Ghost": "Giant Ghost",
  "Fire Ghost": "Fire Ghost",
  "Ghost King": "Ghost King",
  "Ghostly Mass": "Ghostly Mass",
  "Witch": "Witch",
  "Haunter": "Haunter",
  "Mind Maggot": "Mind Maggot",
  "Giant Mind Maggot": "Giant Mind Maggot",
  "Mind Maggot Drone": "Mind Maggot Drone",
  "Flud, Mind Maggot King": "Flud, Mind Maggot King",
  "Mind Devourer": "Mind Devourer",
  "Mind Maggot Queen": "Mind Maggot Queen",
  "Displacer Beast": "Displacer Beast",
  "Displacer Broodmother": "Displacer Broodmother",
  "Razor Beast": "Razor Beast",
  "Giant Displacer Beast": "Giant Displacer Beast",
  "Spirit Strider": "Spirit Strider",
  "Bloodfrenzy Feline": "Bloodfrenzy Feline",
  "Nine the Cat": "Nine the Cat",
  "Green Mushboom": "Green Mushboom",
  "Giant Green Mushboom": "Giant Green Mushboom",
  "Acrinar, Green Mushboom King": "Acrinar, Green Mushboom King",
  "Glass Mushboom": "Glass Mushboom",
  "Swamp Queen": "Swamp Queen",
  "Mantis": "Mantis",
  "Metal Mantis": "Metal Mantis",
  "Giant Mantis": "Giant Mantis",
  "Ghost Mantis": "Ghost Mantis",
  "Lightning Mantis": "Lightning Mantis",
  "Void Mantis": "Void Mantis",
  "Snake": "Snake",
  "Giant Snake": "Giant Snake",
  "Lightning Snake": "Lightning Snake",
  "Fire Snake": "Fire Snake",
  "Death Snake": "Death Snake",
  "Slazephan, Serpent Philosopher": "Slazephan, Serpent Philosopher",
  "Spriggan": "Spriggan",
  "Spriggan Bush": "Spriggan Bush",
  "Toxic Spriggan": "Toxic Spriggan",
  "Toxic Spriggan Bush": "Toxic Spriggan Bush",
  "Icy Spriggan": "Icy Spriggan",
  "Icy Spriggan Bush": "Icy Spriggan Bush",
  "Treant": "Treant",
  "Boggart": "Boggart",
  "Toxic Boggart": "Toxic Boggart",
  "Giant Boggart": "Giant Boggart",
  "Boggart Aether Zealot": "Boggart Aether Zealot",
  "Trafflerabus, Boggart King": "Trafflerabus, Boggart King",
  "Boggart Void Mage": "Boggart Void Mage",
  "Boggart Assassin": "Boggart Assassin",
  "Iron Imp": "Iron Imp",
  "Giant Iron Imp": "Giant Iron Imp",
  "Tungsten Imp": "Tungsten Imp",
  "Thrahn, Iron Imp King": "Thrahn, Iron Imp King",
  "Satyr": "Satyr",
  "Zahlgrahd, Satyr King": "Zahlgrahd, Satyr King",
  "Giant Satyr": "Giant Satyr",
  "Wild Satyr": "Wild Satyr",
  "Dark Satyr": "Dark Satyr",
  "Armored Satyr": "Armored Satyr",
  "Large Worm Ball": "Large Worm Ball",
  "Giant Worm Ball": "Giant Worm Ball",
  "Large Iron Worm Ball": "Large Iron Worm Ball",
  "Large Toxic Worm Ball": "Large Toxic Worm Ball",
  "Large Ghost Worm Ball": "Large Ghost Worm Ball",
  "Kobold": "Kobold",
  "Pakkatok, Kobold King": "Pakkatok, Kobold King",
  "Kobold Longbowman": "Kobold Longbowman",
  "Kobold Crossbowman": "Kobold Crossbowman",
  "Kobold Siege Mechanic": "Kobold Siege Mechanic",
  "Faewitch": "Faewitch",
  "Ice Witch": "Ice Witch",
  "Fire Witch": "Fire Witch",
  "Old Witch": "Old Witch",
  "Blood Witch": "Blood Witch",
  "Orc": "Orc",
  "Orc Boar Rider": "Orc Boar Rider",
  "Orc Boar": "Orc Boar",
  "Orc Flame Zealot": "Orc Flame Zealot",
  "Orc Pyromancer": "Orc Pyromancer",
  "Akabalah, Orc King": "Akabalah, Orc King",
  "Orc Juggernaut": "Orc Juggernaut",
  "Orc Houndlord": "Orc Houndlord",
  "Giant Spider": "Giant Spider",
  "Giant Spider Queen": "Giant Spider Queen",
  "Steel Spider": "Steel Spider",
  "Aether Spider": "Aether Spider",
  "Arachnid Abombination": "Arachnid Abombination",
  "Aelf Arachnomancer": "Aelf Arachnomancer",
  "Ice Lizard": "Ice Lizard",
  "Giant Ice Lizard": "Giant Ice Lizard",
  "Ice Lizard Belcher": "Ice Lizard Belcher",
  "Armored Ice Lizard": "Armored Ice Lizard",
  "Fire Lizard": "Fire Lizard",
  "Giant Fire Lizard": "Giant Fire Lizard",
  "Fire Lizard Belcher": "Fire Lizard Belcher",
  "Armored Fire Lizard": "Armored Fire Lizard",
  "Grey Mushboom": "Grey Mushboom",
  "Giant Grey Mushboom": "Giant Grey Mushboom",
  "Palinar, Grey Mushboom King": "Palinar, Grey Mushboom King",
  "Horned Toad": "Horned Toad",
  "Ghost Toad": "Ghost Toad",
  "Towering Toadbeast": "Towering Toadbeast",
  "Void Toad": "Void Toad",
  "Flame Toad": "Flame Toad",
  "Rumplerog, Horned Toad King": "Rumplerog, Horned Toad King",
  "Toad Chaos Sorcerer": "Toad Chaos Sorcerer",
  "Toad Nightmare Sorcerer": "Toad Nightmare Sorcerer",
  "Raven": "Raven",
  "Possessed Raven": "Possessed Raven",
  "Giant Raven": "Giant Raven",
  "Toxic Raven": "Toxic Raven",
  "Wereraven": "Wereraven",
  "Wolf": "Wolf",
  "Raven Mage": "Raven Mage",
  "Goatia": "Goatia",
  "Giant Goatia": "Giant Goatia",
  "Steel Goatia": "Steel Goatia",
  "Ghostly Goatia": "Ghostly Goatia",
  "Goatia Tablet": "Goatia Tablet",
  "Centaur": "Centaur",
  "Centaur Druid": "Centaur Druid",
  "Armored Centaur": "Armored Centaur",
  "Trolltaur": "Trolltaur",
  "Ogre": "Ogre",
  "Thunderbone Shaman": "Thunderbone Shaman",
  "Ogre Juggernaut": "Ogre Juggernaut",
  "Blackblaze Shaman": "Blackblaze Shaman",
  "Spore Beast": "Spore Beast",
  "Toxic Spore Beast": "Toxic Spore Beast",
  "Spore Beast Alpha": "Spore Beast Alpha",
  "Possessed Spore Beast": "Possessed Spore Beast",
  "Bag of Bugs": "Bag of Bugs",
  "Bag of Fire Flies": "Bag of Fire Flies",
  "Bag of Lightning Bugs": "Bag of Lightning Bugs",
  "Giant Bag of Bugs": "Giant Bag of Bugs",
  "Bag of Brain Flies": "Bag of Brain Flies",
  "Troll": "Troll",
  "Yiggoroth, Troll King": "Yiggoroth, Troll King",
  "Earth Troll": "Earth Troll",
  "Storm Troll": "Storm Troll",
  "Troubler": "Troubler",
  "Troubling Mass": "Troubling Mass",
  "Big Troubler": "Big Troubler",
  "Iron Troubler": "Iron Troubler",
  "Glass Troubler": "Glass Troubler",
  "Evil Faery": "Evil Faery",
  "Faery Arcanist": "Faery Arcanist",
  "Fae Queen": "Fae Queen",
  "Ice Faery": "Ice Faery",
  "Glass Faery": "Glass Faery",
  "Vampire Count": "Vampire Count",
  "Greater Vampire": "Greater Vampire",
  "Vampiric Mist": "Vampiric Mist",
  "Mind Vampire": "Mind Vampire",
  "Vampire Eye": "Vampire Eye",
  "Vampire Necromancer": "Vampire Necromancer",
  "Armored Vampire": "Armored Vampire",
  "Gnome": "Gnome",
  "Micrognome": "Micrognome",
  "Iron Gnome": "Iron Gnome",
  "Gnome Druid": "Gnome Druid",
  "Gdeit, Gnome King": "Gdeit, Gnome King",
  "Giant Gnome": "Giant Gnome",
  "Copper Spider": "Copper Spider",
  "Furnace Spider": "Furnace Spider",
  "Steel Spider Queen": "Steel Spider Queen",
  "Steel Arachnid Abombination": "Steel Arachnid Abombination",
  "Massive Metal Mantis": "Massive Metal Mantis",
  "Copper Mantis": "Copper Mantis",
  "Furnace Mantis": "Furnace Mantis",
  "Green Slime": "Green Slime",
  "Green Slime Cube": "Green Slime Cube",
  "Shraggi, Green Slime King": "Shraggi, Green Slime King",
  "Void Slime": "Void Slime",
  "Ice Slime": "Ice Slime",
  "Red Slime": "Red Slime",
  "Slime Brewer": "Slime Brewer",
  "Bloodghast": "Bloodghast",
  "Old Blood Witch": "Old Blood Witch",
  "Blood Bear": "Blood Bear",
  "Blood Hound": "Blood Hound",
  "Polar Bear": "Polar Bear",
  "Giant Polar Bear": "Giant Polar Bear",
  "Polar Bear Blizzard Shaman": "Polar Bear Blizzard Shaman",
  "Possessed Polar Bear": "Possessed Polar Bear",
  "Armored Polar Bear": "Armored Polar Bear",
  "Hell Hound": "Hell Hound",
  "Ice Hound": "Ice Hound",
  "Furnace Hound": "Furnace Hound",
  "Chaos Hound": "Chaos Hound",
  "Insanity Hound": "Insanity Hound",
  "Cultist": "Cultist",
  "Lesser Demonic Altar": "Lesser Demonic Altar",
  "Greater Demonic Altar": "Greater Demonic Altar",
  "Cultist Necromancer": "Cultist Necromancer",
  "Cultist Chosen": "Cultist Chosen",
  "Werewolf": "Werewolf",
  "Wild Man": "Wild Man",
  "Werewolf Shaman": "Werewolf Shaman",
  "Werewolf Alpha": "Werewolf Alpha",
  "Possessed Werewolf": "Possessed Werewolf",
  "Possessed Wild Man": "Possessed Wild Man",
  "Blizzard Beast": "Blizzard Beast",
  "Chaos Chimera": "Chaos Chimera",
  "Fire Lion": "Fire Lion",
  "Giant Chaos Chimera": "Giant Chaos Chimera",
  "Giant Chaos Lion": "Giant Chaos Lion",
  "Thunderbird": "Thunderbird",
  "Bone Knight": "Bone Knight",
  "Bone Archer": "Bone Archer",
  "Bone Champion": "Bone Champion",
  "Ossuonobius, Bone King": "Ossuonobius, Bone King",
  "Bone Wizard": "Bone Wizard",
  "Spark Spirit": "Spark Spirit",
  "Chaos Spirit": "Chaos Spirit",
  "Storm Spirit": "Storm Spirit",
  "Fire Spirit": "Fire Spirit",
  "Starfire Spirit": "Starfire Spirit",
  "Golem": "Golem",
  "Clay Golem": "Clay Golem",
  "Gold Golem": "Gold Golem",
  "Spiked Golem": "Spiked Golem",
  "Redcap": "Redcap",
  "Green Gorgon": "Green Gorgon",
  "Giant Green Gorgon": "Giant Green Gorgon",
  "Possessed Green Gorgon": "Possessed Green Gorgon",
  "Earth Troll Coppermancer": "Earth Troll Coppermancer",
  "Earth Troll Magmancer": "Earth Troll Magmancer",
  "Earth Troll Priest": "Earth Troll Priest",
  "Aether Spider Queen": "Aether Spider Queen",
  "Aether Arachnid Abombination": "Aether Arachnid Abombination",
  "Spike Beast": "Spike Beast",
  "Spike Beast Alpha": "Spike Beast Alpha",
  "Possessed Spike Beast": "Possessed Spike Beast",
  "Old Faewitch": "Old Faewitch",
  "Old Fire Witch": "Old Fire Witch",
  "Old Ice Witch": "Old Ice Witch",
  "Night Hag": "Night Hag",
  "Dream Hag": "Dream Hag",
  "Red Slime Cube": "Red Slime Cube",
  "Praggi, Red Slime King": "Praggi, Red Slime King",
  "Ice Slime Cube": "Ice Slime Cube",
  "Xiaggi, Ice Slime King": "Xiaggi, Ice Slime King",
  "Living Scroll of Lightning": "Living Scroll of Lightning",
  "Living Scroll of Fireball": "Living Scroll of Fireball",
  "Duergar": "Duergar",
  "Duergar Executioner": "Duergar Executioner",
  "Duergar Lizard Lord": "Duergar Lizard Lord",
  "Duergar Dark Priest": "Duergar Dark Priest",
  "Fiery Tormentor": "Fiery Tormentor",
  "Giant Fiery Tormentor": "Giant Fiery Tormentor",
  "Fiery Tormenting Mass": "Fiery Tormenting Mass",
  "Ghostfire Tormentor": "Ghostfire Tormentor",
  "Frostfire Tormentor": "Frostfire Tormentor",
  "Dark Tormentor": "Dark Tormentor",
  "Giant Dark Tormentor": "Giant Dark Tormentor",
  "Dark Tormenting Mass": "Dark Tormenting Mass",
  "Deathchill Tormentor": "Deathchill Tormentor",
  "Rolling Spike Ball": "Rolling Spike Ball",
  "Toxic Spike Ball": "Toxic Spike Ball",
  "Ghostly Spike Ball": "Ghostly Spike Ball",
  "Tungsten Spike Ball": "Tungsten Spike Ball",
  "Copper Spike Ball": "Copper Spike Ball",
  "Gazing Spike Ball": "Gazing Spike Ball",
  "Floating Eyeball": "Floating Eyeball",
  "Ice Eye": "Ice Eye",
  "Mass of Eyes": "Mass of Eyes",
  "Flaming Eyeball": "Flaming Eyeball",
  "Storm Drake": "Storm Drake",
  "Massive Storm Drake": "Massive Storm Drake",
  "Armored Storm Drake": "Armored Storm Drake",
  "Fire Drake": "Fire Drake",
  "Massive Fire Drake": "Massive Fire Drake",
  "Armored Fire Drake": "Armored Fire Drake",
  "Bone Shambler": "Bone Shambler",
  "Towering Bone Shambler": "Towering Bone Shambler",
  "Bone Shambler Megalith": "Bone Shambler Megalith",
  "Greater Spore Beast": "Greater Spore Beast",
  "Giant Flame Toad": "Giant Flame Toad",
  "Armored Flame Toad": "Armored Flame Toad",
  "Giant Void Toad": "Giant Void Toad",
  "Armored Void Toad": "Armored Void Toad",
  "Storm Troll Juggernaut": "Storm Troll Juggernaut",
  "Storm Troll Mystic": "Storm Troll Mystic",
  "Minotaur": "Minotaur",
  "Metal Minotaur": "Metal Minotaur",
  "Dozadoka, Minotaur King": "Dozadoka, Minotaur King",
  "Minotaur Magma Shaman": "Minotaur Magma Shaman",
  "Aelf": "Aelf",
  "Aelf Aethermancer": "Aelf Aethermancer",
  "Aelf Lightning Artist": "Aelf Lightning Artist",
  "Aelf Siege Engineer": "Aelf Siege Engineer",
  "Meilmanir, Aelf King": "Meilmanir, Aelf King",
  "Aelf Elite": "Aelf Elite",
  "Purple Hand": "Purple Hand",
  "Iron Hand": "Iron Hand",
  "Jeweled Hand": "Jeweled Hand",
  "Gold Hand": "Gold Hand",
  "Deathchill Chimera": "Deathchill Chimera",
  "Ice Lion": "Ice Lion",
  "Giant Deathchill Chimera": "Giant Deathchill Chimera",
  "Giant Ice Lion": "Giant Ice Lion",
  "Glass Golem": "Glass Golem",
  "Starfire Chimera": "Starfire Chimera",
  "Star Lion": "Star Lion",
  "Giant Starfire Chimera": "Giant Starfire Chimera",
  "Giant Star Lion": "Giant Star Lion",
  "False Prophet": "False Prophet",
  "Giant Mind Devourer": "Giant Mind Devourer",
  "Fire Wyrm": "Fire Wyrm",
  "Fire Wyrm Broodmother": "Fire Wyrm Broodmother",
  "Armored Fire Wyrm": "Armored Fire Wyrm",
  "Gargoyle": "Gargoyle",
  "Gargoyle Statue": "Gargoyle Statue",
  "Mega Gargoyle": "Mega Gargoyle",
  "Mega Gargoyle Statue": "Mega Gargoyle Statue",
  "Ice Gargoyle": "Ice Gargoyle",
  "Ice Gargoyle Statue": "Ice Gargoyle Statue",
  "Fire Gargoyle": "Fire Gargoyle",
  "Fire Gargoyle Statue": "Fire Gargoyle Statue",
  "Void Slime Cube": "Void Slime Cube",
  "Eoggi, Void Slime King": "Eoggi, Void Slime King",
  "Cyclops": "Cyclops",
  "Giant Floating Skull": "Giant Floating Skull",
  "Golden Skull": "Golden Skull",
  "Giant Flaming Skull": "Giant Flaming Skull",
  "Grey Gorgon": "Grey Gorgon",
  "Efreet": "Efreet",
  "Pyrubo, Efreet King": "Pyrubo, Efreet King",
  "Efreet Juggernaut": "Efreet Juggernaut",
  "Yeti": "Yeti",
  "Giant Yeti": "Giant Yeti",
  "Yeti Shaman": "Yeti Shaman",
  "Void Drake": "Void Drake",
  "Massive Void Drake": "Massive Void Drake",
  "Armored Void Drake": "Armored Void Drake",
  "Cockatrice": "Cockatrice",
  "Butterfly Demon": "Butterfly Demon",
  "Chaos Knight": "Chaos Knight",
  "Chaos Champion": "Chaos Champion",
  "Vuldakot, Chaos King": "Vuldakot, Chaos King",
  "Gold Drake": "Gold Drake",
  "Massive Gold Drake": "Massive Gold Drake",
  "Armored Gold Drake": "Armored Gold Drake",
  "Frosty Tormentor": "Frosty Tormentor",
  "Giant Frosty Tormentor": "Giant Frosty Tormentor",
  "Elder Dream Hag": "Elder Dream Hag",
  "Ice Drake": "Ice Drake",
  "Ice Wyrm": "Ice Wyrm",
  "Ice Wyrm Broodmother": "Ice Wyrm Broodmother",
  "Armored Ice Wyrm": "Armored Ice Wyrm",
  "Fire Fiend": "Fire Fiend",
  "Storm Fiend": "Storm Fiend",
  "Iron Fiend": "Iron Fiend",
  "Lich": "Lich",
  "Void Knight": "Void Knight",
  "Void Champion": "Void Champion",
  "Zex Ku, Void King": "Zex Ku, Void King",
  "Storm Knight": "Storm Knight",
  "Storm Champion": "Storm Champion",
  "Koseidius, Storm King": "Koseidius, Storm King",
  "Nightmare Turtle": "Nightmare Turtle",
  "Lamasu": "Lamasu",
  "Greater Lamasu": "Greater Lamasu",
  "Gilded Lamasu": "Gilded Lamasu",
  "Ghostly Lamasu": "Ghostly Lamasu",
  "Corrupted Lamasu": "Corrupted Lamasu",
  "Glass Cockatrice": "Glass Cockatrice",
  "Glass Butterfly": "Glass Butterfly",
  "Phoenix": "Phoenix",
  "Volcano Turtle": "Volcano Turtle",
  "Dracolich": "Dracolich",
  "Aesir": "Aesir",
  "Titan": "Titan",
  "Reaper": "Reaper",
  "Fleshy Mass": "Fleshy Mass",
  "Chaos Fiend": "Chaos Fiend",
  "Copper Fiend": "Copper Fiend",
  "Furnace Fiend": "Furnace Fiend",
  "Insanity Fiend": "Insanity Fiend",
  "Rot Fiend": "Rot Fiend",
  "Ash Fiend": "Ash Fiend",
  "Energy Knight": "Energy Knight",
  "Twilight Knight": "Twilight Knight",
  "Idol of the Weak": "Idol of the Weak",
  "Idol of the Foolish": "Idol of the Foolish",
  "Idol of the Fickle": "Idol of the Fickle",
  "Necromancer": "Necromancer",
  "War Banner": "War Banner",
  "Watcher": "Watcher",
  "Void Watcher": "Void Watcher",
  "Fly Trap": "Fly Trap",
  "Idol of Undeath": "Idol of Undeath",
  "Idol of Life": "Idol of Life",
  "Dark Priest": "Dark Priest",
  "Rogath, Ogre King": "Rogath, Ogre King",
  "The Dreamer": "The Dreamer",
  "Fallen Angel": "Fallen Angel",
  "Spore Man Ancient": "Spore Man Ancient",
  "Tombstone": "Tombstone",
  "Yggdrasil": "Yggdrasil",
  "Idol of Sorcery": "Idol of Sorcery",
  "Idol of Clarity": "Idol of Clarity",
  "Time Keeper": "Time Keeper",
  "Giant Soul Jar": "Giant Soul Jar",
  "Medusa": "Medusa",
  "Bat Dragon": "Bat Dragon",
  "Red Cyclops": "Red Cyclops",
  "Chaos Quill": "Chaos Quill",
  "Fire Wyrm Egg": "Fire Wyrm Egg",
  "Ice Wyrm Egg": "Ice Wyrm Egg",
  "Box of Woe": "Box of Woe",
  "Jack O' Lantern": "Jack O' Lantern",
  "Avian Wizard": "Avian Wizard",
  "Lightning Master": "Lightning Master",
  "Mountain Mage": "Mountain Mage",
  "Masked Wizard": "Masked Wizard",
  "Arachnid Wizard": "Arachnid Wizard",
  "Dragon Mage": "Dragon Mage",
  "Troll Geomancer": "Troll Geomancer",
  "Void Magus": "Void Magus",
  "Glass Master": "Glass Master",
  "Demon Sorcerer": "Demon Sorcerer",
  "Twilight Seer": "Twilight Seer",
  "Ice Lich": "Ice Lich",
  "Fire Lich": "Fire Lich",
  "Ice Wizard": "Ice Wizard",
  "Goblin Wizard": "Goblin Wizard",
  "Frostfire Mage": "Frostfire Mage",
  "Starfire Sorcerer": "Starfire Sorcerer",
  "Fire Wizard": "Fire Wizard",
  "Enchanter": "Enchanter",
  "Black Rider": "Black Rider",
  "White Rider": "White Rider",
  "Red Rider": "Red Rider",
  "Pale Rider": "Pale Rider",
  "The Furnace": "The Furnace",
  "Pillar of Bones": "Pillar of Bones",
  "Pillar of Worms": "Pillar of Worms",
  "Imp Collector": "Imp Collector",
  "Feathered Serpent": "Feathered Serpent",
  "Translocator": "Translocator",
  "Mechanomancer": "Mechanomancer",
  "Minos, The Golden Bull": "Minos, The Golden Bull",
  "Chronos, Titan Immortal": "Chronos, Titan Immortal",
  "Odin, Aesir Immortal": "Odin, Aesir Immortal",
  "Gemini Twin": "Gemini Twin",
  "The Mischief Maker": "The Mischief Maker",
  "Slime Drake": "Slime Drake",
  "Void Phoenix": "Void Phoenix",
  "Slimesoul Idol": "Slimesoul Idol",
  "Crucible of Pain": "Crucible of Pain",
  "Idol of Fiery Vengeance": "Idol of Fiery Vengeance",
  "Concussive Idol": "Concussive Idol",
  "Idol of Vampirism": "Idol of Vampirism",
  "Mordred": "Mordred",
}
# names = {
# "Kobold": "狗头人",
# "Golem": "魔像",
# "Thunderbird": "雷鸟",
# "Rolling Spike Ball": "滚动刺球",
# "Copper Spike Ball": "铜质刺球",
# "Cyclops": "独眼巨人",
# "Storm Drake": "风暴亚龙",
# "Fire Drake": "火焰飞龙",
# "Void Drake": "虚空飞龙",
# "Gold Drake": "黄金飞龙",
# "Dracolich": "龙巫妖",
# "Ice Drake": "冰霜飞龙",
# "Fire Wyrm": "火焰龙鳗",
# "Ice Wyrm": "冰霜龙鳗",
# "Fire Wyrm Egg": "火焰龙鳗蛋",
# "Ice Wyrm Egg": "冰霜龙鳗蛋",
# "Fire Imp": "火焰小恶魔",
# "Spark Imp": "电光小恶魔",
# "Iron Imp": "铁质小恶魔",
# "Chaos Imp": "混沌小恶魔",
# "Furnace Imp": "熔炉小恶魔",
# "Ash Imp": "灰烬小恶魔",
# "Tungsten Imp": "钨质小恶魔",
# "Rot Imp": "腐败小恶魔",
# "Copper Imp": "铜质小恶魔",
# "Insanity Imp": "疯狂小恶魔",
# "Void Imp": "虚空小恶魔",
# "Giant Iron Imp": "巨大铁质小恶魔",
# "Giant Fire Imp": "巨大火焰小恶魔",
# "Giant Spark Imp": "巨大电光小恶魔",
# "Fire Spirit": "火焰小精灵",
# "Spark Spirit": "电光小精灵",
# "Fly Swarm": "飞行虫群",
# "Bag of Bugs": "Bag of Bugs",
# "Spore Beast": "孢子兽",
# "Greater Spore Beast": "大孢子兽",
# "Spike Beast": "Spike Beast",
# "Blizzard Beast": "Blizzard Beast",
# "Void Bomber": "虚空炸弹",
# "Fire Bomber": "火焰炸弹",
# "Displacer Beast": "移形怪",
# "Orc": "兽人",
# "Satyr": "Satyr",
# "Boggart": "Boggart",
# "Mind Maggot": "心灵 Maggot",
# "Mind Maggot Queen": "心灵 Maggot Queen",
# "Centaur": "半人马",
# "Ogre": "食人魔",
# "Troll": "巨魔",
# "Earth Troll": "大地巨魔",
# "Storm Troll": "风暴巨魔",
# "Ghost": "鬼魂",
# "Fire Ghost": "火焰鬼魂",
# "Ghostly Mass": "Ghostly Mass",
# "Ghost King": "鬼魂王",
# "Goblin": "哥布林",
# "Bat": "蝙蝠",
# "Green Slime": "绿史莱姆",
# "Red Slime": "红史莱姆",
# "Ice Slime": "冰霜史莱姆",
# "Void Slime": "虚空史莱姆",
# "Displacer Broodmother": "移形怪族母",
# "Efreet": "Efreet",
# "Bone Shambler Megalith": "骨聚合体巨像",
# "Towering Bone Shambler": "高大骨聚合体",
# "Bone Shambler": "骨聚合体",
# "Bone Shambler Fragment": "骨聚合体碎片",
# "Giant Worm Ball": "大型虫球",
# "Large Worm Ball": "中型虫球",
# "Small Worm Ball": "小型虫球",
# "Glass Faery": "玻璃仙灵",
# "Evil Faery": "邪恶仙灵",
# "Hell Hound": "地狱猎犬",
# "Ice Hound": "冰霜猎犬",
# "Minotaur": "牛头怪",
# "Cockatrice": "鸡蛇兽",
# "Void Rift": "虚空裂隙",
# "Flame Rift": "火焰裂隙",
# "Butterfly Demon": "蝴蝶恶魔",
# "Horned Toad": "有角蟾蜍",
# "Towering Toadbeast": "高大蟾蜍兽",
# "Flame Toad": "火焰蟾蜍",
# "Void Toad": "虚空蟾蜍",
# "Giant Spider": "巨大蜘蛛",
# "Steel Spider": "钢铁蜘蛛",
# "Aether Spider": "以太蜘蛛",
# "Void Knight": "虚空骑士",
# "Chaos Knight": "混沌骑士",
# "Storm Knight": "风暴骑士",
# "Twilight Knight": "暮光骑士",
# "Energy Knight": "能量骑士",
# "Lamasu": "拉玛苏",
# "Nightmare Turtle": "梦魇龟",
# "Vampire Bat": "吸血蝠",
# "Vampire": "吸血鬼",
# "Bone Knight": "骨骑士",
# "Bone Wizard": "骨巫师",
# "False Prophet": "伪先知",
# "Green Mushboom": "绿蘑菇",
# "Grey Mushboom": "灰蘑菇",
# "Glass Mushboom": "玻璃蘑菇",
# "Red Mushboom": "红蘑菇",
# "Swamp Queen": "Swamp Queen",
# "Spriggan Bush": "守宝妖精 Bush",
# "Spriggan": "守宝妖精",
# "Icy Spriggan Bush": "Icy守宝妖精 Bush",
# "Icy Spriggan": "Icy守宝妖精",
# "Treant": "树精",
# "Vampiric Mist": "吸血迷雾",
# "Greater Vampire": "大吸血鬼",
# "Vampire Eye": "Vampire Eye",
# "Mind Vampire": "心灵吸血鬼",
# "Fae Thorn": "Fae Thorn",
# "Fae Queen": "Fae Queen",
# "Floating Eyeball": "漂浮眼球",
# "Flaming Eyeball": "带火眼球",
# "Aelf": "精灵",
# "Duergar": "灰矮人",
# "Redcap": "红帽子",
# "Gnome": "地精",
# "Aelf Lightning Artist": "精灵雷术师",
# "Orc Pyromancer": "兽人炎术师",
# "Faery Arcanist": "仙灵奥术师",
# "Fire Fiend": "火焰恶鬼",
# "Chaos Fiend": "混沌恶鬼",
# "Copper Fiend": "铜质恶鬼",
# "Furnace Fiend": "熔炉恶鬼",
# "Insanity Fiend": "疯狂恶鬼",
# "Rot Fiend": "腐败恶鬼",
# "Ash Fiend": "灰烬恶鬼",
# "Storm Fiend": "风暴恶鬼",
# "Iron Fiend": "铁质恶鬼",
# "Troubler": "Troubler",
# "Witch": "Witch",
# "Old Witch": "Old Witch",
# "Fire Witch": "火焰 Witch",
# "Old Blood Witch": "Old血Witch",
# "Blood Witch": "血Witch",
# "Wild Man": "野人",
# "Werewolf": "狼人",
# "Cultist": "邪教徒",
# "Green Gorgon": "绿戈尔贡",
# "Grey Gorgon": "灰戈尔贡",
# "Raven Mage": "Raven Mage",
# "Raven": "Raven",
# "Polar Bear": "北极熊",
# "Mind Devourer": "心灵吞噬者",
# "Giant Floating Skull": "巨大漂浮颅骨",
# "Golden Skull": "金色颅骨",
# "Purple Hand": "Purple Hand",
# "Blood Bear": "Blood Bear",
# "Bloodghast": "Bloodghast",
# "Blood Hound": "鲜血猎犬",
# "Living Scroll of Lightning": "闪电活卷轴",
# "Living Scroll of Fireball": "火球活卷轴",
# "Fiery Tormentor": "Fiery Tormentor",
# "Frostfire Tormentor": "Frostfire Tormentor",
# "Ghostfire Tormentor": "Ghostfire Tormentor",
# "Dark Tormentor": "Dark Tormentor",
# "Frosty Tormentor": "Frosty Tormentor",
# "Yeti": "雪怪",
# "Goatia": "Goatia",
# "Fire Lion": "火焰狮子",
# "Lightning Snake": "闪电蛇",
# "Chaos Chimera": "混沌奇美拉",
# "Ice Lion": "冰霜狮子",
# "Death Snake": "死之蛇",
# "Deathchill Chimera": "死寒奇美拉",
# "Star Lion": "星辰狮子",
# "Fire Snake": "火焰蛇",
# "Starfire Chimera": "星火奇美拉",
# "Mordred": "莫德雷德",
# "Giant Flaming Skull": "巨大带火颅骨",
# "Volcano Turtle": "火山龟",
# "Titan": "泰坦",
# "Aesir": "Aesir",
# "Fleshy Mass": "Fleshy Mass",
# "Reaper": "死神",
# "Mass of Eyes": "Mass of Eyes",
# "Gargoyle Statue": "Gargoyle Statue",
# "Gargoyle": "Gargoyle",
# }
