names = {
    "Earthquake Orb": "地震法球",
    "Aether Dagger": "以太匕首",
    "Bag of Bags": "一袋袋子",
    "Bag of Spikes": "一袋钉子",
    "Chaos Bell": "混乱之铃",
    "Death Dice": "死亡之骰",
    "Dragon Horn": "巨龙号角",
    "Draught of Memories": "记忆合剂",
    "Earth Troll Crown": "大地巨魔王冠",
    "Elixir of Youth": "青春合剂",
    "Energy Shield": "能量护盾",
    "Golden Stopwatch": "金质怀表",
    "Healing Potion": "治疗药剂",
    "Mana Potion": "魔法药水",
    "Oculus": "天眼",
    "Orb of Corruption": "污染法球",
    "Portal Disruptor": "传送门扰动器",
    "Portal Key": "传送门钥匙",
    "Shrine Disruptor": "神龛扰动器",
    "Stone Shield": "坚石护盾",
    "Storm Troll Crown": "风暴巨魔王冠",
    "Teleporter": "传送器",
    "Troll Crown": "巨魔王冠",
}
