names = {
  "Kobold": "Kobold",
  "Golem": "Golem",
  "Thunderbird": "Thunderbird",
  "Rolling Spike Ball": "Rolling Spike Ball",
  "Copper Spike Ball": "Copper Spike Ball",
  "Cyclops": "Cyclops",
  "Storm Drake": "Storm Drake",
  "Fire Drake": "Fire Drake",
  "Void Drake": "Void Drake",
  "Gold Drake": "Gold Drake",
  "Dracolich": "Dracolich",
  "Ice Drake": "Ice Drake",
  "Fire Wyrm": "Fire Wyrm",
  "Ice Wyrm": "Ice Wyrm",
  "Fire Wyrm Egg": "Fire Wyrm Egg",
  "Ice Wyrm Egg": "Ice Wyrm Egg",
  "Fire Imp": "Fire Imp",
  "Spark Imp": "Spark Imp",
  "Iron Imp": "Iron Imp",
  "Chaos Imp": "Chaos Imp",
  "Furnace Imp": "Furnace Imp",
  "Ash Imp": "Ash Imp",
  "Tungsten Imp": "Tungsten Imp",
  "Rot Imp": "Rot Imp",
  "Copper Imp": "Copper Imp",
  "Insanity Imp": "Insanity Imp",
  "Void Imp": "Void Imp",
  "Giant Iron Imp": "Giant Iron Imp",
  "Giant Fire Imp": "Giant Fire Imp",
  "Giant Spark Imp": "Giant Spark Imp",
  "Fire Spirit": "Fire Spirit",
  "Spark Spirit": "Spark Spirit",
  "Fly Swarm": "Fly Swarm",
  "Bag of Bugs": "Bag of Bugs",
  "Spore Beast": "Spore Beast",
  "Greater Spore Beast": "Greater Spore Beast",
  "Spike Beast": "Spike Beast",
  "Blizzard Beast": "Blizzard Beast",
  "Void Bomber": "Void Bomber",
  "Fire Bomber": "Fire Bomber",
  "Displacer Beast": "Displacer Beast",
  "Orc": "Orc",
  "Satyr": "Satyr",
  "Boggart": "Boggart",
  "Mind Maggot": "Mind Maggot",
  "Mind Maggot Queen": "Mind Maggot Queen",
  "Centaur": "Centaur",
  "Ogre": "Ogre",
  "Troll": "Troll",
  "Earth Troll": "Earth Troll",
  "Storm Troll": "Storm Troll",
  "Ghost": "Ghost",
  "Fire Ghost": "Fire Ghost",
  "Ghostly Mass": "Ghostly Mass",
  "Ghost King": "Ghost King",
  "Goblin": "Goblin",
  "Bat": "Bat",
  "Green Slime": "Green Slime",
  "Red Slime": "Red Slime",
  "Ice Slime": "Ice Slime",
  "Void Slime": "Void Slime",
  "Displacer Broodmother": "Displacer Broodmother",
  "Efreet": "Efreet",
  "Bone Shambler Megalith": "Bone Shambler Megalith",
  "Towering Bone Shambler": "Towering Bone Shambler",
  "Bone Shambler": "Bone Shambler",
  "Bone Shambler Fragment": "Bone Shambler Fragment",
  "Giant Worm Ball": "Giant Worm Ball",
  "Large Worm Ball": "Large Worm Ball",
  "Small Worm Ball": "Small Worm Ball",
  "Glass Faery": "Glass Faery",
  "Evil Faery": "Evil Faery",
  "Hell Hound": "Hell Hound",
  "Ice Hound": "Ice Hound",
  "Minotaur": "Minotaur",
  "Cockatrice": "Cockatrice",
  "Void Rift": "Void Rift",
  "Flame Rift": "Flame Rift",
  "Butterfly Demon": "Butterfly Demon",
  "Horned Toad": "Horned Toad",
  "Towering Toadbeast": "Towering Toadbeast",
  "Flame Toad": "Flame Toad",
  "Void Toad": "Void Toad",
  "Giant Spider": "Giant Spider",
  "Steel Spider": "Steel Spider",
  "Aether Spider": "Aether Spider",
  "Void Knight": "Void Knight",
  "Chaos Knight": "Chaos Knight",
  "Storm Knight": "Storm Knight",
  "Twilight Knight": "Twilight Knight",
  "Energy Knight": "Energy Knight",
  "Lamasu": "Lamasu",
  "Nightmare Turtle": "Nightmare Turtle",
  "Vampire Bat": "Vampire Bat",
  "Vampire": "Vampire",
  "Bone Knight": "Bone Knight",
  "Bone Wizard": "Bone Wizard",
  "False Prophet": "False Prophet",
  "Green Mushboom": "Green Mushboom",
  "Grey Mushboom": "Grey Mushboom",
  "Glass Mushboom": "Glass Mushboom",
  "Red Mushboom": "Red Mushboom",
  "Swamp Queen": "Swamp Queen",
  "Spriggan Bush": "Spriggan Bush",
  "Spriggan": "Spriggan",
  "Icy Spriggan Bush": "Icy Spriggan Bush",
  "Icy Spriggan": "Icy Spriggan",
  "Treant": "Treant",
  "Vampiric Mist": "Vampiric Mist",
  "Greater Vampire": "Greater Vampire",
  "Vampire Eye": "Vampire Eye",
  "Mind Vampire": "Mind Vampire",
  "Fae Thorn": "Fae Thorn",
  "Fae Queen": "Fae Queen",
  "Floating Eyeball": "Floating Eyeball",
  "Flaming Eyeball": "Flaming Eyeball",
  "Aelf": "Aelf",
  "Duergar": "Duergar",
  "Redcap": "Redcap",
  "Gnome": "Gnome",
  "Aelf Lightning Artist": "Aelf Lightning Artist",
  "Orc Pyromancer": "Orc Pyromancer",
  "Faery Arcanist": "Faery Arcanist",
  "Fire Fiend": "Fire Fiend",
  "Chaos Fiend": "Chaos Fiend",
  "Copper Fiend": "Copper Fiend",
  "Furnace Fiend": "Furnace Fiend",
  "Insanity Fiend": "Insanity Fiend",
  "Rot Fiend": "Rot Fiend",
  "Ash Fiend": "Ash Fiend",
  "Storm Fiend": "Storm Fiend",
  "Iron Fiend": "Iron Fiend",
  "Troubler": "Troubler",
  "Witch": "Witch",
  "Old Witch": "Old Witch",
  "Fire Witch": "Fire Witch",
  "Old Blood Witch": "Old Blood Witch",
  "Blood Witch": "Blood Witch",
  "Wild Man": "Wild Man",
  "Werewolf": "Werewolf",
  "Cultist": "Cultist",
  "Green Gorgon": "Green Gorgon",
  "Grey Gorgon": "Grey Gorgon",
  "Raven Mage": "Raven Mage",
  "Raven": "Raven",
  "Polar Bear": "Polar Bear",
  "Mind Devourer": "Mind Devourer",
  "Giant Floating Skull": "Giant Floating Skull",
  "Golden Skull": "Golden Skull",
  "Purple Hand": "Purple Hand",
  "Blood Bear": "Blood Bear",
  "Bloodghast": "Bloodghast",
  "Blood Hound": "Blood Hound",
  "Living Scroll of Lightning": "Living Scroll of Lightning",
  "Living Scroll of Fireball": "Living Scroll of Fireball",
  "Fiery Tormentor": "Fiery Tormentor",
  "Frostfire Tormentor": "Frostfire Tormentor",
  "Ghostfire Tormentor": "Ghostfire Tormentor",
  "Dark Tormentor": "Dark Tormentor",
  "Frosty Tormentor": "Frosty Tormentor",
  "Yeti": "Yeti",
  "Goatia": "Goatia",
  "Fire Lion": "Fire Lion",
  "Lightning Snake": "Lightning Snake",
  "Chaos Chimera": "Chaos Chimera",
  "Ice Lion": "Ice Lion",
  "Death Snake": "Death Snake",
  "Deathchill Chimera": "Deathchill Chimera",
  "Star Lion": "Star Lion",
  "Fire Snake": "Fire Snake",
  "Starfire Chimera": "Starfire Chimera",
  "Mordred": "Mordred",
  "Giant Flaming Skull": "Giant Flaming Skull",
  "Volcano Turtle": "Volcano Turtle",
  "Titan": "Titan",
  "Aesir": "Aesir",
  "Fleshy Mass": "Fleshy Mass",
  "Reaper": "Reaper",
  "Mass of Eyes": "Mass of Eyes",
  "Gargoyle Statue": "Gargoyle Statue",
  "Gargoyle": "Gargoyle",
}
