names = {
  "Earthquake Orb": "Earthquake Orb",
  "Aether Dagger": "Aether Dagger",
  "Bag of Bags": "Bag of Bags",
  "Bag of Spikes": "Bag of Spikes",
  "Chaos Bell": "Chaos Bell",
  "Death Dice": "Death Dice",
  "Dragon Horn": "Dragon Horn",
  "Draught of Memories": "Draught of Memories",
  "Earth Troll Crown": "Earth Troll Crown",
  "Elixir of Youth": "Elixir of Youth",
  "Energy Shield": "Energy Shield",
  "Golden Stopwatch": "Golden Stopwatch",
  "Healing Potion": "Healing Potion",
  "Mana Potion": "Mana Potion",
  "Oculus": "Oculus",
  "Orb of Corruption": "Orb of Corruption",
  "Portal Disruptor": "Portal Disruptor",
  "Portal Key": "Portal Key",
  "Shrine Disruptor": "Shrine Disruptor",
  "Stone Shield": "Stone Shield",
  "Storm Troll Crown": "Storm Troll Crown",
  "Teleporter": "Teleporter",
  "Troll Crown": "Troll Crown",
}
