normal = {
  "Fire": "火焰",
  "Lightning": "闪电",
  "Ice": "冰霜",
  "Nature": "自然",
  "Arcane": "奥法",
  "Dark": "黑暗",
  "Holy": "神圣",
  "Sorcery": "魔能",
  "Conjuration": "召唤",
  "Enchantment": "附魔",
  "Word": "真言",
  "Orb": "法球",
  "Dragon": "巨龙",
  "Translocation": "移位",
  "Metallic": "金属",
  "Eye": "视线",
  "Chaos": "混沌",
}
color = {
  "Fire": "[火焰:fire]",
  "Lightning": "[闪电:lightning]",
  "Ice": "[冰霜:ice]",
  "Nature": "[自然:nature]",
  "Arcane": "[奥法:arcane]",
  "Dark": "[黑暗:dark]",
  "Holy": "[神圣:holy]",
  "Sorcery": "[魔能:sorcery]",
  "Conjuration": "[召唤:conjuration]",
  "Enchantment": "[附魔:enchantment]",
  "Word": "[真言:word]",
  "Orb": "[法球:orb]",
  "Dragon": "[巨龙:dragon]",
  "Translocation": "[移位:translocation]",
  "Metallic": "[金属:metallic]",
  "Eye": "[视线:eye]",
  "Chaos": "[混沌:chaos]",
}
filter = {
  "Fire": "火焰 (F)",
  "Lightning": "闪电 (L)",
  "Ice": "冰霜 (I)",
  "Nature": "自然 (N)",
  "Arcane": "奥法 (A)",
  "Dark": "黑暗 (D)",
  "Holy": "神圣 (H)",
  "Sorcery": "魔能 (S)",
  "Conjuration": "召唤 (C)",
  "Enchantment": "附魔 (E)",
  "Word": "真言 (W)",
  "Orb": "法球 (B)",
  "Dragon": "巨龙 (R)",
  "Translocation": "移位 (T)",
  "Metallic": "金属 (M)",
  "Eye": "视线 (Y)",
  "Chaos": "混沌 (O)",
}
