names = {
  "Flame Tongue": "Flame Tongue",
  "Fireball": "Fireball",
  "Meteor Shower": "Meteor Shower",
  "Lightning Bolt": "Lightning Bolt",
  "Annihilate": "Annihilate",
  "Mega Annihilate": "Mega Annihilate",
  "Teleport": "Teleport",
  "Blink": "Blink",
  "Flame Gate": "Flame Gate",
  "Lightning Form": "Lightning Form",
  "Void Beam": "Void Beam",
  "Thunder Strike": "Thunder Strike",
  "Stone Giant Form": "Stone Giant Form",
  "Chaos Barrage": "Chaos Barrage",
  "Inferno": "Inferno",
  "Disperse": "Disperse",
  "Petrify": "Petrify",
  "Petrification Aura": "Petrification Aura",
  "Wolf": "Wolf",
  "Dire Wolf": "Dire Wolf",
  "Giant Bear": "Giant Bear",
  "Sight of Blood": "Sight of Blood",
  "Darkness": "Darkness",
  "Lightning Storm": "Lightning Storm",
  "Prison of Thorns": "Prison of Thorns",
  "Pillar of Fire": "Pillar of Fire",
  "Cloud Armor": "Cloud Armor",
  "Boiling Blood": "Boiling Blood",
  "Healing Light": "Healing Light",
  "Regeneration Aura": "Regeneration Aura",
  "Void Orb": "Void Orb",
  "Searing Orb": "Searing Orb",
  "Ball Lightning": "Ball Lightning",
  "Glass Orb": "Glass Orb",
  "Ice Orb": "Ice Orb",
  "Orb Control": "Orb Control",
  "Dominate": "Dominate",
  "Eye of Fire": "Eye of Fire",
  "Eye of Lightning": "Eye of Lightning",
  "Eye of Ice": "Eye of Ice",
  "Eye of Rage": "Eye of Rage",
  "Nightmare Aura": "Nightmare Aura",
  "Basilisk Armor": "Basilisk Armor",
  "Watcher Form": "Watcher Form",
  "Imp Swarm": "Imp Swarm",
  "Lightning Halo": "Lightning Halo",
  "Mystic Vision": "Mystic Vision",
  "Mystic Power": "Mystic Power",
  "Power of Pain": "Power of Pain",
  "Flame Burst": "Flame Burst",
  "Fire Drake": "Fire Drake",
  "Storm Drake": "Storm Drake",
  "Void Drake": "Void Drake",
  "Ice Drake": "Ice Drake",
  "Spark": "Spark",
  "Chain Lightning": "Chain Lightning",
  "Death Bolt": "Death Bolt",
  "Wheel of Death": "Wheel of Death",
  "Touch of Death": "Touch of Death",
  "Seal Fate": "Seal Fate",
  "Volcanic Eruption": "Volcanic Eruption",
  "Soul Swap": "Soul Swap",
  "Underworld Passage": "Underworld Passage",
  "Void Spawning": "Void Spawning",
  "Earthen Sentinel": "Earthen Sentinel",
  "Ghostball": "Ghostball",
  "Mystic Memory": "Mystic Memory",
  "Conjure Memories": "Conjure Memories",
  "Weave Sorcery": "Weave Sorcery",
  "Permanence": "Permanence",
  "Death Gaze": "Death Gaze",
  "Bone Barrage": "Bone Barrage",
  "Invoke Savagery": "Invoke Savagery",
  "Magic Missile": "Magic Missile",
  "Devour Mind": "Devour Mind",
  "Death Shock": "Death Shock",
  "Melt": "Melt",
  "Dragon Roar": "Dragon Roar",
  "Ironize": "Ironize",
  "Word of Undeath": "Word of Undeath",
  "Word of Chaos": "Word of Chaos",
  "Word of Beauty": "Word of Beauty",
  "Word of Madness": "Word of Madness",
  "Floating Eye": "Floating Eye",
  "Chimera Familiar": "Chimera Familiar",
  "Arc Lightning": "Arc Lightning",
  "Poison Sting": "Poison Sting",
  "Fan of Flames": "Fan of Flames",
  "Blue Lion": "Blue Lion",
  "Death Cleave": "Death Cleave",
  "Cantrip Cascade": "Cantrip Cascade",
  "Multicast": "Multicast",
  "Fae Court": "Fae Court",
  "Ring of Spiders": "Ring of Spiders",
  "Heavenly Blast": "Heavenly Blast",
  "Holy Fire": "Holy Fire",
  "Sing": "Sing",
  "Choir of Angels": "Choir of Angels",
  "Heaven's Wrath": "Heaven's Wrath",
  "Suspend Mortality": "Suspend Mortality",
  "Soul Tax": "Soul Tax",
  "Holy Armor": "Holy Armor",
  "Blinding Light": "Blinding Light",
  "Flock of Eagles": "Flock of Eagles",
  "Flaming Arc": "Flaming Arc",
  "Flaming Sword": "Flaming Sword",
  "Heavenly Idol": "Heavenly Idol",
  "Gold Drake": "Gold Drake",
  "Flaming Sword": "Flaming Sword",
  "Call Seraph": "Call Seraph",
  "Archon Lightning": "Archon Lightning",
  "Call Archon": "Call Archon",
  "Pain Mirror": "Pain Mirror",
  "Pyrostatic Pulse": "Pyrostatic Pulse",
  "Thunder Stones": "Thunder Stones",
  "Fire Stones": "Fire Stones",
  "Aether Swap": "Aether Swap",
  "Siphon Shields": "Siphon Shields",
  "Hungry Maw": "Hungry Maw",
  "Hollow Flesh": "Hollow Flesh",
  "Conductance": "Conductance",
  "Shrapnel Blast": "Shrapnel Blast",
  "Plague of Filth": "Plague of Filth",
  "Fiery Tormentor": "Fiery Tormentor",
  "Dispersion Field": "Dispersion Field",
  "Knightly Oath": "Knightly Oath",
  "Toxin Burst": "Toxin Burst",
  "Toxic Spores": "Toxic Spores",
  "Amplify Venom": "Amplify Venom",
  "Combust Poison": "Combust Poison",
  "Venom Beast": "Venom Beast",
  "Spider Queen": "Spider Queen",
  "Freeze": "Freeze",
  "Iceball": "Iceball",
  "Blizzard": "Blizzard",
  "Frostfire Hydra": "Frostfire Hydra",
  "Storm Burst": "Storm Burst",
  "Death Chill": "Death Chill",
  "Ice Phoenix": "Ice Phoenix",
  "Word of Ice": "Word of Ice",
  "Ice Weave": "Ice Weave",
  "Icicle": "Icicle",
  "Chill Wind": "Chill Wind",
  "Wall of Ice": "Wall of Ice",
  "Earthquake": "Earthquake",
  "Searing Seal": "Searing Seal",
  "Purity": "Purity",
  "Twilight Gaze": "Twilight Gaze",
  "Slime Form": "Slime Form",
  "Blazerip": "Blazerip",
  "Ice Vortex": "Ice Vortex",
  "The Restless Dead": "The Restless Dead",
  "Gust of Wind": "Gust of Wind",
  "Pyrostatic Curse": "Pyrostatic Curse",
  "Spikeball Factory": "Spikeball Factory",
  "Mercurize": "Mercurize",
  "Magnetize": "Magnetize",
  "Silver Spear": "Silver Spear",
  "Siege Golems": "Siege Golems",
  "Zap": "Zap",
  "Lightning Spire": "Lightning Spire",
  "Essence Flux": "Essence Flux",
}
