names = {
  "Healing Potion": "治疗药剂",
  "Teleporter": "传送器",
  "Chaos Bell": "混乱之铃",
  "Golden Stopwatch": "金质怀表",
  "Death Dice": "死亡之骰",
  "Energy Shield": "能量护盾",
  "Stone Shield": "坚石护盾",
  "Mana Potion": "魔法药水",
  "Earthquake Orb": "地震法球",
  "Dragon Horn": "巨龙号角",
  "Portal Disruptor": "传送门扰动器",
  "Shrine Disruptor": "神龛扰动器",
  "Portal Key": "传送门钥匙",
  "Orb of Corruption": "污染法球",
  "Elixir of Youth": "青春合剂",
  "Aether Dagger": "以太匕首",
  "Oculus": "天眼",
  "Draught of Memories": "记忆合剂",
  "Bag of Spikes": "一袋钉子",
  "Bag of Bags": "一袋袋子",
  "Troll Crown": "巨魔王冠",
  "Storm Troll Crown": "风暴巨魔王冠",
  "Earth Troll Crown": "大地巨魔王冠",
}
