spells = {
    "Fireball": "",
    "Lightning Bolt": "",
    "Annihilate": "",
    "Lightning Form": "",
    "Mega Annihilate": "",
    "Teleport": "",
    "Blink": "",
    "Void Beam": "",
    "Thunder Strike": "",
    "Chaos Barrage": "",
    "Disperse": "",
    "Petrify": "",
    "Wolf": "",
    "Giant Bear": "",
    "Sight of Blood": "",
    "Lightning Storm": "",
    "Prison of Thorns": "",
    "Pillar of Fire": "",
    "Boiling Blood": "",
    "Healing Light": "",
    "Regeneration Aura": "",
    "Arcane Orb": "",
    "Dominate": "",
    "Flame Gate": "",
    "Eye of Fire": "",
    "Eye of Lightning": "",
    "Eye of Ice": "",
    "Nightmare Aura": "",
    "Basilisk Armor": "",
    "Watcher Form": "",
    "Imp Swarm": "",
    "Lightning Halo": "",
    "Mystic Vision": "",
    "Mystic Power": "",
    "Flame Burst": "",
    "Fire Drake": "",
    "Storm Drake": "",
    "Void Drake": "",
    "Ice Drake": "",
    "Chain Lightning": "",
    "Death Bolt": "",
    "Touch of Death": "",
    "Seal Fate": "",
    "Wheel of Death": "",
    "Volcanic Eruption": "",
    "Underworld Passage": "",
    "Earthen Sentinel": "",
    "Ghostball": "",
    "Mystic Memory": "",
    "Permanence": "",
    "Vampiric Gaze": "",
    "Magic Missile": "",
    "Devour Mind": "",
    "Death Shock": "",
    "Melt": "",
    "Dragon Roar": "",
    "Ironize": "",
    "Word of Chaos": "",
    "Word of Undeath": "",
    "Word of Beauty": "",
    "Floating Eye": "",
    "Eye of Rage": "",
    "Arc Lightning": "",
    "Fan of Flames": "",
    "Poison Sting": "",
    "Blue Lion": "",
    "Death Cleave": "",
    "Multicast": "",
    "Fae Court": "",
    "Ring of Spiders": "",
    "Word of Madness": "",
    "Heavenly Blast": "",
    "Holy Fire": "",
    "Choir of Angels": "",
    "Heaven's Wrath": "",
    "Suspend Mortality": "",
    "Soul Tax": "",
    "Holy Armor": "",
    "Blinding Light": "",
    "Flock of Eagles": "",
    "Heavenly Idol": "",
    "Gold Drake": "",
    "Call Seraph": "",
    "Call Archon": "",
    "Pain Mirror": "",
    "Pyrostatic Pulse": "",
    "Aether Swap": "",
    "Siphon Shields": "",
    "Hungry Maw": "",
    "Darkness": "",
    "Plague of Undeath": "",
    "Cantrip Cascade": "",
    "Conductance": "",
    "Invoke Savagery": "",
    "Rain of Fire": "",
    "Shrapnel Blast": "",
    "Plague of Filth": "",
    "Searing Orb": "",
    "Ball Lightning": "",
    "Orb Control": "",
    "Glass Orb": "",
    "Fiery Tormentor": "",
    "Petrification Aura": "",
    "Dispersion Field": "",
    "Knightly Oath": "",
    "Toxin Burst": "",
    "Toxic Spores": "",
    "Combust Poison": "",
    "Spider Queen": "",
    "Freeze": "",
    "Iceball": "",
    "Blizzard": "",
    "Frostfire Hydra": "",
    "Storm Burst": "",
    "Death Chill": "",
    "Ice Phoenix": "",
    "Word of Ice": "",
    "Ice Orb": "",
    "Icicle": "",
    "Chill Wind": "",
    "Wall of Ice": "",
    "Bone Barrage": "",
    "Earthquake": "",
    "Searing Seal": "",
    "Soul Swap": "",
    "Purity": "",
    "Twilight Gaze": "",
    "Slime Form": "",
    "Blazerip": "",
    "Ice Vortex": "",
    "The Restless Dead": "",
    "Pyrostatic Curse": "",
    "Spikeball Factory": "",
    "Mercurize": "",
    "Magnetize": "",
    "Silver Spear": "",
    "Siege Golems": "",
    "Lightning Spire": "",
    "Essence Flux": "",
    "Faehaunt Garden": "",
    "Furnace of Sorcery": "",
    "Golden Skull": "",
    "Wyrm Eggs": "",
    "Moon Glaive": "",
    "Carnival of Pain": "",
    "Dreamwalk": "",
    "Mass Calcification": "",
    "Scourge": "",
    "Immolate": "",
    "Armageddon Blade": "",
    "Bone Spear": "",
    "Lumbriogenesis": "",
    "Night Hag": "",
    "Blood Golem": "",
    "Lifedrain": "",
    "Ritual of Revelation": "",
    "Devour Flesh": "",
    "Bloodshift": "",
    "Flesh Fiend": "",
    "Gates of Helheim": "",
    "Horde of Halfmen": "",
    "Burning Idol": "",
    "Goatia Offering": "",
    "Drain Pulse": "",
    "Summon Wizard": "",
    "Psychic Seedling": "",
    "Soul Wind": "",
    "Stampede Form": "",
    "Hatebolts": "",
    "Bloodflame": "",
}

upgrades = {
    "Arch Enchanter": "",
    "Arch Sorcerer": "",
    "Arch Conjurer": "",
    "Fire Lord": "",
    "Ice Lord": "",
    "Thunder Lord": "",
    "Nature Lord": "",
    "Dark Lord": "",
    "Void Lord": "",
    "Light Lord": "",
    "Dragon Lord": "",
    "Orb Lord": "",
    "Metal Lord": "",
    "Unblinking Eye": "",
    "Translocation Master": "",
    "Pyrophilia": "",
    "Minion Regeneration": "",
    "Searing Heat": "",
    "Arcane Combustion": "",
    "Soul Harvest": "",
    "Arcane Accounting": "",
    "Natural Healing": "",
    "Glittering Dance": "",
    "Lightning Frenzy": "",
    "Melting Armor": "",
    "Natural Vigour": "",
    "Hungry Dead": "",
    "Lightning Warp": "",
    "Holy Thunder": "",
    "Fiery Judgement": "",
    "Starfire": "",
    "Shock Value": "",
    "Horror": "",
    "Arcane Shield": "",
    "Shielded Minions": "",
    "Ghostfire": "",
    "Wordspeaker": "",
    "Prince of Ruin": "",
    "Righteous March": "",
    "Chastisement": "",
    "Chaos Casting": "",
    "Unholy Alliance": "",
    "Thorn Garden": "",
    "Faestone": "",
    "Houndlord": "",
    "Hypocrisy": "",
    "Cracklevoid": "",
    "Bone Guard": "",
    "Spider Spawning": "",
    "Paralyzing Venom": "",
    "Venom Spit": "",
    "Icy Vengeance": "",
    "Ice Tap": "",
    "Frostbite": "",
    "Steam Anima": "",
    "Storm Caller": "",
    "Holy Water": "",
    "Hibernation": "",
    "Crystal Power": "",
    "Radiant Chill": "",
    "Shatter Shards": "",
    "Frozen Fragility": "",
    "Scalespinner": "",
    "Collected Agony": "",
    "Moonspeaker": "",
    "Void Spikes": "",
    "Necrostatics": "",
    "Purestrike": "",
    "Silkshifter": "",
    "Inferno Engines": "",
    "Megavenom": "",
    "Acid Fumes": "",
    "Voidflame Lantern": "",
    "Chaos Poet": "",
    "Master of Space": "",
    "Master of Time": "",
    "Master of Memories": "",
    "Spell Sniper": "",
    "Echomancer": "",
    "Disintegrator": "",
    "Fae Malevolence": "",
    "Blood Anima": "",
    "Blood Reaping": "",
    "Blood Lord": "",
    "Scent of Blood": "",
    "Stormbrood Tricksters": "",
    "Lifespark Lantern": "",
    "Scalefeather Egregore": "",
    "Toadblood Transmutation": "",
    "Chaos Familiar": "",
    "Deathchill Familiar": "",
    "Demonic Cruelty": "",
    "Enchanters Boon": "",
    "Hordemancer": "",
    "Conjured Vitality": "",
    "Conjured Aggression": "",
    "Serpents of Chaos": "",
    "Multimancy": "",
    "Armorer": "",
    "Hemocorruption": "",
    "Earthwrath": "",
}

consumables = {
    "Healing Potion": "",
    "Mana Potion": "",
    "Teleporter": "",
    "Golden Stopwatch": "",
    "Chaos Bell": "",
    "Death Dice": "",
    "Portal Key": "",
    "Earthquake Orb": "",
    "Oculus": "",
    "Aether Dagger": "",
    "Bag of Spikes": "",
    "Orb of Corruption": "",
}

equipments = {
    "The Bladestaff": "",
    "Geometer's Staff": "",
    "Memory Staff": "",
    "Banner of the Horde": "",
    "Storm Oculus": "",
    "Void Oculus": "",
    "Pyrostatic Oculus": "",
    "Twilight Oculus": "",
    "Crystal Oculus": "",
    "Purity Oculus": "",
    "Arcane Amplifier": "",
    "The Flamenweaver": "",
    "Treelord Staff": "",
    "Aetherlord Staff": "",
    "Filthlord Staff": "",
    "Flaming Claw Staff": "",
    "Icy Claw Staff": "",
    "Scepter of Mischief": "",
    "Drakenstaff": "",
    "The Purifier": "",
    "Silvermelt": "",
    "Sorcwinter": "",
    "The Dynamo": "",
    "The Blazeloom": "",
    "Starblesser": "",
    "The Sparkloom": "",
    "Wintersting": "",
    "Red Majesty": "",
    "Blastmaker": "",
    "Embermaker": "",
    "Mantismaker": "",
    "Sprigganmaker": "",
    "Impmaker": "",
    "Crackledarkener": "",
    "Scepter of Sorrows": "",
    "Glassy Fae Staff": "",
    "Quill Staff": "",
    "Robe of Ice": "",
    "Robe of Fire": "",
    "Robe of Void": "",
    "Robe of Storms": "",
    "Robe of the Druids": "",
    "Fae Plate": "",
    "Vampiric Vestments": "",
    "Dwarven Chainmail": "",
    "Elven Chainmail": "",
    "Soulmail": "",
    "Basilisk Scale Armor": "",
    "Earthtroll Armor": "",
    "Stormtroll Armor": "",
    "Robe of Twilight": "",
    "Robe of Agony": "",
    "Robe of Frostfire": "",
    "Robe of Crystals": "",
    "Marksman Cap": "",
    "Warlord Helm": "",
    "Spirit Visor": "",
    "Brain Hat": "",
    "Cannibal Mask": "",
    "Helm of the Host": "",
    "Icy Chill Mask": "",
    "Stone Mask": "",
    "Eye Helm": "",
    "Fire Helm": "",
    "Ice Helm": "",
    "Lightning Helm": "",
    "Dark Helm": "",
    "Nature Helm": "",
    "Holy Helm": "",
    "Arcane Helm": "",
    "Metallic Helm": "",
    "Fire Frenzy Mask": "",
    "Ice Frenzy Mask": "",
    "Arcane Frenzy Mask": "",
    "Summer Crown": "",
    "Winter Crown": "",
    "Spring Crown": "",
    "Autumn Crown": "",
    "Bloodspike Crown": "",
    "Earthmeld Boots": "",
    "Travellers Shoes": "",
    "Cantrip Clogs": "",
    "Timestriders": "",
    "Drill Shoes": "",
    "Winged Shoes": "",
    "Silken Sandals": "",
    "Snow Shoes": "",
    "Translocation Boots": "",
    "Gnome Shoes": "",
    "Slime Shoes": "",
    "Kobold Clogs": "",
    "Ogre Boots": "",
    "Ghost Slippers": "",
    "Storm Boots": "",
    "Exploding Boots": "",
    "Finger 6": "",
    "Ankh": "",
    "Drakentooth": "",
    "Eye Rock Pendant": "",
    "Amber Cube": "",
    "Skull Necklace": "",
    "Red Obsidian Shard": "",
    "Jade Shard": "",
    "Reality Anchor": "",
    "Amulet of Undeath": "",
    "Vial of Ambrosia": "",
    "Amulet of Emerald Flame": "",
    "Monkey Skull Amulet": "",
    "Blood Ruby": "",
    "Mystic Orb": "",
    "Enchanting Dagger": "",
    "Fiery Scale": "",
    "Poison Shield": "",
    "Lightning Shield": "",
    "Physical Shield": "",
    "Bramblethorn": "",
    "Toadthorn": "",
    "Devilthorn": "",
    "Witch Whistle": "",
    "Snowy Fursphere": "",
    "Living Emberstone": "",
    "Silken Links": "",
    "Winter Links": "",
    "Wrath Links": "",
    "Jar of Trollblood": "",
    "Jar of Embers": "",
    "Jar of Quicksilver": "",
    "Jar of Ectoplasm": "",
    "Poison Pipe": "",
    "Time Pipe": "",
    "Ink Pipe": "",
    "Ice Pipe": "",
    "Purple Curse Doll": "",
    "Ugly Curse Doll": "",
    "Red Curse Doll": "",
}
