spells = {
    "Fireball": "火球术",
    "Lightning Bolt": "闪电箭",
    "Annihilate": "歼灭",
    "Lightning Form": "闪电形态",
    "Mega Annihilate": "究极歼灭",
    "Teleport": "传送",
    "Blink": "闪烁",
    "Void Beam": "虚空射线",
    "Thunder Strike": "雷霆打击",
    "Chaos Barrage": "混沌弹幕", # 应该比混沌箭雨好听
    "Disperse": "驱散", # 放逐？下面还有一个驱散立场，放逐立场又很难听
    "Petrify": "石化",
    "Wolf": "狼", # anything better?
    "Giant Bear": "巨熊",
    "Sight of Blood": "血腥视野",
    "Lightning Storm": "闪电风暴",
    "Prison of Thorns": "荆棘监牢",
    "Pillar of Fire": "火焰之柱",
    "Boiling Blood": "沸腾血液",
    "Healing Light": "治疗之光",
    "Regeneration Aura": "再生光环",
    "Arcane Orb": "奥术法球",
    "Dominate": "支配",
    "Flame Gate": "火焰之门", # 太难听了
    "Eye of Fire": "火焰目光",
    "Eye of Lightning": "闪电目光",
    "Eye of Ice": "冰霜目光",
    "Nightmare Aura": "梦魇光环",
    "Basilisk Armor": "石化护甲",
    "Watcher Form": "观察者形态", # 我完全搞不懂这个技能的用途也不知道怎么翻译，不如说游戏里那个 Watcher 到底是什么生物
    "Imp Swarm": "小恶魔群", # 在 rw 里，fiend 就是 demon，imp 是小号 fiend，但是有的地方还是叫小鬼好听一点，纠结
    "Lightning Halo": "雷霆光轮", # 唉，被砍成圆环的技能
    "Mystic Vision": "神秘视野",
    "Mystic Power": "神秘力量",
    "Flame Burst": "炎爆术",
    "Fire Drake": "火焰巨龙",
    "Storm Drake": "风暴巨龙",
    "Void Drake": "虚空巨龙",
    "Ice Drake": "冰霜巨龙",
    "Chain Lightning": "连锁闪电",
    "Death Bolt": "死亡之箭", # 这玩意明显是 neta 魔兽争霸里的黑暗之箭，但是那个是 black arrow
    "Touch of Death": "死亡之触",
    "Seal Fate": "封禁命运", # anything better?
    "Wheel of Death": "死亡轮盘",
    "Volcanic Eruption": "火山爆发",
    "Underworld Passage": "冥界通道",
    "Earthen Sentinel": "大地哨兵",
    "Ghostball": "鬼球术",
    "Mystic Memory": "神秘记忆",
    "Permanence": "法术持久",
    "Vampiric Gaze": "吸血凝视",
    "Magic Missile": "魔法飞弹",
    "Devour Mind": "吞噬心灵",
    "Death Shock": "死亡震击",
    "Melt": "融化",
    "Dragon Roar": "龙吼",
    "Ironize": "铁化", # 太难听了
    "Word of Chaos": "混沌真言",
    "Word of Undeath": "不死真言", # 亡灵真言？
    "Word of Beauty": "美丽真言",
    "Floating Eye": "漂浮眼球",
    "Eye of Rage": "狂怒目光",
    "Arc Lightning": "弧形闪电",
    "Fan of Flames": "火焰扇",
    "Poison Sting": "毒刺",
    "Blue Lion": "蓝狮子",
    "Death Cleave": "死亡分裂", # 我还是有点想叫死亡顺劈
    "Multicast": "多重施法",
    "Fae Court": "妖精庭院",
    "Ring of Spiders": "蜘蛛之环",
    "Word of Madness": "疯狂真言",
    "Heavenly Blast": "天堂爆破",
    "Holy Fire": "圣火",
    "Choir of Angels": "天使唱诗班",
    "Heaven's Wrath": "天堂之怒",
    "Suspend Mortality": "延迟死亡",
    "Soul Tax": "灵魂税",
    "Holy Armor": "神圣护甲",
    "Blinding Light": "致盲之光",
    "Flock of Eagles": "鹰群",
    "Heavenly Idol": "天堂偶像",
    "Gold Drake": "黄金巨龙",
    "Call Seraph": "呼唤炽天使",
    "Call Archon": "呼唤执政官",
    "Pain Mirror": "痛苦之镜",
    "Pyrostatic Pulse": "电焰脉冲",
    "Aether Swap": "以太换位",
    "Siphon Shields": "虹吸护盾",
    "Hungry Maw": "饥饿之口", # anything better
    "Darkness": "黑暗术", # 很难听而且不表意
    "Plague of Undeath": "亡灵瘟疫", # 一代的空心肉体改名了
    "Cantrip Cascade": "小招倾泄",
    "Conductance": "导体化",
    "Invoke Savagery": "唤起野性",
    "Rain of Fire": "陨石雨",
    "Shrapnel Blast": "Shrapnel Blast", # 想不到
    "Plague of Filth": "污秽瘟疫",
    "Searing Orb": "灼热法球",
    "Ball Lightning": "球状闪电",
    "Orb Control": "控制法球",
    "Glass Orb": "玻璃法球",
    "Fiery Tormentor": "火热折磨者", # 拷问者？行刑者？这个的图像很自然让我想到魂3的狱卒和火刑魔女，拿着一个烙铁，这个形象来源于哪里呢
    "Petrification Aura": "石化光环",
    "Dispersion Field": "驱散立场",
    "Knightly Oath": "骑士誓言",
    "Toxin Burst": "毒素爆发",
    "Toxic Spores": "有毒孢子",
    "Combust Poison": "Combust Poison", # 想不到
    "Spider Queen": "蜘蛛女皇",
    "Freeze": "冻结",
    "Iceball": "冰球术",
    "Blizzard": "暴风雪",
    "Frostfire Hydra": "霜火九头蛇", # 作为海德拉你不能移动是正常的吗？
    "Storm Burst": "风暴爆发",
    "Death Chill": "致死严寒",
    "Ice Phoenix": "冰凤凰",
    "Word of Ice": "冰霜真言",
    "Ice Orb": "冰霜法球",
    "Icicle": "冰锥术",
    "Chill Wind": "寒风术", # 想不到好听又能和 soul wind 对称的
    "Wall of Ice": "冰墙", # 不管是冰墙还是冰墙术还是召唤冰墙都很难听
    "Bone Barrage": "骸骨弹幕",
    "Earthquake": "地震术",
    "Searing Seal": "灼热印记",
    "Soul Swap": "灵魂换位",
    "Purity": "净化术",
    "Twilight Gaze": "暮光凝视",
    "Slime Form": "史莱姆形态",
    "Blazerip": "熔火成刃", # 熔刃术？
    "Ice Vortex": "寒冰漩涡",
    "The Restless Dead": "不息死者",
    "Pyrostatic Curse": "电焰诅咒",
    "Spikeball Factory": "钉球工厂",
    "Mercurize": "水银化",
    "Magnetize": "磁化",
    "Silver Spear": "银色标枪", # 长了短了都不好听
    "Siege Golems": "攻城魔像",
    "Lightning Spire": "闪电尖塔",
    "Essence Flux": "精华流转", # 想不到
    "Faehaunt Garden": "蝴蝶花园", # 没法直译 
    "Furnace of Sorcery": "咒术熔炉",
    "Golden Skull": "金色颅骨",
    "Wyrm Eggs": "巨龙蛋", # 我觉得作者并没有搞清楚什么是 drake 什么是 wyrm，所以就都翻译成巨龙好了
    "Moon Glaive": "月光戟", # nonsense
    "Carnival of Pain": "痛楚祭典",
    "Dreamwalk": "梦游",
    "Mass Calcification": "群体钙化",
    "Scourge": "Scourge", # 为什么神圣法术会用这么难听的词
    "Immolate": "火祭",
    "Armageddon Blade": "审判之刃",
    "Bone Spear": "骨矛术",
    "Lumbriogenesis": "Lumbriogenesis", # 想不到
    "Night Hag": "老鬼婆", # DND
    "Blood Golem": "鲜血魔像",
    "Lifedrain": "生命吸取",
    "Ritual of Revelation": "启示仪式",
    "Devour Flesh": "吞噬血肉",
    "Bloodshift": "血液转移",
    "Flesh Fiend": "血肉恶魔",
    "Gates of Helheim": "冥界之门", # 所以 Aelf 到底是什么生物
    "Horde of Halfmen": "半人部族",
    "Burning Idol": "燃烧偶像",
    "Goatia Offering": "Goatia Offering", # 想不到
    "Drain Pulse": "吸取脉冲", # 很烂
    "Summon Wizard": "召唤巫师",
    "Psychic Seedling": "心灵之种",
    "Soul Wind": "魂风术", # 难听
    "Stampede Form": "Stampede Form", # 想不到
    "Hatebolts": "Hatebolts", # 想不到
    "Bloodflame": "血焰术", # 难听
}

skills = {
    "Arch Enchanter": "附魔大师",
    "Arch Sorcerer": "咒术大师",
    "Arch Conjurer": "召唤大师",
    "Fire Lord": "火焰领主",
    "Ice Lord": "冰霜领主",
    "Thunder Lord": "雷霆领主",
    "Nature Lord": "自然领主",
    "Dark Lord": "黑暗领主",
    "Void Lord": "虚空领主",
    "Light Lord": "光明领主",
    "Dragon Lord": "巨龙领主",
    "Orb Lord": "法球领主",
    "Metal Lord": "金属领主",
    "Unblinking Eye": "不眨眼",
    "Translocation Master": "传送大师",
    "Pyrophilia": "嗜火症",
    "Minion Regeneration": "随从再生",
    "Searing Heat": "灼烫热力", # anything better?
    "Arcane Combustion": "奥术爆燃",
    "Soul Harvest": "灵魂收割",
    "Arcane Accounting": "奥术会计", # 难听
    "Natural Healing": "自然回复",
    "Glittering Dance": "闪光之舞",
    "Lightning Frenzy": "雷霆狂热",
    "Melting Armor": "熔化护甲",
    "Natural Vigour": "自然护甲", # vigour 不是护甲的意思，whatever
    "Hungry Dead": "饥饿死者",
    "Lightning Warp": "闪电传送",
    "Holy Thunder": "神圣之雷",
    "Fiery Judgement": "火焰审判",
    "Starfire": "星火",
    "Shock Value": "Shock Value", # 敌人死于雷电伤害使视线内敌人狂暴
    "Horror": "恐惧",
    "Arcane Shield": "奥术护盾",
    "Shielded Minions": "Shielded Minions",
    "Ghostfire": "鬼火",
    "Wordspeaker": "Wordspeaker",
    "Prince of Ruin": "毁灭王子", # 我还是想叫废墟王子
    "Righteous March": "正义行军", # 好难听
    "Chastisement": "惩戒", # 这个图标和 Scourge 一样啊，那都叫惩戒行吗（不行
    "Chaos Casting": "混乱施法",
    "Unholy Alliance": "不洁同盟",
    "Thorn Garden": "荆棘花园",
    "Faestone": "仙灵石",
    "Houndlord": "猎犬领主",
    "Hypocrisy": "伪善",
    "Cracklevoid": "Cracklevoid", # 想不到
    "Bone Guard": "骸骨卫士",
    "Spider Spawning": "蜘蛛孵化", # 难听
    "Paralyzing Venom": "麻痹毒液",
    "Venom Spit": "毒液喷射",
    "Icy Vengeance": "冰霜复仇",
    "Ice Tap": "Ice Tap", # 想不到
    "Frostbite": "霜咬", # 图里有张嘴
    "Steam Anima": "蒸汽元素",
    "Storm Caller": "呼唤风暴",
    "Holy Water": "圣水",
    "Hibernation": "冬眠",
    "Crystal Power": "水晶之力",
    "Radiant Chill": "寒冷光芒",
    "Shatter Shards": "破冰裂片",
    "Frozen Fragility": "Frozen Fragility", # 想不到
    "Scalespinner": "鳞甲变换",
    "Collected Agony": "聚集苦痛",
    "Moonspeaker": "月语者",
    "Void Spikes": "虚空尖刺", # 怎么体现这是一个反伤技能
    "Necrostatics": "Necrostatics", # 我恨透了合成词
    "Purestrike": "纯洁打击",
    "Silkshifter": "蛛网行者",
    "Inferno Engines": "地狱引擎",
    "Megavenom": "剧毒",
    "Acid Fumes": "酸雾",
    "Voidflame Lantern": "Voidflame Lantern", # 我恨透了合成词2
    "Chaos Poet": "混沌诗人",
    "Master of Space": "空间大师",
    "Master of Time": "时间大师",
    "Master of Memories": "记忆大师",
    "Spell Sniper": "法术狙击手",
    "Echomancer": "回响施法",
    "Disintegrator": "解离", # 不能叫解离术，怎么办
    "Fae Malevolence": "妖精恶意",
    "Blood Anima": "鲜血幽魂", # 这里不能叫血元素了，难道叫血幽魂吗，anima 到底怎么翻译
    "Blood Reaping": "鲜血收割",
    "Blood Lord": "鲜血领主",
    "Scent of Blood": "血之气息", # 这名字和猎犬有什么关系了到底
    "Stormbrood Tricksters": "Stormbrood Tricksters", # trickster 到底体现在哪里了，这召唤出来的不就是普通的风暴巨魔吗
    "Lifespark Lantern": "Lifespark Lantern", # 我恨透了合成词3
    "Scalefeather Egregore": "鳞甲", # 这他妈是啥
    "Toadblood Transmutation": "Toadblood Transmutation", # 想不到
    "Chaos Familiar": "混乱仆从",
    "Deathchill Familiar": "死寒仆从",
    "Demonic Cruelty": "恶魔残忍",
    "Enchanters Boon": "恩惠附魔", # 烂
    "Hordemancer": "部族召唤者",
    "Conjured Vitality": "活力随从",
    "Conjured Aggression": "侵袭随从",
    "Serpents of Chaos": "混沌之蛇",
    "Multimancy": "多重施法",
    "Armorer": "盔甲匠",
    "Hemocorruption": "污染血液",
    "Earthwrath": "大地之怒",
}

upgrades = {
  
}

consumables = {
    "Healing Potion": "治疗药水",
    "Mana Potion": "法力药水",
    "Teleporter": "传送器",
    "Golden Stopwatch": "金质怀表",
    "Chaos Bell": "混乱之铃",
    "Death Dice": "死亡骰子",
    "Portal Key": "传送钥匙",
    "Earthquake Orb": "地震法球",
    "Oculus": "天眼",
    "Aether Dagger": "以太匕首",
    "Bag of Spikes": "钉球袋",
    "Orb of Corruption": "腐化法球",
}

equipments = {
    "The Bladestaff": "利刃法杖",
    "Geometer's Staff": "制图师法杖",
    "Memory Staff": "记忆法杖",
    "Banner of the Horde": "部族旗帜",
    "Storm Oculus": "Storm Oculus",
    "Void Oculus": "Void Oculus",
    "Pyrostatic Oculus": "Pyrostatic Oculus",
    "Twilight Oculus": "Twilight Oculus",
    "Crystal Oculus": "Crystal Oculus",
    "Purity Oculus": "Purity Oculus",
    "Arcane Amplifier": "Arcane Amplifier",
    "The Flamenweaver": "The Flamenweaver",
    "Treelord Staff": "Treelord Staff",
    "Aetherlord Staff": "Aetherlord Staff",
    "Filthlord Staff": "Filthlord Staff",
    "Flaming Claw Staff": "Flaming Claw Staff",
    "Icy Claw Staff": "Icy Claw Staff",
    "Scepter of Mischief": "Scepter of Mischief",
    "Drakenstaff": "Drakenstaff",
    "The Purifier": "The Purifier",
    "Silvermelt": "Silvermelt",
    "Sorcwinter": "Sorcwinter",
    "The Dynamo": "The Dynamo",
    "The Blazeloom": "The Blazeloom",
    "Starblesser": "Starblesser",
    "The Sparkloom": "The Sparkloom",
    "Wintersting": "Wintersting",
    "Red Majesty": "Red Majesty",
    "Blastmaker": "Blastmaker",
    "Embermaker": "Embermaker",
    "Mantismaker": "Mantismaker",
    "Sprigganmaker": "Sprigganmaker",
    "Impmaker": "Impmaker",
    "Crackledarkener": "Crackledarkener",
    "Scepter of Sorrows": "Scepter of Sorrows",
    "Glassy Fae Staff": "Glassy Fae Staff",
    "Quill Staff": "Quill Staff",
    "Robe of Ice": "Robe of Ice",
    "Robe of Fire": "Robe of Fire",
    "Robe of Void": "Robe of Void",
    "Robe of Storms": "Robe of Storms",
    "Robe of the Druids": "Robe of the Druids",
    "Fae Plate": "Fae Plate",
    "Vampiric Vestments": "Vampiric Vestments",
    "Dwarven Chainmail": "Dwarven Chainmail",
    "Elven Chainmail": "Elven Chainmail",
    "Soulmail": "Soulmail",
    "Basilisk Scale Armor": "Basilisk Scale Armor",
    "Earthtroll Armor": "Earthtroll Armor",
    "Stormtroll Armor": "Stormtroll Armor",
    "Robe of Twilight": "Robe of Twilight",
    "Robe of Agony": "Robe of Agony",
    "Robe of Frostfire": "Robe of Frostfire",
    "Robe of Crystals": "Robe of Crystals",
    "Marksman Cap": "Marksman Cap",
    "Warlord Helm": "Warlord Helm",
    "Spirit Visor": "Spirit Visor",
    "Brain Hat": "Brain Hat",
    "Cannibal Mask": "Cannibal Mask",
    "Helm of the Host": "Helm of the Host",
    "Icy Chill Mask": "Icy Chill Mask",
    "Stone Mask": "Stone Mask",
    "Eye Helm": "Eye Helm",
    "Fire Helm": "Fire Helm",
    "Ice Helm": "Ice Helm",
    "Lightning Helm": "Lightning Helm",
    "Dark Helm": "Dark Helm",
    "Nature Helm": "Nature Helm",
    "Holy Helm": "Holy Helm",
    "Arcane Helm": "Arcane Helm",
    "Metallic Helm": "Metallic Helm",
    "Fire Frenzy Mask": "Fire Frenzy Mask",
    "Ice Frenzy Mask": "Ice Frenzy Mask",
    "Arcane Frenzy Mask": "Arcane Frenzy Mask",
    "Summer Crown": "夏季皇冠",
    "Winter Crown": "冬季皇冠",
    "Spring Crown": "春季皇冠",
    "Autumn Crown": "秋季皇冠",
    "Bloodspike Crown": "Bloodspike Crown",
    "Earthmeld Boots": "Earthmeld Boots",
    "Travellers Shoes": "Travellers Shoes",
    "Cantrip Clogs": "Cantrip Clogs",
    "Timestriders": "Timestriders",
    "Drill Shoes": "Drill Shoes",
    "Winged Shoes": "Winged Shoes",
    "Silken Sandals": "Silken Sandals",
    "Snow Shoes": "Snow Shoes",
    "Translocation Boots": "Translocation Boots",
    "Gnome Shoes": "Gnome Shoes",
    "Slime Shoes": "Slime Shoes",
    "Kobold Clogs": "Kobold Clogs",
    "Ogre Boots": "Ogre Boots",
    "Ghost Slippers": "Ghost Slippers",
    "Storm Boots": "Storm Boots",
    "Exploding Boots": "Exploding Boots",
    "Finger 6": "Finger 6",
    "Ankh": "Ankh",
    "Drakentooth": "Drakentooth",
    "Eye Rock Pendant": "Eye Rock Pendant",
    "Amber Cube": "Amber Cube",
    "Skull Necklace": "Skull Necklace",
    "Red Obsidian Shard": "Red Obsidian Shard",
    "Jade Shard": "Jade Shard",
    "Reality Anchor": "Reality Anchor",
    "Amulet of Undeath": "Amulet of Undeath",
    "Vial of Ambrosia": "Vial of Ambrosia",
    "Amulet of Emerald Flame": "Amulet of Emerald Flame",
    "Monkey Skull Amulet": "Monkey Skull Amulet",
    "Blood Ruby": "Blood Ruby",
    "Mystic Orb": "Mystic Orb",
    "Enchanting Dagger": "Enchanting Dagger",
    "Fiery Scale": "Fiery Scale",
    "Poison Shield": "Poison Shield",
    "Lightning Shield": "Lightning Shield",
    "Physical Shield": "Physical Shield",
    "Bramblethorn": "Bramblethorn",
    "Toadthorn": "Toadthorn",
    "Devilthorn": "Devilthorn",
    "Witch Whistle": "Witch Whistle",
    "Snowy Fursphere": "Snowy Fursphere",
    "Living Emberstone": "Living Emberstone",
    "Silken Links": "Silken Links",
    "Winter Links": "Winter Links",
    "Wrath Links": "Wrath Links",
    "Jar of Trollblood": "巨魔血坛子",
    "Jar of Embers": "余烬坛子",
    "Jar of Quicksilver": "水银坛子",
    "Jar of Ectoplasm": "灵质坛子",
    "Poison Pipe": "有毒吹箭",
    "Time Pipe": "时间吹箭",
    "Ink Pipe": "墨水吹箭",
    "Ice Pipe": "冰霜吹箭",
    "Purple Curse Doll": "Purple Curse Doll",
    "Ugly Curse Doll": "Ugly Curse Doll",
    "Red Curse Doll": "Red Curse Doll",
}
