spells = {
    "Fireball": "火球术",
    "Lightning Bolt": "闪电箭",
    "Annihilate": "湮灭术",
    "Lightning Form": "闪电形态",
    "Mega Annihilate": "究极湮灭术",
    "Teleport": "传送术",
    "Blink": "闪现术",
    "Void Beam": "虚空射线",
    "Thunder Strike": "雷击术",
    "Chaos Barrage": "混沌箭雨",
    "Disperse": "驱散术",
    "Petrify": "石化术",
    "Wolf": "招狼术",
    "Giant Bear": "巨熊",
    "Sight of Blood": "鲜血视线",
    "Lightning Storm": "闪电风暴",
    "Prison of Thorns": "荆棘囚笼",
    "Pillar of Fire": "火焰之柱",
    "Boiling Blood": "沸腾之血",
    "Healing Light": "治愈之光",
    "Regeneration Aura": "再生光环",
    "Arcane Orb": "奥术法球",
    "Dominate": "支配术",
    "Flame Gate": "火门术",
    "Eye of Fire": "火焰之眼",
    "Eye of Lightning": "闪电之眼",
    "Eye of Ice": "寒冰之眼",
    "Nightmare Aura": "梦魇光环",
    "Basilisk Armor": "蜥怪盔甲",
    "Watcher Form": "守卫形态",
    "Imp Swarm": "小恶魔群",
    "Lightning Halo": "闪电光环",
    "Mystic Vision": "神秘视野",
    "Mystic Power": "神秘力量",
    "Flame Burst": "炎爆术",
    "Fire Drake": "火焰巨龙",
    "Storm Drake": "风暴巨龙",
    "Void Drake": "虚空巨龙",
    "Ice Drake": "寒冰巨龙",
    "Chain Lightning": "连锁闪电",
    "Death Bolt": "死亡之箭",
    "Touch of Death": "死亡之触",
    "Seal Fate": "命定之死",
    "Wheel of Death": "死亡轮盘",
    "Volcanic Eruption": "火山爆发",
    "Underworld Passage": "冥界通道",
    "Earthen Sentinel": "大地哨兵",
    "Ghostball": "鬼球术",
    "Mystic Memory": "神秘记忆",
    "Permanence": "法术持久",
    "Vampiric Gaze": "吸血凝视",
    "Magic Missile": "魔法飞弹",
    "Devour Mind": "吞噬心灵",
    "Death Shock": "死亡电击",
    "Melt": "熔化术",
    "Dragon Roar": "龙吼",
    "Ironize": "铸铁身躯", # 太难听了
    "Word of Chaos": "混沌真言",
    "Word of Undeath": "不死真言", # 亡灵真言？
    "Word of Beauty": "美德真言",
    "Floating Eye": "漂浮眼球",
    "Eye of Rage": "狂怒之眼",
    "Arc Lightning": "弧形闪电",
    "Fan of Flames": "扇状烈焰",
    "Poison Sting": "毒刺术",
    "Blue Lion": "靛蓝巨狮",
    "Death Cleave": "死亡分裂", # 我还是有点想叫死亡顺劈
    "Multicast": "多重施法",
    "Fae Court": "妖精庭院",
    "Ring of Spiders": "蜘蛛之环",
    "Word of Madness": "疯狂真言",
    "Heavenly Blast": "天堂爆破",
    "Holy Fire": "圣火术",
    "Choir of Angels": "天使唱诗班",
    "Heaven's Wrath": "天堂之怒",
    "Suspend Mortality": "死亡拒止",
    "Soul Tax": "灵魂税",
    "Holy Armor": "神圣护甲",
    "Blinding Light": "眩目之光",
    "Flock of Eagles": "召唤鹰群",
    "Heavenly Idol": "天堂造像",
    "Gold Drake": "黄金巨龙",
    "Call Seraph": "呼唤炽天使",
    "Call Archon": "呼唤执政官",
    "Pain Mirror": "痛苦之镜",
    "Pyrostatic Pulse": "电焰脉冲",
    "Aether Swap": "以太换位",
    "Siphon Shields": "虹吸护盾",
    "Hungry Maw": "饥饿嗜魔", # dnd 
    "Darkness": "黑暗术", # dnd二环塑能
    "Plague of Undeath": "亡灵瘟疫", #亡灵天灾（（
    "Cantrip Cascade": "小招倾泻",
    "Conductance": "导体化",
    "Invoke Savagery": "唤起野性",
    "Rain of Fire": "陨石雨",
    "Shrapnel Blast": "破片迸发",
    "Plague of Filth": "污秽瘟疫",
    "Searing Orb": "灼热法球",
    "Ball Lightning": "球状闪电",
    "Orb Control": "法球控制",
    "Glass Orb": "玻璃法球",
    "Fiery Tormentor": "炽火狱吏", # 拷问者？行刑者？这个的图像很自然让我想到魂3的狱卒和火刑魔女，拿着一个烙铁，这个形象来源于哪里呢
    "Petrification Aura": "石化光环",
    "Dispersion Field": "驱散立场",
    "Knightly Oath": "骑士誓言",
    "Toxin Burst": "毒素爆发",
    "Toxic Spores": "有毒孢子",
    "Combust Poison": "燃毒术", # 想不到
    "Spider Queen": "蜘蛛女皇",
    "Freeze": "冰冻术",
    "Iceball": "冰球术",
    "Blizzard": "暴风雪",
    "Frostfire Hydra": "霜火九头蛇", # 作为海德拉你不能移动是正常的吗？
    "Storm Burst": "风暴爆发",
    "Death Chill": "致死严寒",
    "Ice Phoenix": "寒冰凤凰",
    "Word of Ice": "冰霜真言",
    "Ice Orb": "冰霜法球",
    "Icicle": "冰锥术",
    "Chill Wind": "凛冽寒风", 
    "Wall of Ice": "寒冰之墙", # 不管是冰墙还是冰墙术还是召唤冰墙都很难听
    "Bone Barrage": "骸骨弹幕",
    "Earthquake": "地震术",
    "Searing Seal": "灼热印记",
    "Soul Swap": "灵魂换位",
    "Purity": "净化术",
    "Twilight Gaze": "暮光凝视",
    "Slime Form": "史莱姆形态",
    "Blazerip": "炽裂术", # 熔刃术？
    "Ice Vortex": "寒冰漩涡",
    "The Restless Dead": "不息死者",
    "Pyrostatic Curse": "电焰诅咒",
    "Spikeball Factory": "钉球工厂",
    "Mercurize": "汞化术",
    "Magnetize": "磁化术",
    "Silver Spear": "银色标枪", # 长了短了都不好听
    "Siege Golems": "攻城魔像",
    "Lightning Spire": "闪电尖塔",
    "Essence Flux": "要素异变", # 
    "Faehaunt Garden": "蝴蝶花园", # 没法直译 
    "Furnace of Sorcery": "咒术熔炉",
    "Golden Skull": "金色颅骨",
    "Wyrm Eggs": "巨龙蛋", # 我觉得作者并没有搞清楚什么是 drake 什么是 wyrm，所以就都翻译成巨龙好了
    "Moon Glaive": "月刃", 
    "Carnival of Pain": "痛楚祭典",
    "Dreamwalk": "白日梦行",
    "Mass Calcification": "群体钙化",
    "Scourge": "鞭笞术", 
    "Immolate": "燔祭",
    "Armageddon Blade": "审判之刃",
    "Bone Spear": "骨矛术",
    "Lumbriogenesis": "Lumbriogenesis", # 想不到
    "Night Hag": "老鬼婆", # DND
    "Blood Golem": "鲜血魔像",
    "Lifedrain": "生命吸取",
    "Ritual of Revelation": "启示仪式",
    "Devour Flesh": "吞噬血肉",
    "Bloodshift": "鲜血转移",
    "Flesh Fiend": "血肉恶魔",
    "Gates of Helheim": "赫尔海姆之门", # 所以 Aelf 到底是什么生物
    "Horde of Halfmen": "部落出击",
    "Burning Idol": "焚烬造像",
    "Goatia Offering": "邪羊献祭",
    "Drain Pulse": "衰竭脉冲", 
    "Summon Wizard": "召唤巫师",
    "Psychic Seedling": "灵能幼苗",
    "Soul Wind": "灵魂之风",
    "Stampede Form": "象群形态",
    "Hatebolts": "恶业之箭", # 想不到
    "Bloodflame": "血焰术", # 难听
}

skills = {
    "Arch Enchanter": "附魔大师",
    "Arch Sorcerer": "咒术大师",
    "Arch Conjurer": "召唤大师",
    "Fire Lord": "火焰领主",
    "Ice Lord": "冰霜领主",
    "Thunder Lord": "雷霆领主",
    "Nature Lord": "自然领主",
    "Dark Lord": "黑暗领主",
    "Void Lord": "虚空领主",
    "Light Lord": "光明领主",
    "Dragon Lord": "巨龙领主",
    "Orb Lord": "法球领主",
    "Metal Lord": "金属领主",
    "Unblinking Eye": "不瞬之目",
    "Translocation Master": "传送大师",
    "Pyrophilia": "嗜火症",
    "Minion Regeneration": "随从再生",
    "Searing Heat": "炎炎酷热", 
    "Arcane Combustion": "奥术爆燃",
    "Soul Harvest": "灵魂收割",
    "Arcane Accounting": "奥术节能",  
    "Natural Healing": "自然回复",
    "Glittering Dance": "闪光之舞",
    "Lightning Frenzy": "闪电狂热",
    "Melting Armor": "熔化护甲",
    "Natural Vigour": "自然之力",# ?
    "Hungry Dead": "饥饿死者",
    "Lightning Warp": "闪电跃迁",
    "Holy Thunder": "神圣雷霆",
    "Fiery Judgement": "火焰审判",
    "Starfire": "星火交辉",
    "Shock Value": "震魂夺魄", # 敌人死于雷电伤害使视线内敌人狂暴
    "Horror": "恐惧",
    "Arcane Shield": "奥术护盾",
    "Shielded Minions": "盾护随从",
    "Ghostfire": "鬼火",
    "Wordspeaker": "真言行者",
    "Prince of Ruin": "毁灭王子", # 我还是想叫废墟王子
    "Righteous March": "正义之师", # 好难听
    "Chastisement": "惩戒", # 这个图标和 Scourge 一样啊，那都叫惩戒行吗（不行
    "Chaos Casting": "混乱施法",
    "Unholy Alliance": "不洁同盟",
    "Thorn Garden": "荆棘花园",
    "Faestone": "仙灵石",
    "Houndlord": "猎犬领主",
    "Hypocrisy": "伪善",
    "Cracklevoid": "虚空电鸣", 
    "Bone Guard": "骸骨卫士",
    "Spider Spawning": "蜘蛛孳生", 
    "Paralyzing Venom": "麻痹毒液",
    "Venom Spit": "毒液喷射",
    "Icy Vengeance": "冰霜复仇",
    "Ice Tap": "共振冰棱", # 不挨着就对了（？ 
    "Frostbite": "霜咬", # 图里有张嘴
    "Steam Anima": "蒸汽灵体",
    "Storm Caller": "呼唤风暴",
    "Holy Water": "圣水",
    "Hibernation": "冬眠",
    "Crystal Power": "水晶之力",
    "Radiant Chill": "寒冷光芒",
    "Shatter Shards": "碎冰裂片",
    "Frozen Fragility": "低温脆化", 
    "Scalespinner": "鳞甲变换",
    "Collected Agony": "苦痛积聚",
    "Moonspeaker": "月语者",
    "Void Spikes": "虚空棘刺", 
    "Necrostatics": "亡灵起电",
    "Purestrike": "纯洁打击",
    "Silkshifter": "蛛网行者",
    "Inferno Engines": "炼狱引擎",
    "Megavenom": "剧毒",
    "Acid Fumes": "酸雾",
    "Voidflame Lantern": "虚空火灯", 
    "Chaos Poet": "混沌诗人",
    "Master of Space": "空间大师",
    "Master of Time": "时间大师",
    "Master of Memories": "记忆大师",
    "Spell Sniper": "法术狙击",
    "Echomancer": "法术回响",
    "Disintegrator": "解离者",
    "Fae Malevolence": "仙灵诅咒", # TODO
    "Blood Anima": "鲜血灵体", 
    "Blood Reaping": "鲜血收割",
    "Blood Lord": "鲜血领主",
    "Scent of Blood": "血腥嗅迹", 
    "Stormbrood Tricksters": "风巢诡魔", # 召唤出来的巨魔会闪现术
    "Lifespark Lantern": "生灵弧灯", # 呃 电弧灯
    "Scalefeather Egregore": "鳞羽群灵", # 鳞羽格式塔（？
    "Toadblood Transmutation": "蟾血嬗变", # 想不到
    "Chaos Familiar": "混乱仆从",
    "Deathchill Familiar": "死寒仆从",
    "Demonic Cruelty": "魔之恶毒",
    "Enchanters Boon": "附魔恩赐", 
    "Hordemancer": "群体召唤",
    "Conjured Vitality": "造物活力",
    "Conjured Aggression": "造物强袭",
    "Serpents of Chaos": "混沌之蛇",
    "Multimancy": "分心施法",
    "Armorer": "盔甲构装",
    "Hemocorruption": "血之腐化",
    "Earthwrath": "大地之怒",
}

upgrades = {
    "Chaos Ball": "混沌球",
    "Ash Ball": "灰烬球",
    "Meteor": "火流星",
    "Channeling": "引导施法",
    "Electric Ink": "电能复写",
    "Energy Bolt": "能量箭",
    "Cascade": "倾泻湮灭",
    "Comprehensive Annihilation": "全面湮灭",
    "Doom Storm": "毁灭风暴",
    "Lingering Form": "残影形态",
    "Fire Form": "火焰形态",
    "Crackling Aura": "电鸣光环",
    "Cascade": "倾泻湮灭",
    "Dark Annihilation": "黑暗湮灭",
    "Arcane Annihilation": "奥术湮灭",
    "Quickcast": "法术瞬发",
    "Group Teleport": "群体传送",
    "Void Teleport": "虚空传送",
    "Blindcasting": "无需视线",
    "Dissolution": "分散闪现",
    "Thunderblink": "雷霆闪现",
    "Void Binding": "虚空燔祭",
    "Star Beam": "星火射线",
    "Voidcurse": "虚空诅咒",
    "Blindcasting": "无需视线",
    "Storm Power": "风暴蓄能",
    "Heaven Strike": "天堂雷击",
    "Mega Barrage": "超级弹幕",
    "Shockwaves": "冲击波",
    "Smart Bolts": "智能射弹",
    "Violent Warp": "暴力跃迁",
    "Protective Warp": "防护跃迁",
    "Glassify": "玻璃化",
    "Arcane Conductivity": "奥术传导",
    "Rocky Servitude": "岩石奴役",
    "Wolf Pack": "群狼术",
    "Ice Hound": "寒冰猎犬",
    "Clay Hound": "黏土猎犬",
    "Metal Bear": "金属巨熊",
    "Venom Bear": "毒液巨熊",
    "Blood Bear": "鲜血巨熊",
    "Duration": "持续回合",
    "Demon Frenzy": "恶魔狂热",
    "Blindcasting": "无需视线",
    "Particle Storm": "粒子风暴",
    "Lightning Star": "闪电连星",
    "Spirit Harvest": "灵体收割",
    "Minion Damage": "随从伤害",
    "Minion Health": "随从生命",
    "Iron Prison": "钢铁囚笼",
    "Icy Prison": "寒冰囚笼",
    "Channeling": "引导施法",
    "Disrupting Flames": "干扰烈焰",
    "Pillar of Annihilation": "湮灭之柱",
    "Extra Damage": "额外伤害",
    "Duration": "持续回合",
    "Holy Fury": "神圣怒火",
    "Dark Fury": "黑暗怒火",
    "Shielding Light": "护卫之光",
    "Purifying Light": "净化之光",
    "Heartflame": "心灵之火",
    "Heal": "治疗量",
    "Duration": "持续回合",
    "Global": "全图治疗",
    "Blazerip Orb": "炽裂法球",
    "Double Shot": "双重射击",
    "Orb Detonation": "法球激发",
    "HP Threshold": "血量阈值",
    "Brute Force": "蛮力",
    "Undead Servitude": "不死奴役",
    "Burst Fire": "火焰爆发",
    "Eye Gate": "火瞳之门",
    "Starfire Gate": "星火之门",
    "Eye of Fireballs": "火球之眼",
    "Fiery Onlooker": "火焰观者",
    "Eye of Conflaguration": "燎原之眼",
    "Archon Eye": "执政官之眼",
    "Eye of Thunderstrike": "雷击之眼",
    "Penetrating Gaze": "穿透凝视",
    "Frosty Onlooker": "寒霜观者",
    "Eye of Freezing": "冻寒之眼",
    "Eye of Iceballs": "冰球之眼",
    "Dark Dream": "黑暗梦境",
    "Electric Dream": "电气梦境",
    "Fever Dream": "狂热梦境",
    "Max Charges": "充能上线",
    "Duration": "持续回合",
    "Pyrostatic Watcher Form": "电焰守卫",
    "Void Watcher Form": "虚空守卫",
    "Chain Watcher Form": "连锁守卫",
    "Metal Swarm": "金属魔潮",
    "Dark Swarm": "黑暗魔潮",
    "Endless Swarm": "无尽魔潮",
    "Ring of Fire": "火焰之环",
    "Radioactive Field": "辐射场",
    "Lightning Nova": "闪电新星",
    "Duration": "持续回合",
    "Bonus": "增益",
    "Vision Aura": "视野光环",
    "Duration": "持续回合",
    "Damage Bonus": "伤害增益",
    "Intensity": "强度",
    "Melting Flame": "熔融烈焰",
    "Bright Flame": "明亮烈焰",
    "Spreading Flame": "烈焰扩散",
    "Broodlings": "幼体增殖",
    "Metal Dragon": "金属巨龙",
    "Dragon Mage": "巨龙法师",
    "Storm Summoning": "风暴召唤",
    "Ghost Drake": "幽灵巨龙",
    "Drake Swap": "巨龙换位",
    "Dragon Mage": "巨龙法师",
    "Shields": "护盾",
    "Dragon Mage": "巨龙法师",
    "Essence Drake": "本源巨龙",
    "Dracolich": "龙巫妖",
    "Broodlings": "幼体增殖",
    "Dragon Mage": "巨龙法师",
    "Chain Fireball": "连锁火球",
    "Cloud Conductance": "云层导电",
    "Lightning Shield": "闪电护盾",
    "Soul Battery": "灵魂充能",
    "Winter Bolt": "凛冬箭",
    "Chaos Skeletons": "混沌骷髅",
    "Flametouch": "火焰之触",
    "Touch of the Vampire": "吸血之触",
    "Touch of the Reaper": "死神之触",
    "Hand of Death": "死亡之手",
    "Blindcasting": "无需视线",
    "Spreading Curse": "散播诅咒",
    "Genocide": "灭绝术",
    "Max Charges": "充能上限",
    "Cheat Fate": "瞒天过海",
    "Flow Range": "喷发范围",
    "Blindcasting": "无需视线",
    "Wallcano": "墙体喷发",
    "Quickcast": "法术瞬发",
    "Tremorsensitivity": "震动感应",
    "Earthquake Totem": "地震图腾",
    "Stinging Totem": "毒刺图腾",
    "Holy Totem": "神圣图腾",
    "Radius": "半径",
    "Ghost King": "游魂之王",
    "Ghost Mass": "百鬼夜行",
    "Distant Memory": "久远回忆",
    "Deep Reflection": "深度回想",
    "Shield of Memories": "记忆护盾",
    "Duration": "持续回合",
    "Toxic Gaze": "毒性凝视",
    "Vampiric Tax": "吸血税",
    "Refracting Gaze": "目光折射",
    "Shield Burn": "护盾烧却",
    "Disruption Bolt": "干扰飞弹",
    "Arcane Crossfire": "奥术交火",
    "Ricochet": "弹射飞弹",
    "Huskification": "尸壳化",
    "Spirit Eater": "吞噬灵体",
    "Gluttony": "暴食",
    "Fire Shock": "火焰电击",
    "Shield Burn": "护盾烧却",
    "Corpse Construct": "尸体重组",
    "Mass Melt": "群体熔化",
    "Ice Penetration": "熔透寒冰",
    "White Flame": "白色火焰",
    "Draconic Vitality": "巨龙生机",
    "Draconic Vigor": "巨龙活力",
    "Draconic Majesty": "巨龙威严",
    "Armor Plating": "装甲镀层",
    "Permanent Transmutation": "永续",
    "Arcane Insulation": "奥术绝缘",
    "Animated Chaos": "诱导降临",
    "Chaos Gifts": "混沌恩赐",
    "Echoing Chaos": "混沌回响",
    "Hatred of Life": "亡者之憎",
    "Spirit Gift": "幽灵馈赠",
    "Spirit of Lichdom": "巫魂涌现",
    "Beauty of Steel": "钢之美德",
    "Shield Strip": "护盾剥离",
    "Echoing Beauty": "美德回响",
    "Stone Gaze": "石化魔眼",
    "Eyemage": "拟态魔眼",
    "Regenerating Shields": "护盾再生",
    "Lycanthropy": "狼人疫病",
    "Infectious Rage": "集群感染",
    "Burning Rage": "怒火中烧",
    "Proton Storm": "质子风暴",
    "Enervation": "精妙施法",
    "Multi Flash": "多重火花",
    "Healing Hearthfire": "治愈之炎",
    "Fan of Frostfire": "霜火技艺",
    "Wildfire": "野火燎原",
    "Acidity": "剧毒入髓",
    "Silk Shot": "蛛丝射击",
    "Stinger Barrage": "毒素爆发",
    "Holy Bolt": "神圣之箭",
    "Shimmermane": "微光",
    "Burning Lion": "烈焰亚种",
    "Duration": "持续回合",
    "Max Charges": "充能上限",
    "Copies": "Copies",
    "Duration": "持续回合",
    "Max Charges": "充能上限",
    "Winter Faery": "冬之精灵",
    "Summon Queen": "召唤女皇",
    "Glass Faery": "玻璃精灵",
    "Turbo Toxin": "毒网",
    "Long Webs": "巨网",
    "Aether Spiders": "以太族群", 
    "Selective Madness": "精妙吟唱",
    "Echoing Madness": "妄语回响",
    "Guardians of Madness": "疯诞降临",
    "Spirit Bind": "圣罚魂缚",
    "Shield": "护盾",
    "Echo Heal": "圣愈共鸣",
    "Holy Smite": "神怒一击",
    "Divine Blaze": "神性炽裂",
    "Heaven Call": "天堂号令",
    "Dual Angels": "战斗天使",
    "Mercy": "圣光感化",
    "Massive Chorus": "天堂诗班",
    "Culling": "抹除打击",
    "Halt Heretics": "打断邪术",
    "Fiery Wrath": "圣光烈焰",
    "Endlessness": "绵延不绝",
    "Mass Immortaity": "不朽之族",
    "Twilight Essence": "暮光之子",
    "Arcane Taxation": "奥术苛税",
    "Insta Tax": "瞬发协议",
    "Mass Taxation": "群体征收",
    "Greater Armor": "改良装甲",
    "Crystal Armor": "铸晶装甲",
    "Smiting Thorns": "荆棘护佑",
    "Halting Light": "顿滞神光",
    "Searing Light": "烈焰神光",
    "Quickcast": "法术瞬发",
    "Army of Eagles": "猎鹰军团",
    "Shielded Eagles": "猎鹰甲胄",
    "Thunder Claw": "雷霆之爪",
    "Untouchable Majesty": "上兽之威",
    "Fire Gaze": "烈焰之眼",
    "Shield Gaze": "修复之眼",
    "Bastion of Immortality": "不灭之壁",
    "Dragon Saint": "至圣之威",
    "Immortal Dragon": "金之不朽",
    "Dragon Mage": "巨龙法师",
    "Moonblade": "月光铸剑",
    "Heal Aura": "再生光环",
    "Holy Fire Aura": "圣焰光环",
    "Heal Beam": "愈合波动",
    "Beam Arc": "电弧集束",
    "Storm Archon": "冰暴军团",
    "Flesh Harvest": "血肉狂欢",
    "Dulled Pain": "痛感钝化",
    "Burning Pain": "蚀骨之火",
    "Chaos Pulse": "混沌脉冲",
    "Lesser Cascade": "低联散射",
    "Greater Cascade": "超联迸射",
    "Petrification": "石化光线",
    "Blindcasting": "无需视线",
    "Quickcast": "法术瞬发",
    "Shield Burn": "护盾烧却",
    "Shield Steal": "护盾窃取",
    "Gnashing Teeth": "磨牙凿齿",
    "Invincible Maw": "无敌巨口",
    "Void Maw": "虚空亚种",
    "Darkvision": "黑暗视觉",
    "Dark Clouds": "暗之死云",
    "Eternal Darkness": "永恒之暗",
    "Max Health Loss": "最大生命损伤",
    "Fire Vulnerability": "火焰脆弱",
    "Plague of Undead": "亡者疫灾",
    "Cantrip Burst": "定点爆破",
    "Orb Cascade": "法球共鸣",
    "Evocation Amalgamation": "巫术唤灵",
    "Multicopy": "多重拷贝",
    "Resistance Debuff": "抗性削弱",
    "Max Charges": "充能上限",
    "Venomous Bite": "剧毒撕咬",
    "Savage Leap": "野蛮跃击",
    "Scavengers": "狼群之道",
    "Chaos Storm": "混沌风暴",
    "Rain of Dragons": "龙火技艺",
    "Pyrostatic Storm": "流星掣电",
    "More Shrapnel": "改良破片",
    "Puncturing Blast": "穿刺爆破",
    "Magnetized Shards": "索敌破片",
    "Num Summons": "召唤数量",
    "Minion Duration": "随从持续回合",
    "Serpent Plague": "枭蛇之灾",
    "Explosive Orb": "爆炸过载",
    "Matter Melting": "无坚不熔",
    "Flame Rift": "火焰裂隙",
    "Final Burst": "高压过载",
    "Drakebirth": "巨龙降生",
    "Pyrostatics": "升压爆燃",
    "Petrification Orb": "石化法球",
    "Orb Shards": "破碎迸射",
    "Enchantment Refraction": "魔力折射",
    "Frostfire Tormentor": "霜火刑罚",
    "Metallic Tormentor": "金属拷问",
    "Tormenting Mass": "集群召唤",
    "Crumbling Aura": "崩碎光环",
    "Wormification Aura": "岩蠕光环",
    "Glassify": "玻璃化",
    "Num Targets": "目标数量",
    "Duration": "持续回合",
    "Max Charges": "充能上限",
    "Void Court": "虚空审判",
    "Storm Court": "暴风审判",
    "Chaos Court": "混沌审判",
    "Herbal Remedy": "草药制备",
    "Withertoxin": "邪恶巫毒",
    "Toxin Bomber": "毒素炸弹",
    "Num Summons": "召唤数量",
    "Grey Mushbooms": "瘫痪菌株",
    "Red Mushbooms": "爆燃变异",
    "Glass Mushbooms": "玻璃菌株",
    "Paralyzing Combustion": "瘫痪诱发",
    "Flame Rave": "烈火狂潮",
    "Toxic Embers": "剧毒余烬",
    "Aether Queen": "以太先驱",
    "Steel Queen": "钢之女皇",
    "Vampire Queen": "血族皇后",
    "Refreezing": "再度冻结",
    "Mass Freeze": "集群冻结",
    "Quickcast": "快速施法",
    "Cloud Combustion": "风暴借势",
    "Ice Crush": "冰屑破片",
    "Fae Ball": "敲冰戛玉",
    "Flash Freeze": "急冻风暴",
    "Hailstorm": "坠冰风暴",
    "Snow Feathers": "霜羽祝福",
    "Crystal Eyes Hydra": "晶眼亚种",
    "Freezing Ice": "急冻霜火",
    "Hydra Reclamation": "前仆后继",
    "Stormshield": "风暴护盾",
    "Dual Nova": "双核新星",
    "Spirit Nova": "风暴共鸣",
    "Icy Necromancy": "亡灵冰术",
    "Slaughter Chill": "巫毒寒战",
    "Mass Death Chill": "灭绝寒潮",
    "Reincarnations": "转世轮回",
    "Ice Aura": "冰霜光环",
    "Heal Aura": "治愈光环",
    "Echoing Ice": "冰之回响",
    "Endless Ice": "共鸣冰语",
    "Word of Wind": "速咏成风",
    "Frostgleam": "寒冻闪爆",
    "Faebound Orb": "冰精法球",
    "Blizzard Orb": "暴雪法球",
    "Freezing": "霜冻冰锥",
    "Ice Spear": "冰枪疾射",
    "Icicle Harvest": "冰锥回收",
    "Ice Guardians": "冰灵加护",
    "Dual Wind": "双面驶风",
    "Arcane Storm": "奥术风暴",
    "Hungry Wall": "噬命之欲",
    "Fae Wall": "仙灵祝福",
    "Endless Wall": "无尽冰幕",
    "Bone Spears": "贯通之枪",
    "Cursed Bones": "诅咒之骨",
    "Safety": "自然庇佑",
    "Aftershocks": "余波未尽",
    "Magnitude 8.0": "天震地骇",
    "Slow Burn": "噬体之焰",
    "Chaos Seal": "元素混响",
    "Fire Harvest": "火焰收割",
    "Forced Transfer": "强制转换",
    "Max Charges": "充能上限",
    "Duration": "持续回合",
    "Max Charges": "充能上限",
    "Resistance Debuff": "抗性削弱",
    "Duration": "持续回合",
    "Arcane Gaze": "奥术凝视",
    "Fire Slime": "烈焰亚种",
    "Ice Slime": "霜寒亚种",
    "Void Slime": "虚空亚种",
    "Dual Blazerip": "双向爆闪",
    "Aether Poison": "以太之毒",
    "Blazebugs": "焱虫增殖",
    "Damage": "伤害",
    "Duration": "持续回合",
    "Radius": "半径",
    "Junk Golems": "废品傀儡",
    "Elemental Spirits": "元素篡夺",
    "Restless Minions": "无休战仆",
    "Resistance Melting": "外壳熔解",
    "Linear Conductance": "线性传导",
    "Pyrostatic Chaos": "混沌链接",
    "Defense System": "自卫系统",
    "Manufactory": "集群装配",
    "Copper Spikeballs": "青铜铸法",
    "Morbidity": "恶毒金属",
    "Corrosion": "熔蚀护甲",
    "Toxic Fumes": "毒瘴污染",
    "Mercurial Vengeance": "活化感染",
    "Radioactivity": "放射污染",
    "Electromagnetism": "磁场放电",
    "Liquid Magnetism": "流性磁导",
    "Copper Shaft": "青铜轴体",
    "Consecration": "银枪祝圣",
    "Assistant Cannoneers": "炮兵小队",
    "Recycling": "战场回收",
    "Chaos Cannon": "混沌造物",
    "Mass Blasting": "集群迸射",
    "Wall Penetration": "墙体渗透",
    "Resistance Penetration": "抗性穿透",
    "Radius": "半径",
    "Max Charges": "充能上限",
    "Guardian Gnomes": "侏儒守卫",
    "Fae Flies": "仙化飞蝇",
    "Glass Garden": "玻璃花园",
    "Flames of Sorcery": "炉火升腾",
    "Imp Smithy": "青铜仲魔",
    "Arcane Eyebolts": "奥术猎犬",
    "Ghost Caller": "通灵仪式",
    "Bone Wheel": "死亡之轮",
    "Blood Skull": "骨山血海",
    "Magic Eggs": "魔法胎教",
    "Radiant Eggs": "炫光龙蛋",
    "Scale Harvest": "Scale Harvest",
    "Glimmerblade": "光辉剑刃",
    "Electroblade": "雷电赋能",
    "Steelshaping": "金属共鸣",
    "Lifesteal": "生命窃取",
    "Death Power": "死亡巫能",
    "Torment": "无尽折磨",
    "Fae Bones": "仙化亡灵",
    "Burning Bones": "燃烧亡灵",
    "Bone Shards": "碎骨迸射",
    "Redemption": "天理昭彰",
    "Conversion": "支配戮民",
    "Mass Scourge": "族群天罚",
    "Conflaguration": "连锁焚烧",
    "Radiant Heat": "焚灭扩散",
    "Dragon Soul": "龙魂觉醒",
    "Armor of Armageddon": "终末装甲",
    "Mass Armaments": "连锁湮灭",
    "Mega Armageddon": "最终决战",
    "Infernal Spear": "炎狱咒祝",
    "Toxic Spear": "爆炸毒枪",
    "Stun Spear": "Stun Spear",
    "Toxogenesis": "毒素生物",
    "Mechanogenesis": "机械造物",
    "Ectogenesis": "外质生物",
    "Spear Hag": "骨矛女巫",
    "Nightmare Hag": "夜魇女巫",
    "Bone Queen": "Bone Queen",
    "Pain Aura": "痛苦光环",
    "Greater Thorns": "锋锐荆棘",
    "Vampire Golem": "血族造物",
    "Blood Bond": "生命纽带",
    "Life Funnel": "生命漏斗",
    "Blindcasting": "无需视线",
    "Holy Horde": "Holy Horde",
    "Blasphemy": "亵渎仪式",
    "Arcane Revelation": "奥能绽放",
    "Controlled Appetite": "节制吞噬",
    "Mass Feeding": "分摊治愈",
    "Charred Flesh": "焦焚仆役",
    "Radius": "半径",
    "Damage": "伤害",
    "Max Charges": "充能上限",
    "Range": "射程",
    "Toxic Shift": "Toxic Shift",
    "Belly Flop": "Belly Flop",
    "Barbeque Fiends": "灼肉恶魔",
    "Worm Lord": "蠕虫领主",
    "Aelf Horde": "Aelf Horde",
    "Fae Aelves": "Fae Aelves",
    "Elite Aelves": "Elite Aelves",
    "Trollblooded Halfmen": "巨魔亚种",
    "Metallic Halfmen": "全金属化",
    "Burning Halfmen": "烈焰血统",
    "Bone Explosion": "骸骨爆碎",
    "Archon Beam": "波形光束",
    "Reincarnation": "转世轮回",
    "Pain Aura": "痛苦光环",
    "Maggot Host": "蛆群主脑",
    "Felomancy": "咒猫呼唤",
    "Ursomancy": "血熊呼唤",
    "Radius": "半径",
    "Clay Wizard": "黏土秘术",
    "Ghost Wizard": "幽灵巫师",
    "Wizard Gang": "战法小队",
    "Psychic Fields": "灵能域界",
    "Immortal Forest": "不朽瑶林",
    "Parasitic Growth": "槲寄生",
    "Ensoulment": "灵魂出窍",
    "Arcane Wind": "奥法之风",
    "Dual Wind": "双面驶风",
    "Fae Stampede": "仙灵祝福",
    "Burning Stampede": "燃烧巨象",
    "Metal Stampede": "金属践踏",
    "Boomerang": "回旋弩矢",
    "Toxic Hatred": "淬毒箭头",
    "Torment Harvest": "煎熬收割",
}

consumables = {
    "Healing Potion": "治疗药水",
    "Mana Potion": "法力药水",
    "Teleporter": "传送器",
    "Golden Stopwatch": "金质怀表",
    "Chaos Bell": "混乱之铃",
    "Death Dice": "死亡骰子",
    "Portal Key": "传送钥匙",
    "Earthquake Orb": "地震法球",
    "Oculus": "天眼",
    "Aether Dagger": "以太匕首",
    "Bag of Spikes": "钉球袋",
    "Orb of Corruption": "腐化法球",
}

equipments = {
    "The Bladestaff": "利刃法杖",
    "Geometer's Staff": "制图师法杖",
    "Memory Staff": "记忆法杖",
    "Banner of the Horde": "部族旗帜",
    "Storm Oculus": "Storm Oculus",
    "Void Oculus": "Void Oculus",
    "Pyrostatic Oculus": "Pyrostatic Oculus",
    "Twilight Oculus": "Twilight Oculus",
    "Crystal Oculus": "Crystal Oculus",
    "Purity Oculus": "Purity Oculus",
    "Arcane Amplifier": "Arcane Amplifier",
    "The Flamenweaver": "The Flamenweaver",
    "Treelord Staff": "Treelord Staff",
    "Aetherlord Staff": "Aetherlord Staff",
    "Filthlord Staff": "Filthlord Staff",
    "Flaming Claw Staff": "Flaming Claw Staff",
    "Icy Claw Staff": "Icy Claw Staff",
    "Scepter of Mischief": "Scepter of Mischief",
    "Drakenstaff": "Drakenstaff",
    "The Purifier": "The Purifier",
    "Silvermelt": "Silvermelt",
    "Sorcwinter": "Sorcwinter",
    "The Dynamo": "The Dynamo",
    "The Blazeloom": "The Blazeloom",
    "Starblesser": "Starblesser",
    "The Sparkloom": "The Sparkloom",
    "Wintersting": "Wintersting",
    "Red Majesty": "Red Majesty",
    "Blastmaker": "Blastmaker",
    "Embermaker": "Embermaker",
    "Mantismaker": "Mantismaker",
    "Sprigganmaker": "Sprigganmaker",
    "Impmaker": "Impmaker",
    "Crackledarkener": "Crackledarkener",
    "Scepter of Sorrows": "Scepter of Sorrows",
    "Glassy Fae Staff": "Glassy Fae Staff",
    "Quill Staff": "Quill Staff",
    "Robe of Ice": "Robe of Ice",
    "Robe of Fire": "Robe of Fire",
    "Robe of Void": "Robe of Void",
    "Robe of Storms": "Robe of Storms",
    "Robe of the Druids": "Robe of the Druids",
    "Fae Plate": "Fae Plate",
    "Vampiric Vestments": "Vampiric Vestments",
    "Dwarven Chainmail": "Dwarven Chainmail",
    "Elven Chainmail": "Elven Chainmail",
    "Soulmail": "Soulmail",
    "Basilisk Scale Armor": "Basilisk Scale Armor",
    "Earthtroll Armor": "Earthtroll Armor",
    "Stormtroll Armor": "Stormtroll Armor",
    "Robe of Twilight": "Robe of Twilight",
    "Robe of Agony": "Robe of Agony",
    "Robe of Frostfire": "Robe of Frostfire",
    "Robe of Crystals": "Robe of Crystals",
    "Marksman Cap": "Marksman Cap",
    "Warlord Helm": "Warlord Helm",
    "Spirit Visor": "Spirit Visor",
    "Brain Hat": "Brain Hat",
    "Cannibal Mask": "Cannibal Mask",
    "Helm of the Host": "Helm of the Host",
    "Icy Chill Mask": "Icy Chill Mask",
    "Stone Mask": "Stone Mask",
    "Eye Helm": "Eye Helm",
    "Fire Helm": "Fire Helm",
    "Ice Helm": "Ice Helm",
    "Lightning Helm": "Lightning Helm",
    "Dark Helm": "Dark Helm",
    "Nature Helm": "Nature Helm",
    "Holy Helm": "Holy Helm",
    "Arcane Helm": "Arcane Helm",
    "Metallic Helm": "Metallic Helm",
    "Fire Frenzy Mask": "Fire Frenzy Mask",
    "Ice Frenzy Mask": "Ice Frenzy Mask",
    "Arcane Frenzy Mask": "Arcane Frenzy Mask",
    "Summer Crown": "夏季皇冠",
    "Winter Crown": "冬季皇冠",
    "Spring Crown": "春季皇冠",
    "Autumn Crown": "秋季皇冠",
    "Bloodspike Crown": "Bloodspike Crown",
    "Earthmeld Boots": "Earthmeld Boots",
    "Travellers Shoes": "Travellers Shoes",
    "Cantrip Clogs": "Cantrip Clogs",
    "Timestriders": "Timestriders",
    "Drill Shoes": "Drill Shoes",
    "Winged Shoes": "Winged Shoes",
    "Silken Sandals": "Silken Sandals",
    "Snow Shoes": "Snow Shoes",
    "Translocation Boots": "Translocation Boots",
    "Gnome Shoes": "Gnome Shoes",
    "Slime Shoes": "Slime Shoes",
    "Kobold Clogs": "Kobold Clogs",
    "Ogre Boots": "Ogre Boots",
    "Ghost Slippers": "Ghost Slippers",
    "Storm Boots": "Storm Boots",
    "Exploding Boots": "Exploding Boots",
    "Finger 6": "Finger 6",
    "Ankh": "Ankh",
    "Drakentooth": "Drakentooth",
    "Eye Rock Pendant": "Eye Rock Pendant",
    "Amber Cube": "Amber Cube",
    "Skull Necklace": "Skull Necklace",
    "Red Obsidian Shard": "Red Obsidian Shard",
    "Jade Shard": "Jade Shard",
    "Reality Anchor": "Reality Anchor",
    "Amulet of Undeath": "Amulet of Undeath",
    "Vial of Ambrosia": "Vial of Ambrosia",
    "Amulet of Emerald Flame": "Amulet of Emerald Flame",
    "Monkey Skull Amulet": "Monkey Skull Amulet",
    "Blood Ruby": "Blood Ruby",
    "Bramblethorn": "Bramblethorn",
    "Toadthorn": "Toadthorn",
    "Devilthorn": "Devilthorn",
    "Witch Whistle": "Witch Whistle",
    "Snowy Fursphere": "Snowy Fursphere",
    "Living Emberstone": "Living Emberstone",
    "Silken Links": "Silken Links",
    "Winter Links": "Winter Links",
    "Wrath Links": "Wrath Links",
    "Jar of Trollblood": "巨魔血坛子",
    "Jar of Embers": "余烬坛子",
    "Jar of Quicksilver": "水银坛子",
    "Jar of Ectoplasm": "灵质坛子",
    "Poison Pipe": "毒素吹箭",
    "Time Pipe": "时间吹箭",
    "Ink Pipe": "墨汁吹箭",
    "Ice Pipe": "冰霜吹箭",
    "Purple Curse Doll": "紫色巫蛊",
    "Ugly Curse Doll": "丑陋巫蛊",
    "Red Curse Doll": "红色巫蛊",
}