spells = {
    "Fireball": "Fireball",
    "Lightning Bolt": "Lightning Bolt",
    "Annihilate": "Annihilate",
    "Lightning Form": "Lightning Form",
    "Mega Annihilate": "Mega Annihilate",
    "Teleport": "Teleport",
    "Blink": "Blink",
    "Void Beam": "Void Beam",
    "Thunder Strike": "Thunder Strike",
    "Chaos Barrage": "Chaos Barrage",
    "Disperse": "Disperse",
    "Petrify": "Petrify",
    "Wolf": "Wolf",
    "Giant Bear": "Giant Bear",
    "Sight of Blood": "Sight of Blood",
    "Lightning Storm": "Lightning Storm",
    "Prison of Thorns": "Prison of Thorns",
    "Pillar of Fire": "Pillar of Fire",
    "Boiling Blood": "Boiling Blood",
    "Healing Light": "Healing Light",
    "Regeneration Aura": "Regeneration Aura",
    "Arcane Orb": "Arcane Orb",
    "Dominate": "Dominate",
    "Flame Gate": "Flame Gate",
    "Eye of Fire": "Eye of Fire",
    "Eye of Lightning": "Eye of Lightning",
    "Eye of Ice": "Eye of Ice",
    "Nightmare Aura": "Nightmare Aura",
    "Basilisk Armor": "Basilisk Armor",
    "Watcher Form": "Watcher Form",
    "Imp Swarm": "Imp Swarm",
    "Lightning Halo": "Lightning Halo",
    "Mystic Vision": "Mystic Vision",
    "Mystic Power": "Mystic Power",
    "Flame Burst": "Flame Burst",
    "Fire Drake": "Fire Drake",
    "Storm Drake": "Storm Drake",
    "Void Drake": "Void Drake",
    "Ice Drake": "Ice Drake",
    "Chain Lightning": "Chain Lightning",
    "Death Bolt": "Death Bolt",
    "Touch of Death": "Touch of Death",
    "Seal Fate": "Seal Fate",
    "Wheel of Death": "Wheel of Death",
    "Volcanic Eruption": "Volcanic Eruption",
    "Underworld Passage": "Underworld Passage",
    "Earthen Sentinel": "Earthen Sentinel",
    "Ghostball": "Ghostball",
    "Mystic Memory": "Mystic Memory",
    "Permanence": "Permanence",
    "Vampiric Gaze": "Vampiric Gaze",
    "Magic Missile": "Magic Missile",
    "Devour Mind": "Devour Mind",
    "Death Shock": "Death Shock",
    "Melt": "Melt",
    "Dragon Roar": "Dragon Roar",
    "Ironize": "Ironize",
    "Word of Chaos": "Word of Chaos",
    "Word of Undeath": "Word of Undeath",
    "Word of Beauty": "Word of Beauty",
    "Floating Eye": "Floating Eye",
    "Eye of Rage": "Eye of Rage",
    "Arc Lightning": "Arc Lightning",
    "Fan of Flames": "Fan of Flames",
    "Poison Sting": "Poison Sting",
    "Blue Lion": "Blue Lion",
    "Death Cleave": "Death Cleave",
    "Multicast": "Multicast",
    "Fae Court": "Fae Court",
    "Ring of Spiders": "Ring of Spiders",
    "Word of Madness": "Word of Madness",
    "Heavenly Blast": "Heavenly Blast",
    "Holy Fire": "Holy Fire",
    "Choir of Angels": "Choir of Angels",
    "Heaven's Wrath": "Heaven's Wrath",
    "Suspend Mortality": "Suspend Mortality",
    "Soul Tax": "Soul Tax",
    "Holy Armor": "Holy Armor",
    "Blinding Light": "Blinding Light",
    "Flock of Eagles": "Flock of Eagles",
    "Heavenly Idol": "Heavenly Idol",
    "Gold Drake": "Gold Drake",
    "Call Seraph": "Call Seraph",
    "Call Archon": "Call Archon",
    "Pain Mirror": "Pain Mirror",
    "Pyrostatic Pulse": "Pyrostatic Pulse",
    "Aether Swap": "Aether Swap",
    "Siphon Shields": "Siphon Shields",
    "Hungry Maw": "Hungry Maw",
    "Darkness": "Darkness",
    "Plague of Undeath": "Plague of Undeath",
    "Cantrip Cascade": "Cantrip Cascade",
    "Conductance": "Conductance",
    "Invoke Savagery": "Invoke Savagery",
    "Rain of Fire": "Rain of Fire",
    "Shrapnel Blast": "Shrapnel Blast",
    "Plague of Filth": "Plague of Filth",
    "Searing Orb": "Searing Orb",
    "Ball Lightning": "Ball Lightning",
    "Orb Control": "Orb Control",
    "Glass Orb": "Glass Orb",
    "Fiery Tormentor": "Fiery Tormentor",
    "Petrification Aura": "Petrification Aura",
    "Dispersion Field": "Dispersion Field",
    "Knightly Oath": "Knightly Oath",
    "Toxin Burst": "Toxin Burst",
    "Toxic Spores": "Toxic Spores",
    "Combust Poison": "Combust Poison",
    "Spider Queen": "Spider Queen",
    "Freeze": "Freeze",
    "Iceball": "Iceball",
    "Blizzard": "Blizzard",
    "Frostfire Hydra": "Frostfire Hydra",
    "Storm Burst": "Storm Burst",
    "Death Chill": "Death Chill",
    "Ice Phoenix": "Ice Phoenix",
    "Word of Ice": "Word of Ice",
    "Ice Orb": "Ice Orb",
    "Icicle": "Icicle",
    "Chill Wind": "Chill Wind",
    "Wall of Ice": "Wall of Ice",
    "Bone Barrage": "Bone Barrage",
    "Earthquake": "Earthquake",
    "Searing Seal": "Searing Seal",
    "Soul Swap": "Soul Swap",
    "Purity": "Purity",
    "Twilight Gaze": "Twilight Gaze",
    "Slime Form": "Slime Form",
    "Blazerip": "Blazerip",
    "Ice Vortex": "Ice Vortex",
    "The Restless Dead": "The Restless Dead",
    "Pyrostatic Curse": "Pyrostatic Curse",
    "Spikeball Factory": "Spikeball Factory",
    "Mercurize": "Mercurize",
    "Magnetize": "Magnetize",
    "Silver Spear": "Silver Spear",
    "Siege Golems": "Siege Golems",
    "Lightning Spire": "Lightning Spire",
    "Essence Flux": "Essence Flux",
    "Faehaunt Garden": "Faehaunt Garden",
    "Furnace of Sorcery": "Furnace of Sorcery",
    "Golden Skull": "Golden Skull",
    "Wyrm Eggs": "Wyrm Eggs",
    "Moon Glaive": "Moon Glaive",
    "Carnival of Pain": "Carnival of Pain",
    "Dreamwalk": "Dreamwalk",
    "Mass Calcification": "Mass Calcification",
    "Scourge": "Scourge",
    "Immolate": "Immolate",
    "Armageddon Blade": "Armageddon Blade",
    "Bone Spear": "Bone Spear",
    "Lumbriogenesis": "Lumbriogenesis",
    "Night Hag": "Night Hag",
    "Blood Golem": "Blood Golem",
    "Lifedrain": "Lifedrain",
    "Ritual of Revelation": "Ritual of Revelation",
    "Devour Flesh": "Devour Flesh",
    "Bloodshift": "Bloodshift",
    "Flesh Fiend": "Flesh Fiend",
    "Gates of Helheim": "Gates of Helheim",
    "Horde of Halfmen": "Horde of Halfmen",
    "Burning Idol": "Burning Idol",
    "Goatia Offering": "Goatia Offering",
    "Drain Pulse": "Drain Pulse",
    "Summon Wizard": "Summon Wizard",
    "Psychic Seedling": "Psychic Seedling",
    "Soul Wind": "Soul Wind",
    "Stampede Form": "Stampede Form",
    "Hatebolts": "Hatebolts",
    "Bloodflame": "Bloodflame",
}

skills = {
    "Arch Enchanter": "Arch Enchanter",
    "Arch Sorcerer": "Arch Sorcerer",
    "Arch Conjurer": "Arch Conjurer",
    "Fire Lord": "Fire Lord",
    "Ice Lord": "Ice Lord",
    "Thunder Lord": "Thunder Lord",
    "Nature Lord": "Nature Lord",
    "Dark Lord": "Dark Lord",
    "Void Lord": "Void Lord",
    "Light Lord": "Light Lord",
    "Dragon Lord": "Dragon Lord",
    "Orb Lord": "Orb Lord",
    "Metal Lord": "Metal Lord",
    "Unblinking Eye": "Unblinking Eye",
    "Translocation Master": "Translocation Master",
    "Pyrophilia": "Pyrophilia",
    "Minion Regeneration": "Minion Regeneration",
    "Searing Heat": "Searing Heat",
    "Arcane Combustion": "Arcane Combustion",
    "Soul Harvest": "Soul Harvest",
    "Arcane Accounting": "Arcane Accounting",
    "Natural Healing": "Natural Healing",
    "Glittering Dance": "Glittering Dance",
    "Lightning Frenzy": "Lightning Frenzy",
    "Melting Armor": "Melting Armor",
    "Natural Vigour": "Natural Vigour",
    "Hungry Dead": "Hungry Dead",
    "Lightning Warp": "Lightning Warp",
    "Holy Thunder": "Holy Thunder",
    "Fiery Judgement": "Fiery Judgement",
    "Starfire": "Starfire",
    "Shock Value": "Shock Value",
    "Horror": "Horror",
    "Arcane Shield": "Arcane Shield",
    "Shielded Minions": "Shielded Minions",
    "Ghostfire": "Ghostfire",
    "Wordspeaker": "Wordspeaker",
    "Prince of Ruin": "Prince of Ruin",
    "Righteous March": "Righteous March",
    "Chastisement": "Chastisement",
    "Chaos Casting": "Chaos Casting",
    "Unholy Alliance": "Unholy Alliance",
    "Thorn Garden": "Thorn Garden",
    "Faestone": "Faestone",
    "Houndlord": "Houndlord",
    "Hypocrisy": "Hypocrisy",
    "Cracklevoid": "Cracklevoid",
    "Bone Guard": "Bone Guard",
    "Spider Spawning": "Spider Spawning",
    "Paralyzing Venom": "Paralyzing Venom",
    "Venom Spit": "Venom Spit",
    "Icy Vengeance": "Icy Vengeance",
    "Ice Tap": "Ice Tap",
    "Frostbite": "Frostbite",
    "Steam Anima": "Steam Anima",
    "Storm Caller": "Storm Caller",
    "Holy Water": "Holy Water",
    "Hibernation": "Hibernation",
    "Crystal Power": "Crystal Power",
    "Radiant Chill": "Radiant Chill",
    "Shatter Shards": "Shatter Shards",
    "Frozen Fragility": "Frozen Fragility",
    "Scalespinner": "Scalespinner",
    "Collected Agony": "Collected Agony",
    "Moonspeaker": "Moonspeaker",
    "Void Spikes": "Void Spikes",
    "Necrostatics": "Necrostatics",
    "Purestrike": "Purestrike",
    "Silkshifter": "Silkshifter",
    "Inferno Engines": "Inferno Engines",
    "Megavenom": "Megavenom",
    "Acid Fumes": "Acid Fumes",
    "Voidflame Lantern": "Voidflame Lantern",
    "Chaos Poet": "Chaos Poet",
    "Master of Space": "Master of Space",
    "Master of Time": "Master of Time",
    "Master of Memories": "Master of Memories",
    "Spell Sniper": "Spell Sniper",
    "Echomancer": "Echomancer",
    "Disintegrator": "Disintegrator",
    "Fae Malevolence": "Fae Malevolence",
    "Blood Anima": "Blood Anima",
    "Blood Reaping": "Blood Reaping",
    "Blood Lord": "Blood Lord",
    "Scent of Blood": "Scent of Blood",
    "Stormbrood Tricksters": "Stormbrood Tricksters",
    "Lifespark Lantern": "Lifespark Lantern",
    "Scalefeather Egregore": "Scalefeather Egregore",
    "Toadblood Transmutation": "Toadblood Transmutation",
    "Chaos Familiar": "Chaos Familiar",
    "Deathchill Familiar": "Deathchill Familiar",
    "Demonic Cruelty": "Demonic Cruelty",
    "Enchanters Boon": "Enchanters Boon",
    "Hordemancer": "Hordemancer",
    "Conjured Vitality": "Conjured Vitality",
    "Conjured Aggression": "Conjured Aggression",
    "Serpents of Chaos": "Serpents of Chaos",
    "Multimancy": "Multimancy",
    "Armorer": "Armorer",
    "Hemocorruption": "Hemocorruption",
    "Earthwrath": "Earthwrath",
}

upgrades = {
    "Chaos Ball": "Chaos Ball",
    "Ash Ball": "Ash Ball",
    "Meteor": "Meteor",
    "Channeling": "Channeling",
    "Electric Ink": "Electric Ink",
    "Energy Bolt": "Energy Bolt",
    "Cascade": "Cascade",
    "Comprehensive Annihilation": "Comprehensive Annihilation",
    "Doom Storm": "Doom Storm",
    "Lingering Form": "Lingering Form",
    "Fire Form": "Fire Form",
    "Crackling Aura": "Crackling Aura",
    "Cascade": "Cascade",
    "Dark Annihilation": "Dark Annihilation",
    "Arcane Annihilation": "Arcane Annihilation",
    "Quickcast": "Quickcast",
    "Group Teleport": "Group Teleport",
    "Void Teleport": "Void Teleport",
    "Blindcasting": "Blindcasting",
    "Dissolution": "Dissolution",
    "Thunderblink": "Thunderblink",
    "Void Binding": "Void Binding",
    "Star Beam": "Star Beam",
    "Voidcurse": "Voidcurse",
    "Blindcasting": "Blindcasting",
    "Storm Power": "Storm Power",
    "Heaven Strike": "Heaven Strike",
    "Mega Barrage": "Mega Barrage",
    "Shockwaves": "Shockwaves",
    "Smart Bolts": "Smart Bolts",
    "Violent Warp": "Violent Warp",
    "Protective Warp": "Protective Warp",
    "Glassify": "Glassify",
    "Arcane Conductivity": "Arcane Conductivity",
    "Rocky Servitude": "Rocky Servitude",
    "Wolf Pack": "Wolf Pack",
    "Ice Hound": "Ice Hound",
    "Clay Hound": "Clay Hound",
    "Metal Bear": "Metal Bear",
    "Venom Bear": "Venom Bear",
    "Blood Bear": "Blood Bear",
    "Duration": "Duration",
    "Demon Frenzy": "Demon Frenzy",
    "Blindcasting": "Blindcasting",
    "Particle Storm": "Particle Storm",
    "Lightning Star": "Lightning Star",
    "Spirit Harvest": "Spirit Harvest",
    "Minion Damage": "Minion Damage",
    "Minion Health": "Minion Health",
    "Iron Prison": "Iron Prison",
    "Icy Prison": "Icy Prison",
    "Channeling": "Channeling",
    "Disrupting Flames": "Disrupting Flames",
    "Pillar of Annihilation": "Pillar of Annihilation",
    "Extra Damage": "Extra Damage",
    "Duration": "Duration",
    "Holy Fury": "Holy Fury",
    "Dark Fury": "Dark Fury",
    "Shielding Light": "Shielding Light",
    "Purifying Light": "Purifying Light",
    "Heartflame": "Heartflame",
    "Heal": "Heal",
    "Duration": "Duration",
    "Global": "Global",
    "Blazerip Orb": "Blazerip Orb",
    "Double Shot": "Double Shot",
    "Orb Detonation": "Orb Detonation",
    "HP Threshold": "HP Threshold",
    "Brute Force": "Brute Force",
    "Undead Servitude": "Undead Servitude",
    "Burst Fire": "Burst Fire",
    "Eye Gate": "Eye Gate",
    "Starfire Gate": "Starfire Gate",
    "Eye of Fireballs": "Eye of Fireballs",
    "Fiery Onlooker": "Fiery Onlooker",
    "Eye of Conflaguration": "Eye of Conflaguration",
    "Archon Eye": "Archon Eye",
    "Eye of Thunderstrike": "Eye of Thunderstrike",
    "Penetrating Gaze": "Penetrating Gaze",
    "Frosty Onlooker": "Frosty Onlooker",
    "Eye of Freezing": "Eye of Freezing",
    "Eye of Iceballs": "Eye of Iceballs",
    "Dark Dream": "Dark Dream",
    "Electric Dream": "Electric Dream",
    "Fever Dream": "Fever Dream",
    "Max Charges": "Max Charges",
    "Duration": "Duration",
    "Pyrostatic Watcher Form": "Pyrostatic Watcher Form",
    "Void Watcher Form": "Void Watcher Form",
    "Chain Watcher Form": "Chain Watcher Form",
    "Metal Swarm": "Metal Swarm",
    "Dark Swarm": "Dark Swarm",
    "Endless Swarm": "Endless Swarm",
    "Ring of Fire": "Ring of Fire",
    "Radioactive Field": "Radioactive Field",
    "Lightning Nova": "Lightning Nova",
    "Duration": "Duration",
    "Bonus": "Bonus",
    "Vision Aura": "Vision Aura",
    "Duration": "Duration",
    "Damage Bonus": "Damage Bonus",
    "Intensity": "Intensity",
    "Melting Flame": "Melting Flame",
    "Bright Flame": "Bright Flame",
    "Spreading Flame": "Spreading Flame",
    "Broodlings": "Broodlings",
    "Metal Dragon": "Metal Dragon",
    "Dragon Mage": "Dragon Mage",
    "Storm Summoning": "Storm Summoning",
    "Ghost Drake": "Ghost Drake",
    "Drake Swap": "Drake Swap",
    "Dragon Mage": "Dragon Mage",
    "Shields": "Shields",
    "Dragon Mage": "Dragon Mage",
    "Essence Drake": "Essence Drake",
    "Dracolich": "Dracolich",
    "Broodlings": "Broodlings",
    "Dragon Mage": "Dragon Mage",
    "Chain Fireball": "Chain Fireball",
    "Cloud Conductance": "Cloud Conductance",
    "Lightning Shield": "Lightning Shield",
    "Soul Battery": "Soul Battery",
    "Winter Bolt": "Winter Bolt",
    "Chaos Skeletons": "Chaos Skeletons",
    "Flametouch": "Flametouch",
    "Touch of the Vampire": "Touch of the Vampire",
    "Touch of the Reaper": "Touch of the Reaper",
    "Hand of Death": "Hand of Death",
    "Blindcasting": "Blindcasting",
    "Spreading Curse": "Spreading Curse",
    "Genocide": "Genocide",
    "Max Charges": "Max Charges",
    "Cheat Fate": "Cheat Fate",
    "Flow Range": "Flow Range",
    "Blindcasting": "Blindcasting",
    "Wallcano": "Wallcano",
    "Quickcast": "Quickcast",
    "Tremorsensitivity": "Tremorsensitivity",
    "Earthquake Totem": "Earthquake Totem",
    "Stinging Totem": "Stinging Totem",
    "Holy Totem": "Holy Totem",
    "Radius": "Radius",
    "Ghost King": "Ghost King",
    "Ghost Mass": "Ghost Mass",
    "Distant Memory": "Distant Memory",
    "Deep Reflection": "Deep Reflection",
    "Shield of Memories": "Shield of Memories",
    "Duration": "Duration",
    "Toxic Gaze": "Toxic Gaze",
    "Vampiric Tax": "Vampiric Tax",
    "Refracting Gaze": "Refracting Gaze",
    "Shield Burn": "Shield Burn",
    "Disruption Bolt": "Disruption Bolt",
    "Arcane Crossfire": "Arcane Crossfire",
    "Ricochet": "Ricochet",
    "Huskification": "Huskification",
    "Spirit Eater": "Spirit Eater",
    "Gluttony": "Gluttony",
    "Fire Shock": "Fire Shock",
    "Shield Burn": "Shield Burn",
    "Corpse Construct": "Corpse Construct",
    "Mass Melt": "Mass Melt",
    "Ice Penetration": "Ice Penetration",
    "White Flame": "White Flame",
    "Draconic Vitality": "Draconic Vitality",
    "Draconic Vigor": "Draconic Vigor",
    "Draconic Majesty": "Draconic Majesty",
    "Armor Plating": "Armor Plating",
    "Permanent Transmutation": "Permanent Transmutation",
    "Arcane Insulation": "Arcane Insulation",
    "Animated Chaos": "Animated Chaos",
    "Chaos Gifts": "Chaos Gifts",
    "Echoing Chaos": "Echoing Chaos",
    "Hatred of Life": "Hatred of Life",
    "Spirit Gift": "Spirit Gift",
    "Spirit of Lichdom": "Spirit of Lichdom",
    "Beauty of Steel": "Beauty of Steel",
    "Shield Strip": "Shield Strip",
    "Echoing Beauty": "Echoing Beauty",
    "Stone Gaze": "Stone Gaze",
    "Eyemage": "Eyemage",
    "Regenerating Shields": "Regenerating Shields",
    "Lycanthropy": "Lycanthropy",
    "Infectious Rage": "Infectious Rage",
    "Burning Rage": "Burning Rage",
    "Proton Storm": "Proton Storm",
    "Enervation": "Enervation",
    "Multi Flash": "Multi Flash",
    "Healing Hearthfire": "Healing Hearthfire",
    "Fan of Frostfire": "Fan of Frostfire",
    "Wildfire": "Wildfire",
    "Acidity": "Acidity",
    "Silk Shot": "Silk Shot",
    "Stinger Barrage": "Stinger Barrage",
    "Holy Bolt": "Holy Bolt",
    "Shimmermane": "Shimmermane",
    "Burning Lion": "Burning Lion",
    "Duration": "Duration",
    "Max Charges": "Max Charges",
    "Copies": "Copies",
    "Duration": "Duration",
    "Max Charges": "Max Charges",
    "Winter Faery": "Winter Faery",
    "Summon Queen": "Summon Queen",
    "Glass Faery": "Glass Faery",
    "Turbo Toxin": "Turbo Toxin",
    "Long Webs": "Long Webs",
    "Aether Spiders": "Aether Spiders",
    "Selective Madness": "Selective Madness",
    "Echoing Madness": "Echoing Madness",
    "Guardians of Madness": "Guardians of Madness",
    "Spirit Bind": "Spirit Bind",
    "Shield": "Shield",
    "Echo Heal": "Echo Heal",
    "Holy Smite": "Holy Smite",
    "Divine Blaze": "Divine Blaze",
    "Heaven Call": "Heaven Call",
    "Dual Angels": "Dual Angels",
    "Mercy": "Mercy",
    "Massive Chorus": "Massive Chorus",
    "Culling": "Culling",
    "Halt Heretics": "Halt Heretics",
    "Fiery Wrath": "Fiery Wrath",
    "Endlessness": "Endlessness",
    "Mass Immortaity": "Mass Immortaity",
    "Twilight Essence": "Twilight Essence",
    "Arcane Taxation": "Arcane Taxation",
    "Insta Tax": "Insta Tax",
    "Mass Taxation": "Mass Taxation",
    "Greater Armor": "Greater Armor",
    "Crystal Armor": "Crystal Armor",
    "Smiting Thorns": "Smiting Thorns",
    "Halting Light": "Halting Light",
    "Searing Light": "Searing Light",
    "Quickcast": "Quickcast",
    "Army of Eagles": "Army of Eagles",
    "Shielded Eagles": "Shielded Eagles",
    "Thunder Claw": "Thunder Claw",
    "Untouchable Majesty": "Untouchable Majesty",
    "Fire Gaze": "Fire Gaze",
    "Shield Gaze": "Shield Gaze",
    "Bastion of Immortality": "Bastion of Immortality",
    "Dragon Saint": "Dragon Saint",
    "Immortal Dragon": "Immortal Dragon",
    "Dragon Mage": "Dragon Mage",
    "Moonblade": "Moonblade",
    "Heal Aura": "Heal Aura",
    "Holy Fire Aura": "Holy Fire Aura",
    "Heal Beam": "Heal Beam",
    "Beam Arc": "Beam Arc",
    "Storm Archon": "Storm Archon",
    "Flesh Harvest": "Flesh Harvest",
    "Dulled Pain": "Dulled Pain",
    "Burning Pain": "Burning Pain",
    "Chaos Pulse": "Chaos Pulse",
    "Lesser Cascade": "Lesser Cascade",
    "Greater Cascade": "Greater Cascade",
    "Petrification": "Petrification",
    "Blindcasting": "Blindcasting",
    "Quickcast": "Quickcast",
    "Shield Burn": "Shield Burn",
    "Shield Steal": "Shield Steal",
    "Gnashing Teeth": "Gnashing Teeth",
    "Invincible Maw": "Invincible Maw",
    "Void Maw": "Void Maw",
    "Darkvision": "Darkvision",
    "Dark Clouds": "Dark Clouds",
    "Eternal Darkness": "Eternal Darkness",
    "Max Health Loss": "Max Health Loss",
    "Fire Vulnerability": "Fire Vulnerability",
    "Plague of Undead": "Plague of Undead",
    "Cantrip Burst": "Cantrip Burst",
    "Orb Cascade": "Orb Cascade",
    "Evocation Amalgamation": "Evocation Amalgamation",
    "Multicopy": "Multicopy",
    "Resistance Debuff": "Resistance Debuff",
    "Max Charges": "Max Charges",
    "Venomous Bite": "Venomous Bite",
    "Savage Leap": "Savage Leap",
    "Scavengers": "Scavengers",
    "Chaos Storm": "Chaos Storm",
    "Rain of Dragons": "Rain of Dragons",
    "Pyrostatic Storm": "Pyrostatic Storm",
    "More Shrapnel": "More Shrapnel",
    "Puncturing Blast": "Puncturing Blast",
    "Magnetized Shards": "Magnetized Shards",
    "Num Summons": "Num Summons",
    "Minion Duration": "Minion Duration",
    "Serpent Plague": "Serpent Plague",
    "Explosive Orb": "Explosive Orb",
    "Matter Melting": "Matter Melting",
    "Flame Rift": "Flame Rift",
    "Final Burst": "Final Burst",
    "Drakebirth": "Drakebirth",
    "Pyrostatics": "Pyrostatics",
    "Petrification Orb": "Petrification Orb",
    "Orb Shards": "Orb Shards",
    "Enchantment Refraction": "Enchantment Refraction",
    "Frostfire Tormentor": "Frostfire Tormentor",
    "Metallic Tormentor": "Metallic Tormentor",
    "Tormenting Mass": "Tormenting Mass",
    "Crumbling Aura": "Crumbling Aura",
    "Wormification Aura": "Wormification Aura",
    "Glassify": "Glassify",
    "Num Targets": "Num Targets",
    "Duration": "Duration",
    "Max Charges": "Max Charges",
    "Void Court": "Void Court",
    "Storm Court": "Storm Court",
    "Chaos Court": "Chaos Court",
    "Herbal Remedy": "Herbal Remedy",
    "Withertoxin": "Withertoxin",
    "Toxin Bomber": "Toxin Bomber",
    "Num Summons": "Num Summons",
    "Grey Mushbooms": "Grey Mushbooms",
    "Red Mushbooms": "Red Mushbooms",
    "Glass Mushbooms": "Glass Mushbooms",
    "Paralyzing Combustion": "Paralyzing Combustion",
    "Flame Rave": "Flame Rave",
    "Toxic Embers": "Toxic Embers",
    "Aether Queen": "Aether Queen",
    "Steel Queen": "Steel Queen",
    "Vampire Queen": "Vampire Queen",
    "Refreezing": "Refreezing",
    "Mass Freeze": "Mass Freeze",
    "Quickcast": "Quickcast",
    "Cloud Combustion": "Cloud Combustion",
    "Ice Crush": "Ice Crush",
    "Fae Ball": "Fae Ball",
    "Flash Freeze": "Flash Freeze",
    "Hailstorm": "Hailstorm",
    "Snow Feathers": "Snow Feathers",
    "Crystal Eyes Hydra": "Crystal Eyes Hydra",
    "Freezing Ice": "Freezing Ice",
    "Hydra Reclamation": "Hydra Reclamation",
    "Stormshield": "Stormshield",
    "Dual Nova": "Dual Nova",
    "Spirit Nova": "Spirit Nova",
    "Icy Necromancy": "Icy Necromancy",
    "Slaughter Chill": "Slaughter Chill",
    "Mass Death Chill": "Mass Death Chill",
    "Reincarnations": "Reincarnations",
    "Ice Aura": "Ice Aura",
    "Heal Aura": "Heal Aura",
    "Echoing Ice": "Echoing Ice",
    "Endless Ice": "Endless Ice",
    "Word of Wind": "Word of Wind",
    "Frostgleam": "Frostgleam",
    "Faebound Orb": "Faebound Orb",
    "Blizzard Orb": "Blizzard Orb",
    "Freezing": "Freezing",
    "Ice Spear": "Ice Spear",
    "Icicle Harvest": "Icicle Harvest",
    "Ice Guardians": "Ice Guardians",
    "Dual Wind": "Dual Wind",
    "Arcane Storm": "Arcane Storm",
    "Hungry Wall": "Hungry Wall",
    "Fae Wall": "Fae Wall",
    "Endless Wall": "Endless Wall",
    "Bone Spears": "Bone Spears",
    "Cursed Bones": "Cursed Bones",
    "Safety": "Safety",
    "Aftershocks": "Aftershocks",
    "Magnitude 8.0": "Magnitude 8.0",
    "Slow Burn": "Slow Burn",
    "Chaos Seal": "Chaos Seal",
    "Fire Harvest": "Fire Harvest",
    "Forced Transfer": "Forced Transfer",
    "Max Charges": "Max Charges",
    "Duration": "Duration",
    "Max Charges": "Max Charges",
    "Resistance Debuff": "Resistance Debuff",
    "Duration": "Duration",
    "Arcane Gaze": "Arcane Gaze",
    "Fire Slime": "Fire Slime",
    "Ice Slime": "Ice Slime",
    "Void Slime": "Void Slime",
    "Dual Blazerip": "Dual Blazerip",
    "Aether Poison": "Aether Poison",
    "Blazebugs": "Blazebugs",
    "Damage": "Damage",
    "Duration": "Duration",
    "Radius": "Radius",
    "Junk Golems": "Junk Golems",
    "Elemental Spirits": "Elemental Spirits",
    "Restless Minions": "Restless Minions",
    "Resistance Melting": "Resistance Melting",
    "Linear Conductance": "Linear Conductance",
    "Pyrostatic Chaos": "Pyrostatic Chaos",
    "Defense System": "Defense System",
    "Manufactory": "Manufactory",
    "Copper Spikeballs": "Copper Spikeballs",
    "Morbidity": "Morbidity",
    "Corrosion": "Corrosion",
    "Toxic Fumes": "Toxic Fumes",
    "Mercurial Vengeance": "Mercurial Vengeance",
    "Radioactivity": "Radioactivity",
    "Electromagnetism": "Electromagnetism",
    "Liquid Magnetism": "Liquid Magnetism",
    "Copper Shaft": "Copper Shaft",
    "Consecration": "Consecration",
    "Assistant Cannoneers": "Assistant Cannoneers",
    "Recycling": "Recycling",
    "Chaos Cannon": "Chaos Cannon",
    "Mass Blasting": "Mass Blasting",
    "Wall Penetration": "Wall Penetration",
    "Resistance Penetration": "Resistance Penetration",
    "Radius": "Radius",
    "Max Charges": "Max Charges",
    "Guardian Gnomes": "Guardian Gnomes",
    "Fae Flies": "Fae Flies",
    "Glass Garden": "Glass Garden",
    "Flames of Sorcery": "Flames of Sorcery",
    "Imp Smithy": "Imp Smithy",
    "Arcane Eyebolts": "Arcane Eyebolts",
    "Ghost Caller": "Ghost Caller",
    "Bone Wheel": "Bone Wheel",
    "Blood Skull": "Blood Skull",
    "Magic Eggs": "Magic Eggs",
    "Radiant Eggs": "Radiant Eggs",
    "Scale Harvest": "Scale Harvest",
    "Glimmerblade": "Glimmerblade",
    "Electroblade": "Electroblade",
    "Steelshaping": "Steelshaping",
    "Lifesteal": "Lifesteal",
    "Death Power": "Death Power",
    "Torment": "Torment",
    "Fae Bones": "Fae Bones",
    "Burning Bones": "Burning Bones",
    "Bone Shards": "Bone Shards",
    "Redemption": "Redemption",
    "Conversion": "Conversion",
    "Mass Scourge": "Mass Scourge",
    "Conflaguration": "Conflaguration",
    "Radiant Heat": "Radiant Heat",
    "Dragon Soul": "Dragon Soul",
    "Armor of Armageddon": "Armor of Armageddon",
    "Mass Armaments": "Mass Armaments",
    "Mega Armageddon": "Mega Armageddon",
    "Infernal Spear": "Infernal Spear",
    "Toxic Spear": "Toxic Spear",
    "Stun Spear": "Stun Spear",
    "Toxogenesis": "Toxogenesis",
    "Mechanogenesis": "Mechanogenesis",
    "Ectogenesis": "Ectogenesis",
    "Spear Hag": "Spear Hag",
    "Nightmare Hag": "Nightmare Hag",
    "Bone Queen": "Bone Queen",
    "Pain Aura": "Pain Aura",
    "Greater Thorns": "Greater Thorns",
    "Vampire Golem": "Vampire Golem",
    "Blood Bond": "Blood Bond",
    "Life Funnel": "Life Funnel",
    "Blindcasting": "Blindcasting",
    "Holy Horde": "Holy Horde",
    "Blasphemy": "Blasphemy",
    "Arcane Revelation": "Arcane Revelation",
    "Controlled Appetite": "Controlled Appetite",
    "Mass Feeding": "Mass Feeding",
    "Charred Flesh": "Charred Flesh",
    "Radius": "Radius",
    "Damage": "Damage",
    "Max Charges": "Max Charges",
    "Range": "Range",
    "Toxic Shift": "Toxic Shift",
    "Belly Flop": "Belly Flop",
    "Barbeque Fiends": "Barbeque Fiends",
    "Worm Lord": "Worm Lord",
    "Aelf Horde": "Aelf Horde",
    "Fae Aelves": "Fae Aelves",
    "Elite Aelves": "Elite Aelves",
    "Trollblooded Halfmen": "Trollblooded Halfmen",
    "Metallic Halfmen": "Metallic Halfmen",
    "Burning Halfmen": "Burning Halfmen",
    "Bone Explosion": "Bone Explosion",
    "Archon Beam": "Archon Beam",
    "Reincarnation": "Reincarnation",
    "Pain Aura": "Pain Aura",
    "Maggot Host": "Maggot Host",
    "Felomancy": "Felomancy",
    "Ursomancy": "Ursomancy",
    "Radius": "Radius",
    "Clay Wizard": "Clay Wizard",
    "Ghost Wizard": "Ghost Wizard",
    "Wizard Gang": "Wizard Gang",
    "Psychic Fields": "Psychic Fields",
    "Immortal Forest": "Immortal Forest",
    "Parasitic Growth": "Parasitic Growth",
    "Ensoulment": "Ensoulment",
    "Arcane Wind": "Arcane Wind",
    "Dual Wind": "Dual Wind",
    "Fae Stampede": "Fae Stampede",
    "Burning Stampede": "Burning Stampede",
    "Metal Stampede": "Metal Stampede",
    "Boomerang": "Boomerang",
    "Toxic Hatred": "Toxic Hatred",
    "Torment Harvest": "Torment Harvest",
}

consumables = {
    "Healing Potion": "Healing Potion",
    "Mana Potion": "Mana Potion",
    "Teleporter": "Teleporter",
    "Golden Stopwatch": "Golden Stopwatch",
    "Chaos Bell": "Chaos Bell",
    "Death Dice": "Death Dice",
    "Portal Key": "Portal Key",
    "Earthquake Orb": "Earthquake Orb",
    "Oculus": "Oculus",
    "Aether Dagger": "Aether Dagger",
    "Bag of Spikes": "Bag of Spikes",
    "Orb of Corruption": "Orb of Corruption",
}

equipments = {
    "The Bladestaff": "The Bladestaff",
    "Geometer's Staff": "Geometer's Staff",
    "Memory Staff": "Memory Staff",
    "Banner of the Horde": "Banner of the Horde",
    "Storm Oculus": "Storm Oculus",
    "Void Oculus": "Void Oculus",
    "Pyrostatic Oculus": "Pyrostatic Oculus",
    "Twilight Oculus": "Twilight Oculus",
    "Crystal Oculus": "Crystal Oculus",
    "Purity Oculus": "Purity Oculus",
    "Arcane Amplifier": "Arcane Amplifier",
    "The Flamenweaver": "The Flamenweaver",
    "Treelord Staff": "Treelord Staff",
    "Aetherlord Staff": "Aetherlord Staff",
    "Filthlord Staff": "Filthlord Staff",
    "Flaming Claw Staff": "Flaming Claw Staff",
    "Icy Claw Staff": "Icy Claw Staff",
    "Scepter of Mischief": "Scepter of Mischief",
    "Drakenstaff": "Drakenstaff",
    "The Purifier": "The Purifier",
    "Silvermelt": "Silvermelt",
    "Sorcwinter": "Sorcwinter",
    "The Dynamo": "The Dynamo",
    "The Blazeloom": "The Blazeloom",
    "Starblesser": "Starblesser",
    "The Sparkloom": "The Sparkloom",
    "Wintersting": "Wintersting",
    "Red Majesty": "Red Majesty",
    "Blastmaker": "Blastmaker",
    "Embermaker": "Embermaker",
    "Mantismaker": "Mantismaker",
    "Sprigganmaker": "Sprigganmaker",
    "Impmaker": "Impmaker",
    "Crackledarkener": "Crackledarkener",
    "Scepter of Sorrows": "Scepter of Sorrows",
    "Glassy Fae Staff": "Glassy Fae Staff",
    "Quill Staff": "Quill Staff",
    "Robe of Ice": "Robe of Ice",
    "Robe of Fire": "Robe of Fire",
    "Robe of Void": "Robe of Void",
    "Robe of Storms": "Robe of Storms",
    "Robe of the Druids": "Robe of the Druids",
    "Fae Plate": "Fae Plate",
    "Vampiric Vestments": "Vampiric Vestments",
    "Dwarven Chainmail": "Dwarven Chainmail",
    "Elven Chainmail": "Elven Chainmail",
    "Soulmail": "Soulmail",
    "Basilisk Scale Armor": "Basilisk Scale Armor",
    "Earthtroll Armor": "Earthtroll Armor",
    "Stormtroll Armor": "Stormtroll Armor",
    "Robe of Twilight": "Robe of Twilight",
    "Robe of Agony": "Robe of Agony",
    "Robe of Frostfire": "Robe of Frostfire",
    "Robe of Crystals": "Robe of Crystals",
    "Marksman Cap": "Marksman Cap",
    "Warlord Helm": "Warlord Helm",
    "Spirit Visor": "Spirit Visor",
    "Brain Hat": "Brain Hat",
    "Cannibal Mask": "Cannibal Mask",
    "Helm of the Host": "Helm of the Host",
    "Icy Chill Mask": "Icy Chill Mask",
    "Stone Mask": "Stone Mask",
    "Eye Helm": "Eye Helm",
    "Fire Helm": "Fire Helm",
    "Ice Helm": "Ice Helm",
    "Lightning Helm": "Lightning Helm",
    "Dark Helm": "Dark Helm",
    "Nature Helm": "Nature Helm",
    "Holy Helm": "Holy Helm",
    "Arcane Helm": "Arcane Helm",
    "Metallic Helm": "Metallic Helm",
    "Fire Frenzy Mask": "Fire Frenzy Mask",
    "Ice Frenzy Mask": "Ice Frenzy Mask",
    "Arcane Frenzy Mask": "Arcane Frenzy Mask",
    "Summer Crown": "Summer Crown",
    "Winter Crown": "Winter Crown",
    "Spring Crown": "Spring Crown",
    "Autumn Crown": "Autumn Crown",
    "Bloodspike Crown": "Bloodspike Crown",
    "Earthmeld Boots": "Earthmeld Boots",
    "Travellers Shoes": "Travellers Shoes",
    "Cantrip Clogs": "Cantrip Clogs",
    "Timestriders": "Timestriders",
    "Drill Shoes": "Drill Shoes",
    "Winged Shoes": "Winged Shoes",
    "Silken Sandals": "Silken Sandals",
    "Snow Shoes": "Snow Shoes",
    "Translocation Boots": "Translocation Boots",
    "Gnome Shoes": "Gnome Shoes",
    "Slime Shoes": "Slime Shoes",
    "Kobold Clogs": "Kobold Clogs",
    "Ogre Boots": "Ogre Boots",
    "Ghost Slippers": "Ghost Slippers",
    "Storm Boots": "Storm Boots",
    "Exploding Boots": "Exploding Boots",
    "Finger 6": "Finger 6",
    "Ankh": "Ankh",
    "Drakentooth": "Drakentooth",
    "Eye Rock Pendant": "Eye Rock Pendant",
    "Amber Cube": "Amber Cube",
    "Skull Necklace": "Skull Necklace",
    "Red Obsidian Shard": "Red Obsidian Shard",
    "Jade Shard": "Jade Shard",
    "Reality Anchor": "Reality Anchor",
    "Amulet of Undeath": "Amulet of Undeath",
    "Vial of Ambrosia": "Vial of Ambrosia",
    "Amulet of Emerald Flame": "Amulet of Emerald Flame",
    "Monkey Skull Amulet": "Monkey Skull Amulet",
    "Blood Ruby": "Blood Ruby",
    "Bramblethorn": "Bramblethorn",
    "Toadthorn": "Toadthorn",
    "Devilthorn": "Devilthorn",
    "Witch Whistle": "Witch Whistle",
    "Snowy Fursphere": "Snowy Fursphere",
    "Living Emberstone": "Living Emberstone",
    "Silken Links": "Silken Links",
    "Winter Links": "Winter Links",
    "Wrath Links": "Wrath Links",
    "Jar of Trollblood": "Jar of Trollblood",
    "Jar of Embers": "Jar of Embers",
    "Jar of Quicksilver": "Jar of Quicksilver",
    "Jar of Ectoplasm": "Jar of Ectoplasm",
    "Poison Pipe": "Poison Pipe",
    "Time Pipe": "Time Pipe",
    "Ink Pipe": "Ink Pipe",
    "Ice Pipe": "Ice Pipe",
    "Purple Curse Doll": "Purple Curse Doll",
    "Ugly Curse Doll": "Ugly Curse Doll",
    "Red Curse Doll": "Red Curse Doll",
}
