tags = {
    "physical": "物理",
    "fire": "火焰",
    "lightning": "闪电",
    "dark": "黑暗",
    "poison": "毒素",
    "holy": "神圣",
    "arcane": "奥术",
    "ice": "寒冰",
    "nature": "自然",
    "sorcery": "咒术",
    "conjuration": "召唤",
    "enchantment": "附魔",
    "word": "真言",
    "orb": "法球",
    "dragon": "龙",
    "translocation": "移形",
    "undead": "死灵",
    "elemental": "元素",
    "heal": "治疗",
    "acid": "酸化",
    "demon": "恶魔",
    "spider": "蜘蛛",
    "living": "活物",
    "construct": "构造体",
    "metallic": "金属",
    "eye": "眼",
    "glass": "玻璃",
    "chaos": "混沌",
    "blood": "鲜血",
    "tongue": "tongue", # ？
    "slime": "史莱姆",
    "shield": "护盾",
	# 下面的都没见过
    "buff_apply": "buff_apply",
    "debuff_apply": "debuff_apply",
    "shield_apply": "shield_apply",
    "shield_expire": "shield_expire",
    "sound_effect": "sound_effect",
    "leap": "leap",
    "arrow": "arrow",
    "petrification": "petrification",
    "glassification": "glassification",
    "immolate": "immolate",
    "thunderstrike": "thunderstrike",
    "armageddonblade": "armageddonblade",
    # 上面的都没见过
    "damage": "伤害",
    "range": "范围",
    "minion_health": "随从生命",
    "minion_damage": "随从伤害",
    "breath_damage": "吐息伤害",
    "minion_duration": "随从持续时间",
    "minion_range": "随从攻击范围",
    "duration": "持续时间",
    "max_charges": "最大充能",
    "radius": "半径",
    "num_summons": "召唤数量",
    "num_targets": "目标数量",
    "shields": "护盾",
    "shot_cooldown": "shot_cooldown", # TODO
    "strikechance": "打击概率",
    "cooldown": "冷却时间",
    "cascade_range": "弹射范围",
    "petrify": "石化",
    "petrified": "石化",
    "petrifies": "石化",
    "glassify": "玻璃化",
    "glassified": "玻璃化",
    "frozen": "冻结",
    "freezes": "冻结",
    "freeze": "冻结",
    "stunned": "眩晕",
    "stun": "眩晕",
    "stuns": "眩晕",
    "berserk": "狂暴",
    "poisoned": "中毒",
    "blind": "致盲",
    "blinded": "致盲",
    "quick_cast": "快速施放",
}

tags_format = {
    # upgrade attributes
    "damage": "%s 点伤害",
    "range": "%s 格",
    "minion_health": "%s 点生命",
    "minion_damage": "%s 点伤害",
    "breath_damage": "%s 点吐息伤害",
    "minion_duration": "%s 回合",
    "minion_range": "%s 格",
    "duration": "%s 个回合",
    "max_charges": "%s 点最大充能",
    "radius": "半径 %s 格",
    "num_summons": "%s 个",
    "num_targets": "%s 个",
    "shields": "%s 点护盾",
    "shot_cooldown": "%s 回合",
    "strikechance": "%s%% 概率",
    "cooldown": "%s 回合",
    "cascade_range": "%s 格弹射范围",

    # other
    "heal": "%s 点生命",
}

school_list = ["fire", "ice", "lightning", "nature", "dark", "holy", "arcane", "sorcery", "conjuration", "enchantment",]
schools = dict([(s, tags[s]) for s in school_list])

damage_type_list = ["physical", "fire", "lightning", "dark", "poison", "holy", "arcane", "ice",]
damage_tags = dict([(t, tags[t]) for t in damage_type_list])
tags_format.update(dict([(t, f"%s 点{tags[t]}伤害") for t in damage_type_list]))
tags_format.update(dict([(f"r_{t}", f"%s%% {tags[t]}抗性") for t in damage_type_list]))

clauses = {
    "channel": "这个法术至多可以引导 %s，引导持续的每个回合都会重复相同的效果",
}

spells = {
    "Death Bolt": "死亡之箭", # 这玩意明显是 neta 魔兽争霸里的黑暗之箭，但是那个是 black arrow
    "Fireball": "火球",
    "Icicle": "冰锥",
    "Lifedrain": "生命吸取",
    "Lightning Bolt": "闪电箭",
    "Magic Missile": "魔法飞弹",
    "Poison Sting": "毒刺",
    "Wolf": "召唤狼",
    "Annihilate": "湮灭",
    "Boiling Blood": "沸血术", # 其实倾向于避免用“之”，沸腾血液有什么不好的吗
    "Bone Spear": "骨矛",
    "Chaos Barrage": "混沌箭雨",
    "Devour Mind": "吞噬心灵",
    "Disperse": "驱散",
    "Dreamwalk": "白日梦行",
    "Eye of Fire": "火焰之眼",
    "Eye of Ice": "寒冰之眼",
    "Eye of Lightning": "闪电之眼",
    "Eye of Rage": "狂怒之眼",
    "Fan of Flames": "焰扇", # 黑暗之魂3
    "Freeze": "冰冻",
    "Goatia Offering": "邪祭羊首",
    "Healing Light": "治愈之光",
    "Heavenly Blast": "圣能迸发",
    "Hungry Maw": "饥饿饕魔", # dnd
    "Iceball": "冰球",
    "Immolate": "燔祭",
    "Invoke Savagery": "野性呼唤",
    "Magnetize": "磁化",
    "Melt": "熔化",
    "Mercurize": "汞化",
    "Moon Glaive": "月刃",
    "Petrify": "石化",
    "Plague of Undeath": "亡灵瘟疫", #亡灵天灾（（
    "Pyrostatic Pulse": "灼流脉冲",
    "Regeneration Aura": "再生光环",
    "Scourge": "天罚", 
    "Soul Swap": "灵魂换位",
    "Thunder Strike": "雷击",
    "Touch of Death": "死亡之触",
    "Toxic Spores": "毒性孢子",
    "Toxin Burst": "毒素爆发",
    "Aether Swap": "以太换位",
    "Arcane Orb": "奥术法球",
    "Basilisk Armor": "蛇王铠甲",
    "Blazerip": "炽裂术",
    "Blinding Light": "眩目之光",
    "Blink": "闪现",
    "Bloodshift": "血移",
    "Chain Lightning": "连锁闪电",
    "Choir of Angels": "天使唱诗班",
    "Darkness": "致暗术", # dnd二环塑能
    "Death Chill": "致死恶寒",
    "Devour Flesh": "吞噬血肉",
    "Dominate": "支配",
    "Earthen Sentinel": "大地哨兵",
    "Earthquake": "地震",
    "Flame Gate": "火焰之门", # 寒冰之墙
    "Frostfire Hydra": "霜火九头蛇", # 作为海德拉你不能移动是正常的吗？
    "Ghostball": "幽灵球",
    "Giant Bear": "召唤巨熊",
    "Glass Orb": "玻璃法球",
    "Holy Armor": "神圣铠甲",
    "Holy Fire": "圣火",
    "Ironize": "钢化", # 太难听了
    "Lightning Halo": "闪电光圈", # 唉，被砍成圆环的技能
    "Lightning Spire": "闪电尖塔",
    "Lumbriogenesis": "蚓团孳生",
    "Mystic Power": "神秘力量",
    "Mystic Vision": "神秘视野",
    "Nightmare Aura": "梦魇光环",
    "Plague of Filth": "污秽瘟疫",
    "Prison of Thorns": "荆棘囚笼",
    "Psychic Seedling": "灵能树苗",
    "Seal Fate": "命殒咒印",
    "Shrapnel Blast": "破片迸发",
    "Sight of Blood": "血腥视域",
    "Silver Spear": "银枪",
    "Suspend Mortality": "驻亡止朽",
    "Underworld Passage": "冥界通道",
    "Armageddon Blade": "末日之刃",
    "Blizzard": "暴风雪",
    "Blood Golem": "鲜血魔像",
    "Bone Barrage": "骸骨箭雨",
    "Burning Idol": "焚烬造像",
    "Call Seraph": "呼唤炽天使",
    "Carnival of Pain": "痛楚狂欢",
    "Combust Poison": "毒素燃爆",
    "Conductance": "导体化",
    "Death Cleave": "丧殁斩",
    "Dispersion Field": "驱散立场",
    "Drain Pulse": "汲精脉冲",
    "Essence Flux": "要素异变",
    "Fiery Tormentor": "灼炎折磨者",
    "Fire Drake": "火焰幼龙",
    "Flame Burst": "燎焰爆发",
    "Floating Eye": "召唤浮眼",
    "Ice Drake": "寒冰幼龙",
    "Ice Orb": "寒冰法球",
    "Ice Vortex": "寒冰漩涡",
    "Imp Swarm": "小鬼集群",
    "Lightning Form": "闪电形态",
    "Lightning Storm": "闪电风暴",
    "Mass Calcification": "群体钙化",
    "Orb Control": "法球控制",
    "Pain Mirror": "痛苦之镜",
    "Permanence": "法术持久",
    "Petrification Aura": "石化光环",
    "Purity": "净化",
    "Pyrostatic Curse": "灼流诅咒",
    "Searing Seal": "灼热印记",
    "Siege Golems": "攻城傀儡",
    "Siphon Shields": "虹吸护盾",
    "Stampede Form": "象群形态",
    "Storm Burst": "风暴爆发",
    "Storm Drake": "风暴幼龙",
    "The Restless Dead": "不息死者",
    "Vampiric Gaze": "吸血凝视",
    "Void Beam": "虚空光束",
    "Void Drake": "虚空幼龙",
    "Wall of Ice": "寒冰之墙",
    "Volcanic Eruption": "火山喷发",
    "Watcher Form": "监视者形态",
    "Wheel of Death": "死亡之轮",
    "Ball Lightning": "球状闪电",
    "Bloodflame": "血焰", # 难听
    "Blue Lion": "蓝狮",
    "Call Archon": "召唤执政官",
    "Cantrip Cascade": "小招倾泻",
    "Chill Wind": "凛冽寒风",
    "Death Shock": "死亡电击",
    "Fae Court": "仙灵庭院",
    "Flesh Fiend": "血肉恶魔",
    "Golden Skull": "黄金头骨",
    "Heavenly Idol": "天堂造像",
    "Ice Phoenix": "寒冰凤凰",
    "Mega Annihilate": "究极湮灭",
    "Night Hag": "夜魇老巫", # DND
    "Pillar of Fire": "火焰之柱",
    "Ring of Spiders": "蜘蛛之环",
    "Slime Form": "史莱姆形态",
    "Soul Tax": "灵魂税",
    "Spider Queen": "蜘蛛女皇",
    "Teleport": "传送",
    "Arc Lightning": "弧形闪电",
    "Dragon Roar": "龙吼",
    "Faehaunt Garden": "仙萦花园", # 没法直译
    "Flock of Eagles": "召唤鹰群",
    "Furnace of Sorcery": "咒术熔炉",
    "Gold Drake": "黄金幼龙",
    "Heaven's Wrath": "天堂之怒",
    "Knightly Oath": "骑士誓言",
    "Mystic Memory": "神秘记忆",
    "Searing Orb": "灼热法球",
    "Twilight Gaze": "暮光凝视",
    "Hatebolts": "恶业之箭",
    "Multicast": "多重施法",
    "Soul Wind": "灵魂之风",
    "Spikeball Factory": "钉球工厂",
    "Word of Beauty": "至善真言",
    "Word of Chaos": "混沌真言",
    "Word of Ice": "冰霜真言",
    "Word of Madness": "疯狂真言",
    "Word of Undeath": "不死真言", # 亡灵真言？
    "Wyrm Eggs": "妖蛆蛋",
    "Gates of Helheim": "赫尔海姆之门", # 所以 Aelf 到底是什么生物
    "Horde of Halfmen": "半人部族",
    "Rain of Fire": "火雨",
    "Ritual of Revelation": "启示仪式",
    "Summon Wizard": "召唤巫师",
}

skills = {
    "Arcane Accounting": "奥术账",
    "Arcane Combustion": "奥术爆燃",
    "Arcane Shield": "奥术护盾",
    "Bone Guard": "骸骨卫士",
    "Chaos Familiar": "混乱仆从",
    "Conjured Aggression": "造物强袭",
    "Conjured Vitality": "造物活力",
    "Crystal Power": "水晶之力",
    "Deathchill Familiar": "死寒仆从",
    "Faestone": "仙灵石",
    "Frostbite": "霜咬", # 图里有张嘴
    "Frozen Fragility": "低温脆化",
    "Glittering Dance": "闪光之舞",
    "Hibernation": "冬眠",
    "Holy Water": "圣水",
    "Houndlord": "猎犬领主",
    "Hungry Dead": "饥饿死者",
    "Lifespark Lantern": "生灵弧灯",
    "Lightning Warp": "闪电扭曲",
    "Master of Memories": "记忆大师",
    "Megavenom": "剧毒",
    "Melting Armor": "装甲熔毁",
    "Minion Regeneration": "随从再生",
    "Natural Healing": "自然回复",
    "Natural Vigour": "自然护身", # TODO
    "Paralyzing Venom": "麻痹性毒液",
    "Prince of Ruin": "毁灭王子",
    "Radiant Chill": "寒气逼人",
    "Shielded Minions": "盾护随从",
    "Silkshifter": "蛛网行者",
    "Spell Sniper": "法术狙击",
    "Spider Spawning": "蜘蛛孳生",
    "Stormbrood Tricksters": "风巢诡魔", # 召唤出来的巨魔会闪现术
    "Toadblood Transmutation": "蟾血嬗变",
    "Unholy Alliance": "不洁同盟",
    "Venom Spit": "毒液喷射",
    "Voidflame Lantern": "虚空燃灯",
    "Acid Fumes": "酸雾",
    "Armorer": "甲胄幻形", # TODO
    "Blood Anima": "鲜血灵体",
    "Blood Reaping": "鲜血收割",
    "Chaos Casting": "混沌施法",
    "Collected Agony": "苦痛集萃",
    "Demonic Cruelty": "恶魔残虐", # 这个真的好难听 TODO
    "Earthwrath": "大地之怒",
    "Fae Malevolence": "邪灵作祟", # TODO
    "Fiery Judgement": "炽焰审判",
    "Ghostfire": "鬼火",
    "Hemocorruption": "腐血污荼", # 因为只是有毒所以感觉还是污染好一点
    "Holy Thunder": "圣雷",
    "Hordemancer": "部族唤者", # TODO
    "Horror": "恐惧",
    "Hypocrisy": "伪善",
    "Master of Space": "空间大师",
    "Master of Time": "时间大师",
    "Multimancy": "法术霰映",
    "Necrostatics": "死灵静电", # TODO 想弄点弗兰肯斯坦进去
    "Purestrike": "纯洁打击",
    "Pyrophilia": "嗜火症",
    "Righteous March": "正义之师",
    "Scalefeather Egregore": "鳞羽集识体", # 鳞羽格式塔（？ 这个怪名字叫feathered serpent啊 就是羽蛇 （Egregore是群体意念聚集的灵体）
    "Searing Heat": "炎炎酷热",
    "Starfire": "星辰烈焰",
    "Thorn Garden": "荆棘花园",
    "Wordspeaker": "真言诵者", # 或者咏者？颂者？
    "Chastisement": "天惩", # 这个图标和 Scourge 一样啊，那都叫惩戒行吗（不行
    "Cracklevoid": "虚空霹雳",
    "Echomancer": "回声术士",
    "Ice Tap": "共振冰棱", # 冰坠子
    "Icy Vengeance": "冰霜复仇",
    "Inferno Engines": "炼狱引擎",
    "Lightning Frenzy": "闪电狂掣",
    "Moonspeaker": "颂月使",
    "Scalespinner": "鳞挣者",
    "Shatter Shards": "碎冰裂片",
    "Steam Anima": "蒸汽灵体",
    "Storm Caller": "呼唤风暴",
    "Arch Conjurer": "大召唤师",
    "Arch Enchanter": "大附魔师",
    "Arch Sorcerer": "大咒术师",
    "Blood Lord": "鲜血领主",
    "Chaos Poet": "混沌诗人",
    "Dark Lord": "黑暗领主",
    "Disintegrator": "解离术", # 解离术士？解离单元？魔力解离？感觉解离器听起来像个有实体的工具
    "Enchanters Boon": "附魔幻形", # TODO
    "Dragon Lord": "巨龙领主",
    "Fire Lord": "火焰领主",
    "Ice Lord": "冰霜领主",
    "Light Lord": "光明领主",
    "Metal Lord": "金属领主",
    "Nature Lord": "自然领主",
    "Orb Lord": "法球领主",
    "Scent of Blood": "血腥嗅迹",
    "Serpents of Chaos": "混沌之蛇",
    "Shock Value": "震魂撼魄", # 敌人死于雷电伤害使视线内敌人狂暴
    "Soul Harvest": "灵魂收割",
    "Thunder Lord": "雷霆领主",
    "Translocation Master": "传送大师",
    "Unblinking Eye": "不瞬之目",
    "Void Lord": "虚空领主",
    "Void Spikes": "虚空棘刺",
}

upgrades = {
    "Soul Battery": "灵魂电容",
    "Winter Bolt": "凛冬箭",
    "Chaos Skeletons": "混沌骷髅",
    "Chaos Ball": "混沌球",
    "Ash Ball": "灰烬球",
    "Meteor": "陨石",
    "Freezing": "霜冻冰锥",
    "Ice Spear": "冰枪",
    "Icicle Harvest": "回收冰锥",
    "Blood Bond": "鲜血分享",
    "Life Funnel": "生命虹吸",
    "Blindcasting": "无需视线",
    "Channeling": "引导施法",
    "Electric Ink": "电子墨",
    "Energy Bolt": "能量箭",
    "Shield Burn": "护盾焚除",
    "Disruption Bolt": "摧扰飞弹",
    "Arcane Crossfire": "奥术交火",
    "Ricochet": "跳弹",
    "Acidity": "腐蚀酸刺",
    "Silk Shot": "织丝钉刺",
    "Stinger Barrage": "密集钉刺",
    "Wolf Pack": "狼群",
    "Ice Hound": "寒冰猎犬",
    "Clay Hound": "黏土猎犬",
    "Cascade": "连锁",
    "Comprehensive Annihilation": "全面湮灭",
    "Doom Storm": "毁灭风暴",
    "Extra Damage": "额外伤害",
    "Duration": "持续回合",
    "Holy Fury": "神圣怒火",
    "Dark Fury": "黑暗怒火",
    "Infernal Spear": "狱火矛",
    "Toxic Spear": "迸毒矛",
    "Stun Spear": "眩晕一击",
    "Mega Barrage": "超级箭雨",
    "Shockwaves": "撼震波",
    "Smart Bolts": "智能射弹",
    "Huskification": "尸壳化",
    "Spirit Eater": "吞噬灵体",
    "Gluttony": "暴食",
    "Violent Warp": "暴力扭曲",
    "Protective Warp": "防护扭曲",
    "Eye of Fireballs": "火球之眼",
    "Fiery Onlooker": "火焰观者",
    "Eye of Conflaguration": "燎原之眼",
    "Frosty Onlooker": "寒霜观者",
    "Eye of Freezing": "冰结之眼",
    "Eye of Iceballs": "冰球之眼",
    "Archon Eye": "执政官之眼",
    "Eye of Thunderstrike": "雷击之眼",
    "Penetrating Gaze": "穿透凝视",
    "Lycanthropy": "狼人疫病",
    "Infectious Rage": "集群感染",
    "Burning Rage": "怒火中烧",
    "Healing Hearthfire": "治愈之炎",
    "Fan of Frostfire": "霜火扇",
    "Wildfire": "野火燎原",
    "Refreezing": "复冻",
    "Mass Freeze": "集群冻结",
    "Quickcast": "快速施法",
    "Reincarnation": "复生羊头",
    "Pain Aura": "痛苦光环",
    "Maggot Host": "蛆寄生",
    "Shielding Light": "庇护之光",
    "Purifying Light": "净化之光",
    "Heartflame": "心灵之火",
    "Spirit Bind": "圣罚魂缚",
    "Shield": "护盾",
    "Echo Heal": "圣愈回响",
    "Gnashing Teeth": "磨牙凿齿",
    "Invincible Maw": "无敌巨口",
    "Void Maw": "虚空巨口",
    "Cloud Combustion": "雪云装药",
    "Ice Crush": "冰屑破片",
    "Fae Ball": "冰仙球",
    "Conflaguration": "连锁焚烧",
    "Radiant Heat": "热辐射",
    "Dragon Soul": "龙魂觉醒",
    "Venomous Bite": "剧毒撕咬",
    "Savage Leap": "野蛮跃击",
    "Scavengers": "荒拾狼聚",
    "Radioactivity": "放射污染",
    "Electromagnetism": "磁场致电",
    "Liquid Magnetism": "流性磁导",
    "Mass Melt": "群体熔化",
    "Ice Penetration": "熔透寒冰",
    "White Flame": "白色火焰",
    "Morbidity": "恶毒金属",
    "Corrosion": "溶蚀",
    "Toxic Fumes": "毒瘴污染",
    "Mercurial Vengeance": "汞化恩返",
    "Glimmerblade": "辉渺光刃",
    "Electroblade": "带电刀锋",
    "Steelshaping": "钢刃幻形",
    "Glassify": "玻璃化",
    "Arcane Conductivity": "奥术传导",
    "Rocky Servitude": "岩化奴役",
    "Max Health Loss": "最大生命损伤",
    "Fire Vulnerability": "火焰易伤",
    "Plague of Undead": "亡者疫灾",
    "Chaos Pulse": "混沌脉冲",
    "Lesser Cascade": "低联散射",
    "Greater Cascade": "超级连锁",
    "Heal": "治疗量",
    "Global": "全图治疗",
    "Redemption": "救赎",
    "Conversion": "招降",
    "Mass Scourge": "集群天罚",
    "Forced Transfer": "强制易位", 
    "Max Charges": "充能上限",
    "Storm Power": "风暴蓄能",
    "Heaven Strike": "天堂雷击",
    "Flametouch": "火焰之触",
    "Touch of the Vampire": "吸血之触",
    "Touch of the Reaper": "死神之触",
    "Hand of Death": "死亡之手",
    "Num Summons": "召唤数量",
    "Grey Mushbooms": "致晕菌株",
    "Red Mushbooms": "赤燃菌株",
    "Glass Mushbooms": "玻璃菌株",
    "Herbal Remedy": "草药制备",
    "Withertoxin": "邪恶巫毒",
    "Toxin Bomber": "毒素炸弹",
    "Petrification": "石化光线",
    "Blazerip Orb": "炽裂法球",
    "Double Shot": "双重射击",
    "Orb Detonation": "法球激发",
    "Dual Blazerip": "双向炽裂",
    "Aether Poison": "以太之毒",
    "Blazebugs": "焱虫增殖",
    "Halting Light": "顿滞神光",
    "Searing Light": "烈焰神光",
    "Dissolution": "分散闪现",
    "Thunderblink": "雷霆闪现",
    "Radius": "半径",
    "Damage": "伤害",
    "Range": "射程",
    "Toxic Shift": "淬毒血移",  # Bloodshift 好理解，什么叫毒转移啊你告诉我
    "Chain Fireball": "连锁火球",
    "Cloud Conductance": "云层导电",
    "Lightning Shield": "闪电护盾",
    "Dual Angels": "双面天使",
    "Mercy": "圣光感化",
    "Massive Chorus": "天堂诗班",
    "Darkvision": "黑暗视觉",
    "Dark Clouds": "暗之死云",
    "Eternal Darkness": "永恒之暗",
    "Icy Necromancy": "亡灵冰术",
    "Slaughter Chill": "巫毒寒战",
    "Mass Death Chill": "灭绝寒潮",
    "Controlled Appetite": "节制吞噬",
    "Mass Feeding": "分摊治愈",
    "Charred Flesh": "焦焚仆役",
    "HP Threshold": "血量阈值",
    "Brute Force": "蛮力",
    "Undead Servitude": "不死奴役",
    "Earthquake Totem": "地震图腾",
    "Stinging Totem": "毒刺图腾",
    "Holy Totem": "神圣图腾",
    "Safety": "自然庇佑",
    "Aftershocks": "余震",
    "Magnitude 8.0": "震级8.0",
    "Burst Fire": "火焰爆发",
    "Eye Gate": "火瞳之门",
    "Starfire Gate": "星火之门",
    "Crystal Eyes Hydra": "晶眼九头蛇",
    "Freezing Ice": "急冻霜火",
    "Hydra Reclamation": "前仆后继",
    "Ghost King": "幽灵国王",
    "Ghost Mass": "幽灵畸团",
    "Metal Bear": "金属巨熊",
    "Venom Bear": "毒液巨熊",
    "Blood Bear": "血煞巨熊",
    "Petrification Orb": "石化法球",
    "Orb Shards": "法球破片",
    "Enchantment Refraction": "附魔折射",
    "Greater Armor": "改良装甲",
    "Crystal Armor": "水晶装甲",
    "Smiting Thorns": "荆棘护佑",
    "Holy Smite": "神怒一击",
    "Divine Blaze": "神性炽裂",
    "Heaven Call": "天堂号令",
    "Armor Plating": "装甲镀层",
    "Permanent Transmutation": "永续",
    "Arcane Insulation": "奥术绝缘",
    "Ring of Fire": "火焰之环",
    "Radioactive Field": "辐射场",
    "Lightning Nova": "闪电新星",
    "Mass Blasting": "集群迸射",
    "Wall Penetration": "穿墙电击",
    "Resistance Penetration": "抗性渗蚀",
    "Toxogenesis": "毒素生物",
    "Mechanogenesis": "械化生物",
    "Ectogenesis": "幽质生物",
    "Damage Bonus": "伤害增益",
    "Intensity": "强度",
    "Bonus": "增益",
    "Vision Aura": "视野光环",
    "Dark Dream": "黑暗梦境",
    "Electric Dream": "电气梦境",
    "Fever Dream": "狂热梦境",
    "Minion Duration": "随从持续时间",
    "Serpent Plague": "蛇瘟",
    "Minion Damage": "随从伤害",
    "Minion Health": "随从生命",
    "Iron Prison": "钢铁囚笼",
    "Icy Prison": "寒冰囚笼",
    "Psychic Fields": "灵能域界",
    "Immortal Forest": "不朽瑶林",
    "Parasitic Growth": "槲寄生",
    "Spreading Curse": "散播诅咒",
    "Genocide": "灭绝术",
    "More Shrapnel": "更多破片",
    "Puncturing Blast": "穿刺爆破",
    "Magnetized Shards": "磁性破片",
    "Demon Frenzy": "恶魔狂热",
    "Copper Shaft": "铜轴枪",
    "Consecration": "银枪祝圣",
    "Endlessness": "无朽无尽",
    "Mass Immortaity": "不朽集群",
    "Twilight Essence": "暮光精华",
    "Tremorsensitivity": "震动感应",
    "Armor of Armageddon": "终末装甲",
    "Mass Armaments": "连锁湮灭",
    "Mega Armageddon": "最终决战",
    "Flash Freeze": "闪冻",
    "Hailstorm": "坠冰风暴",
    "Snow Feathers": "雪绒天羽",
    "Greater Thorns": "锋锐荆棘",
    "Vampire Golem": "吸血魔像",
    "Bone Spears": "白骨矛箭",
    "Cursed Bones": "诅咒之骨",
    "Bone Explosion": "骸骨爆碎",
    "Archon Beam": "执政官光束",
    "Moonblade": "月光之刃",
    "Heal Aura": "治愈光环",
    "Holy Fire Aura": "圣火光环",
    "Lifesteal": "生命窃取",
    "Death Power": "丧殁亡能",
    "Torment": "无尽折磨",
    "Paralyzing Combustion": "瘫痪燃荼",
    "Flame Rave": "烈火狂潮",
    "Toxic Embers": "剧毒余烬",
    "Multicopy": "多重拷贝",
    "Resistance Debuff": "抗性削弱",
    "Num Targets": "目标数量",
    "Felomancy": "孽孳猫妖",
    "Ursomancy": "血塑熊煞",
    "Frostfire Tormentor": "霜火折磨者",
    "Metallic Tormentor": "金属折磨者",
    "Tormenting Mass": "折磨者畸团",
    "Broodlings": "幼体增殖",
    "Metal Dragon": "金属巨龙",
    "Dragon Mage": "龙法师",
    "Melting Flame": "熔融烈焰",
    "Bright Flame": "光之焰",
    "Spreading Flame": "席卷烈焰",
    "Stone Gaze": "石化凝视",
    "Eyemage": "魔眼法师",
    "Regenerating Shields": "护盾再生",
    "Dracolich": "龙巫妖",
    "Frostgleam": "寒冻闪爆",
    "Faebound Orb": "冰蕴法球",
    "Blizzard Orb": "暴雪法球",
    "Metal Swarm": "金属魔潮",
    "Dark Swarm": "黑暗魔潮",
    "Endless Swarm": "无尽魔潮",
    "Lingering Form": "残影形态",
    "Fire Form": "火焰形态",
    "Crackling Aura": "电鸣光环",
    "Particle Storm": "粒子风暴",
    "Lightning Star": "闪电连星",
    "Spirit Harvest": "灵体收割",
    "Fae Bones": "仙化亡骨",
    "Burning Bones": "燃烧亡骨",
    "Bone Shards": "碎骨破片",
    "Flesh Harvest": "血肉狂欢",
    "Dulled Pain": "痛感钝化",
    "Burning Pain": "蚀骨之火",
    "Crumbling Aura": "崩碎光环",
    "Wormification Aura": "岩蠕光环",
    "Resistance Melting": "外壳熔解",
    "Linear Conductance": "线性传导",
    "Pyrostatic Chaos": "灼流混沌",
    "Slow Burn": "噬体之焰",
    "Chaos Seal": "混沌咒印",
    "Fire Harvest": "火焰收割",
    "Assistant Cannoneers": "助理炮兵",
    "Recycling": "回收",
    "Chaos Cannon": "混沌加农",
    "Shield Steal": "护盾窃取",
    "Fae Stampede": "仙灵象群",
    "Burning Stampede": "燃烧象群",
    "Metal Stampede": "金属象群",
    "Stormshield": "风暴护盾",
    "Dual Nova": "双重星爆",
    "Spirit Nova": "唤灵星爆",
    "Storm Summoning": "风暴召唤",
    "Ghost Drake": "幽灵巨龙",
    "Drake Swap": "巨龙换位",
    "Junk Golems": "废品傀儡",
    "Elemental Spirits": "元素精魂",
    "Restless Minions": "无休战仆",
    "Toxic Gaze": "毒性凝视",
    "Vampiric Tax": "吸血税",
    "Refracting Gaze": "目光折射",
    "Void Binding": "虚空之缚",
    "Star Beam": "星火射线",
    "Voidcurse": "虚空诅咒",
    "Shields": "护盾",
    "Essence Drake": "龙之灵粹",
    "Flow Range": "喷发范围",
    "Wallcano": "火“山”",
    "Hungry Wall": "饥饿冰墙",
    "Fae Wall": "仙灵祝福",
    "Endless Wall": "无尽冰墙",
    "Pyrostatic Watcher Form": "灼流监视者",
    "Void Watcher Form": "虚空监视者",
    "Chain Watcher Form": "电链监视者",
    "Cheat Fate": "命运欺谑",
    "Final Burst": "终焉迸发",
    "Drakebirth": "雷龙幻生",
    "Pyrostatics": "高温静电",
    "Holy Bolt": "神圣之箭",
    "Shimmermane": "微光狮鬃",
    "Burning Lion": "烈焰蓝狮",
    "Heal Beam": "至于光束",
    "Beam Arc": "电弧集束",
    "Storm Archon": "冰暴军团",
    "Cantrip Burst": "定点爆破",
    "Orb Cascade": "法球共鸣",
    "Evocation Amalgamation": "混联施法",
    "Ice Guardians": "寒冰守卫",
    "Dual Wind": "双面驶风",
    "Arcane Storm": "奥术风暴",
    "Fire Shock": "火焰电击",
    "Corpse Construct": "尸体重组",
    "Winter Faery": "冬日精灵",
    "Summon Queen": "召唤女皇",
    "Glass Faery": "玻璃精灵",
    "Belly Flop": "肚皮冲撞",
    "Barbeque Fiends": "烧烤恶魔",
    "Worm Lord": "蠕虫领主",
    "Ghost Caller": "唤鬼者",
    "Bone Wheel": "白骨之轮",
    "Blood Skull": "血头骨",
    "Fire Gaze": "烈焰之眼",
    "Shield Gaze": "屏护之眼",
    "Bastion of Immortality": "不朽壁垒",
    "Reincarnations": "转世轮回",
    "Ice Aura": "冰霜光环",
    "Dark Annihilation": "黑暗湮灭",
    "Arcane Annihilation": "奥术湮灭",
    "Spear Hag": "骨矛女巫",
    "Nightmare Hag": "梦魇女巫",
    "Bone Queen": "骸骨女王",
    "Disrupting Flames": "摧扰烈焰",
    "Pillar of Annihilation": "湮灭之柱",
    "Turbo Toxin": "毒网",
    "Long Webs": "巨网",
    "Aether Spiders": "以太蜘蛛",
    "Fire Slime": "烈焰史莱姆",
    "Ice Slime": "寒冰史莱姆",
    "Void Slime": "虚空史莱姆",
    "Arcane Taxation": "奥术苛税",
    "Insta Tax": "即时税",
    "Mass Taxation": "群体征收",
    "Aether Queen": "以太蛛后",
    "Steel Queen": "钢铁蛛后",
    "Vampire Queen": "血族蛛后",
    "Group Teleport": "群体传送",
    "Void Teleport": "虚空传送",
    "Proton Storm": "质子风暴",
    "Enervation": "治愈电弧",
    "Multi Flash": "多重火花",
    "Draconic Vitality": "巨龙生机",
    "Draconic Vigor": "巨龙精元",
    "Draconic Majesty": "巨龙威严",
    "Guardian Gnomes": "地精守卫",
    "Fae Flies": "仙化飞蝇",
    "Glass Garden": "玻璃花园",
    "Army of Eagles": "猎鹰军团",
    "Shielded Eagles": "猎鹰庇甲",
    "Thunder Claw": "雷霆之爪",
    "Untouchable Majesty": "上兽之威",
    "Flames of Sorcery": "咒术炉焰",
    "Imp Smithy": "青铜仲魔",
    "Arcane Eyebolts": "奥术瞳矢",
    "Dragon Saint": "圣龙天威",
    "Immortal Dragon": "不朽金龙",
    "Culling": "抹除",
    "Halt Heretics": "异寇惩滞",
    "Fiery Wrath": "圣光烈焰",
    "Void Court": "虚空王朝",
    "Storm Court": "暴风王朝",
    "Chaos Court": "混沌王朝",
    "Distant Memory": "久远回忆",
    "Deep Reflection": "深度回想",
    "Shield of Memories": "记忆护盾",
    "Explosive Orb": "爆炸过载",
    "Matter Melting": "无坚不熔",
    "Flame Rift": "火焰裂隙",
    "Arcane Gaze": "奥术凝视",
    "Boomerang": "回返弩矢",
    "Toxic Hatred": "淬毒之憎",
    "Torment Harvest": "煎熬收割",
    "Copies": "复制数量", # Multicast 的升级
    "Ensoulment": "赋魂",
    "Arcane Wind": "奥法之风",
    "Defense System": "自卫系统",
    "Manufactory": "批量生产",
    "Copper Spikeballs": "铜质钉球",
    "Beauty of Steel": "缮钢美德",
    "Shield Strip": "护盾剥离",
    "Echoing Beauty": "美德回响",
    "Animated Chaos": "混沌魂涌",
    "Chaos Gifts": "混沌恩赐",
    "Echoing Chaos": "混沌回响",
    "Echoing Ice": "冰之回响",
    "Endless Ice": "无尽寒冰",
    "Word of Wind": "寒风真言",
    "Selective Madness": "择敌致疯",
    "Echoing Madness": "妄语回响",
    "Guardians of Madness": "疯诞护卫",
    "Hatred of Life": "亡者之憎",
    "Spirit Gift": "精魂馈赠",
    "Spirit of Lichdom": "巫魂涌现",
    "Magic Eggs": "魔法蛋",
    "Radiant Eggs": "放射性龙蛋",
    "Scale Harvest": "鳞片回收", # 回收总比收获好点
    "Aelf Horde": "精灵部族",
    "Fae Aelves": "仙化精灵", # 怎么着都要重一个字是吧
    "Elite Aelves": "精英精灵",
    "Trollblooded Halfmen": "巨魔亚种",
    "Metallic Halfmen": "全金属化",
    "Burning Halfmen": "烈焰血统",
    "Chaos Storm": "混沌风暴",
    "Rain of Dragons": "龙火技艺",
    "Pyrostatic Storm": "流星掣电",
    "Holy Horde": "神圣部族",
    "Blasphemy": "亵渎仪式",
    "Arcane Revelation": "奥能绽放",
    "Clay Wizard": "黏土秘术",
    "Ghost Wizard": "幽灵巫师",
    "Wizard Gang": "战法小队",
}

consumables = {
    "Healing Potion": "治疗药水",
    "Mana Potion": "法力药水",
    "Teleporter": "传送器",
    "Golden Stopwatch": "金质怀表",
    "Chaos Bell": "混乱之铃",
    "Death Dice": "死亡骰子",
    "Portal Key": "传送钥匙",
    "Earthquake Orb": "地震法球",
    "Oculus": "天眼",
    "Aether Dagger": "以太匕首",
    "Bag of Spikes": "钉球袋",
    "Orb of Corruption": "腐化法球",
}

ring_tags = {
    "Fiery": "炽焰",
    "Icy": "寒冰",
    "Electric": "电气",
    "Living": "生灵",
    "Sinister": "邪冥",
    "Golden": "黄金",
    "Mystic": "神秘",
    "Sorcerous": "咒术",
    "Enchanting": "附魔",
    "Conjured": "召唤",
}

ring_stats = {
    "Dagger": "匕首",
    "Orb": "法球",
    "Tome": "典籍",
    "Lens": "眼镜",
    "Flag": "旗帜",
    "Disk": "圆盘", # 说实话这是啥，图看着真像块光盘，但是认真的吗
    "Scale": "鳞片",
    "Claw": "爪刀",
    "Fang": "尖牙",
    "Hourglass": "沙漏",
    "Horn": "号角",
}

shrines = {
    "Ruby Heart": "红宝心",
    "Exotic Pet Shop": "珍稀宠物商店",
    "Scroll of Spells": "法术卷轴",
    "Treasure Chest": "宝物箱",
    "Sigil Chest": "召唤法印箱", # TODO
    "Box of Wizard Caps": "巫师帽盒",
    "Hat Chest": "帽子箱",
    "Staff Chest": "法杖箱",
    "Shoe Box": "鞋盒",
    "Armor Chest": "盔甲箱",
    "Trinket Box": "饰品盒",
    "Scroll of Skills": "技能卷轴",
}
for k, v in ring_tags.items():
    name = "%s Trinket Chest" % k
    shrines[name] = "%s饰品箱" % v
for k, v in ring_stats.items():
    name = "%s Chest" % k
    shrines[name] = "%s箱" % v

equipments = {
    "The Bladestaff": "利刃法杖",
    "Geometer's Staff": "制图师法杖",
    "Memory Staff": "记忆法杖",
    "Banner of the Horde": "部族旗帜",
    "Storm Oculus": "风暴瞳槊",
    "Void Oculus": "虚空瞳槊",
    "Pyrostatic Oculus": "灼流瞳槊",
    "Twilight Oculus": "暮光瞳槊",
    "Crystal Oculus": "水晶瞳槊",
    "Purity Oculus": "圣洁瞳槊",
    "Arcane Amplifier": "奥术增魔杖",
    "The Flamenweaver": "织焰者",
    "Treelord Staff": "树领主之杖",
    "Aetherlord Staff": "以太领主杖",
    "Filthlord Staff": "污秽领主杖",
    "Flaming Claw Staff": "火爪法杖",
    "Icy Claw Staff": "冰爪法杖",
    "Scepter of Mischief": "整蛊权杖",
    "Drakenstaff": "龙之杖",
    "The Purifier": "净化者",
    "Silvermelt": "熔银杖",
    "Sorcwinter": "唤咒寒冬",
    "The Dynamo": "湮能发生器",
    "The Blazeloom": "炽裂织者",
    "Starblesser": "星祈者",
    "The Sparkloom": "雳闪织者",
    "Wintersting": "寒冬之蜇",
    "Red Majesty": "赤红威严",
    "Blastmaker": "布雷者",
    "Embermaker": "余烬升萤者",
    "Mantismaker": "唤螳者",
    "Sprigganmaker": "蔓灵点化者",
    "Impmaker": "小鬼召唤者",
    "Crackledarkener": "黯然霹雳",
    "Scepter of Sorrows": "凄寒权杖",
    "Glassy Fae Staff": "玻璃仙灵法杖",
    "Quill Staff": "翎笔法杖",
    "Robe of Ice": "冰霜法袍",
    "Robe of Fire": "火焰法袍",
    "Robe of Void": "虚空法袍",
    "Robe of Storms": "风暴法袍",
    "Robe of the Druids": "德鲁伊法袍",
    "Fae Plate": "仙灵板甲",
    "Vampiric Vestments": "吸血背心",
    "Dwarven Chainmail": "矮人链甲",
    "Elven Chainmail": "精灵链甲", #？
    "Soulmail": "魂甲",
    "Basilisk Scale Armor": "石化鳞甲",
    "Earthtroll Armor": "大地巨魔铠甲",
    "Stormtroll Armor": "风暴巨魔铠甲",
    "Robe of Twilight": "暮光法袍",
    "Robe of Agony": "苦痛法袍",
    "Robe of Frostfire": "霜火法袍",
    "Robe of Crystals": "水晶法袍",
    "Marksman Cap": "射手帽",
    "Warlord Helm": "军阀头盔", # TODO
    "Spirit Visor": "精魂面甲",
    "Brain Hat": "头脑帽",
    "Cannibal Mask": "食人魔假面", # 怎么表达同类相食的感觉
    "Helm of the Host": "宿主头盔",
    "Icy Chill Mask": "凛冽寒面",
    "Stone Mask": "岩石假面",
    "Eye Helm": "魔眼头盔",
    "Fire Helm": "烈焰头盔",
    "Ice Helm": "寒冰头盔",
    "Lightning Helm": "雷电头盔",
    "Dark Helm": "黑暗头盔",
    "Nature Helm": "自然头盔",
    "Holy Helm": "神圣头盔",
    "Arcane Helm": "奥术头盔",
    "Metallic Helm": "金属头盔",
    "Fire Frenzy Mask": "烈焰狂面",
    "Ice Frenzy Mask": "寒冰狂面",
    "Arcane Frenzy Mask": "奥术狂面",
    "Summer Crown": "夏季皇冠",
    "Winter Crown": "冬季皇冠",
    "Spring Crown": "春季皇冠",
    "Autumn Crown": "秋季皇冠",
    "Bloodspike Crown": "血棘之冠",
    "Earthmeld Boots": "凝壤之靴",
    "Travellers Shoes": "冒险者之履",
    "Cantrip Clogs": "戏法木屐",
    "Timestriders": "时空瞬行者",
    "Drill Shoes": "钻头鞋",
    "Winged Shoes": "飞翼鞋",
    "Silken Sandals": "蚕丝凉鞋",
    "Snow Shoes": "冰霜鞋",
    "Translocation Boots": "易位靴",
    "Gnome Shoes": "地精鞋",
    "Slime Shoes": "史莱姆鞋",
    "Kobold Clogs": "狗头人木屐",
    "Ogre Boots": "食人魔之靴",
    "Ghost Slippers": "幽灵拖鞋",
    "Storm Boots": "风暴靴",
    "Exploding Boots": "炎爆靴",
    "Finger 6": "第六指",
    "Ankh": "安卡十字架",
    "Drakentooth": "龙牙",
    "Eye Rock Pendant": "岩目吊坠",
    "Amber Cube": "琥珀立方",
    "Skull Necklace": "头骨项链",
    "Red Obsidian Shard": "红曜岩碎片",
    "Jade Shard": "青玉碎片",
    "Reality Anchor": "现实驻锚",
    "Amulet of Undeath": "亡灵护符",
    "Vial of Ambrosia": "仙果瓿",
    "Amulet of Emerald Flame": "翡翠焰护符",
    "Monkey Skull Amulet": "猴头骨护符",
    "Blood Ruby": "血红宝石",
    "Bramblethorn": "棘刺",
    "Toadthorn": "毒蟾棘刺",
    "Devilthorn": "恶魔棘刺",
    "Witch Whistle": "唤巫哨",
    "Snowy Fursphere": "覆雪毛球",
    "Living Emberstone": "活体余烬岩",
    "Silken Links": "蚕丝锁链",
    "Winter Links": "凛冬锁链",
    "Wrath Links": "盛怒锁链",
    "Jar of Trollblood": "巨魔血坛子",
    "Jar of Embers": "余烬坛子",
    "Jar of Quicksilver": "水银坛子",
    "Jar of Ectoplasm": "灵质坛子",
    "Poison Pipe": "毒素吹箭",
    "Time Pipe": "时光吹箭",
    "Ink Pipe": "墨汁吹箭",
    "Ice Pipe": "冰霜吹箭",
    "Purple Curse Doll": "紫色巫蛊偶",
    "Ugly Curse Doll": "丑陋巫蛊偶",
    "Red Curse Doll": "红色巫蛊偶",
}
for k, v in ring_tags.items():
    for k2, v2 in ring_stats.items():
        name = "%s %s" % (k, k2)
        equipments[name] = "%s %s" % (v, v2)
for k, v in schools.items():
    name = "%s Wand" % k
    equipments[name] = "%s魔杖" % v
for k,v in damage_tags.items():
    name = "%s Shield" % k
    equipments[name] = "%s护盾" % v

monsters = {
    "Goblin": "哥布林",
    "Bat": "蝙蝠",
    "Void Bomber": "虚空炸弹",
    "Fire Bomber": "火焰炸弹",
    "Fire Imp": "火焰小鬼",
    "Spark Imp": "电光小鬼",
    "Mind Maggot": "心灵蛆虫",
    "Displacer Beast": "移形兽",
    "Green Mushboom": "绿蘑菇",
    "Mantis": "螳螂",
    "Snake": "蛇",
    "Spriggan": "蔓妖", # 待议
    "Spriggan Bush": "蔓妖灌木丛",
    "Boggart": "波伽",
    "Orc": "兽人",
    "Pachyderm": "大象",
    "Rotting Zombie": "腐烂僵尸",
    "Ghost": "幽灵",
    "Iron Imp": "铁小鬼",
    "Satyr": "萨堤尔", # 潘神的追随者 萨堤尔/萨特
    "Large Worm Ball": "大型蠕虫球",
    "Kobold": "狗头人",
    "Witch": "女巫",
    "Rock Worm": "岩石蠕虫",
    "Giant Spider": "巨型蜘蛛",
    "Ice Lizard": "冰蜥蜴",
    "Fire Lizard": "火蜥蜴",
    "Grey Mushboom": "灰蘑菇",
    "Horned Toad": "角蟾",
    "Raven": "乌鸦",
    "Treant": "树妖",
    "Cursed Cat": "被诅咒的猫",
    "Cultist": "邪教徒",
    "Two Headed Snake": "双头蛇",
    "Centaur": "半人马",
    "Ogre": "食人魔",
    "Spore Beast": "孢子兽",
    "Bag of Bugs": "虫子袋", # 袋子自己有行动能力
    "Troll": "巨魔",
    "Troubler": "麻烦精", # 待议
    "Evil Faery": "邪恶仙灵",
    "Vampire": "吸血鬼",
    "Vampire Bat": "吸血蝙蝠",
    "Gnome": "地精", # 侏儒地精哥布林傻傻分不清
    "Goatia": "羊头邪祟", # 难听
    "Steel Spider": "钢铁蜘蛛",
    "Green Slime": "绿史莱姆",
    "Polar Bear": "北极熊",
    "Hell Hound": "地狱猎犬",
    "Werewolf": "狼人",
    "Wild Man": "野人",
    "Blizzard Beast": "暴风雪兽",
    "Chaos Chimera": "混沌奇美拉",
    "Fire Lion": "火狮",
    "Mycobeast": "真菌兽", # Myco-前缀表示和真菌有关
    "Thunderbird": "雷鸟",
    "Bone Knight": "骸骨骑士",
    "Blood Hound": "血煞猎犬",
    "Spark Spirit": "电光精魂", # 不想叫电光之灵，更不能叫火花之灵
    "Fire Spirit": "火焰精魂",
    "Golem": "魔像",
    "Redcap": "红帽子",
    "Green Gorgon": "绿戈尔贡", # 这玩意不会石化啊，而且也不是人形，它是啥
    "Earth Troll": "大地巨魔",
    "Stonefish": "石鱼", # 鱼，石头做的，还有腿
    "Dancing Blade": "舞动锋刃",
    "Fire Belcher": "火喷吐者", # 升级版蜥蜴
    "Aether Spider": "以太蜘蛛",
    "Spike Beast": "钉刺兽",
    "Old Witch": "老女巫",
    "Red Slime": "红史莱姆",
    "Ice Slime": "冰史莱姆",
    "Blood Bear": "血煞熊",
    "Living Scroll of Lightning": "活体闪电卷轴",
    "Living Scroll of Fireball": "活体火球卷轴",
    "Duergar": "灰矮人",
    "Fiery Tormentor": "烈焰折磨者",
    "Dark Tormentor": "黑暗折磨者",
    "Orc Houndlord": "兽人驯犬师",
    "Warlock": "典狱长", # 战锁，这个效果是招 imp 群然后点化 fiend
    "Void Rift": "虚空裂隙",
    "Flame Rift": "燃烧裂隙", # Flame 换个词吧
    "Rolling Spike Ball": "滚动钉球",
    "Floating Eyeball": "飘浮眼球",
    "Storm Drake": "风暴幼龙",
    "Fire Drake": "火焰巨龙",
    "Bone Shambler": "骸骨跛行者",
    "Worm Shambler": "蠕虫跛行者",
    "Greater Spore Beast": "大孢子兽",
    "Displacer Broodmother": "移形兽母",
    "Mind Maggot Queen": "心灵蛆虫女王",
    "Flame Toad": "烈焰蟾蜍",
    "Void Toad": "虚空蟾蜍",
    "Storm Troll": "风暴巨魔",
    "Minotaur": "牛头人",
    "Greater Vampire": "大吸血鬼",
    "Vampiric Mist": "吸血迷雾",
    "Aelf": "冥灵",
    "Ghostly Mass": "幽灵畸团",
    "Faery Arcanist": "仙灵奥术师",
    "Purple Hand": "紫手",
    "Star Swimmer": "星涌者", # 是个海星
    "Towering Toadbeast": "高大蟾蜍",
    "Deathchill Chimera": "死寒奇美拉",
    "Ice Lion": "冰狮",
    "Glass Golem": "玻璃魔像",
    "Ice Belcher": "冰喷吐者",
    "Bark Lord": "树皮领主", # 长得很丑的一棵树
    "Starfire Chimera": "星火奇美拉",
    "Star Lion": "星狮", #是不是有点怪了 TODO
    "Mind Vampire": "心灵吸血鬼",
    "Vampire Eye": "血族翼眼",
    "False Prophet": "伪缪先知",
    "Mind Devourer": "心灵吞噬者",
    "Fire Wyrm": "火焰妖蛆", # ……
    "Gargoyle": "石像鬼",
    "Gargoyle Statue": "石像鬼雕塑",
    "Void Slime": "虚空史莱姆",
    "Night Hag": "夜魇老巫", # DND
    "Red Cyclops": "红色独眼魔",
    "Giant Floating Skull": "巨大飘浮头骨",
    "Grey Gorgon": "灰戈尔贡",
    "Efreet": "火魉", # 关键词：火焰、烟雾、精怪、阿拉伯
    "Purple Pachyderm": "紫色大象",
    "Yeti": "雪人",
    "Void Drake": "虚空幼龙",
    "Cockatrice": "鸡蛇兽",
    "Butterfly Demon": "蝴蝶恶魔",
    "Chaos Knight": "混沌骑士",
    "Gold Drake": "黄金巨龙",
    "Flaming Eyeball": "燃烧眼球",
    "Frosty Tormentor": "霜冻折磨者",
    "Giant Spider Queen": "巨大蜘蛛女王",
    "Rotting Mass": "腐尸畸团",
    "Dryder": "蛛化精灵", # dnd，其实是蛛化卓尔精灵
    "Dream Hag": "寐祟老巫", # 不知道怎么和 Night Hag 协调
    "Ice Drake": "寒冰巨龙",
    "Ice Wyrm": "寒冰游龙", # ……
    "Fire Fiend": "火焰恶魔",
    "Storm Fiend": "风暴恶魔",
    "Iron Fiend": "铁质恶魔",
    "Annihilation Goo": "湮灭黏质", # 什么是 Goo？？有史莱姆词条，有嘴，有不知道是触角还是眼睛
    "Lich": "巫妖",
    "Aelf Lightning Artist": "冥灵雷术师",
    "Fae Queen": "仙灵女王",
    "Towering Bone Shambler": "高大骸骨跛行者",
    "Void Knight": "虚空骑士",
    "Storm Knight": "风暴骑士",
    "Nightmare Turtle": "梦魇龟",
    "Lamasu": "拉马苏",
    "Glass Cockatrice": "玻璃鸡蛇兽",
    "Glass Butterfly": "玻璃蝴蝶",
    "Giant Flaming Skull": "巨大燃烧头骨",
    "Phoenix": "凤凰",
    "Steel Spider Queen": "钢铁蜘蛛女王",
    "Aether Spider Queen": "以太蜘蛛女王",
    "Volcano Turtle": "火山龟",
    "Dracolich": "龙巫妖",
    "Aesir": "亚萨神族", # 亚萨神？
    "Titan": "泰坦",
    "Reaper": "收割者",
    "Mass of Eyes": "眼球畸团",
    "Fleshy Mass": "血肉集群", # 这个贴图和属性都和巫师招的flesh fiend完全一样
    "Chaos Fiend": "混沌恶魔",
    "Copper Fiend": "铜质恶魔",
    "Furnace Fiend": "熔炉恶魔",
    "Insanity Fiend": "狂乱恶魔",
    "Rot Fiend": "腐烂恶魔",
    "Ash Fiend": "灰烬恶魔",
    "Bone Shambler Megalith": "庞大骸骨跛行者",
    "Golden Skull": "金色颅骨",
    "Energy Knight": "能量骑士",
    "Twilight Knight": "暮光骑士",
    "Watcher": "监视者",
    "Void Watcher": "虚空监视者",
    "Idol of Undeath": "亡灵造像",
    "Fountain of Blood": "鲜血之泉",
    "Fountain of Venom": "毒液之泉",
    "Idol of Insanity": "狂乱造像",
    "Slimesoul Idol": "史莱姆造像",
    "Idol of Agony": "苦痛造像",
    "Idol of Frailty": "脆弱造像",
    "Idol of Nightmares": "梦魇造像",
    "Idol of Invincibiity": "无敌造像", # 要不还是叫护盾吧，有什么两个字的词描述无法摧毁的
    "Idol of Fiends": "恶魔造像",
    "Medusa": "美杜莎",
    "Bat Dragon": "蝙蝠龙",
    "Tombstone": "石墓", # TODO
    "Yggdrasil": "世界树",
    "Idol of Sorcery": "咒术造像",
    "Time Keeper": "驻时者",
    "Giant Soul Jar": "巨型魂匣",
    "Swamp Queen": "沼泽女王",
    "Chaos Quill": "混沌魔笔",
    "Fire Wyrm Egg": "火焰妖蛆蛋",
    "Ice Wyrm Egg": "寒冰妖蛆蛋",
    "Box of Woe": "祟灵魔匣", #魔盒？一代叫悲哀盒感觉不太对
    "Bone Wizard": "骸骨巫师",
    "Avian Wizard": "禽鸟巫师", # TODO
    "Raven Mage": "乌鸦法师",
    "Lightning Master": "闪电大师",
    "Mountain Mage": "山峦法师",
    "Masked Wizard": "蒙面巫师",
    "Arachnid Wizard": "蜘蛛巫师", # TODO
    "Dragon Mage": "龙巫师",
    "Troll Geomancer": "巨魔地术师",
    "Void Magus": "Void Magus", # TODO
    "Glass Master": "玻璃大师",
    "Grand Warlock": "Grand Warlock", # TODO
    "Twilight Seer": "暮光先知",
    "Ice Lich": "冰巫妖",
    "Fire Lich": "火巫妖",
    "Ice Wizard": "寒冰巫师",
    "Goblin Wizard": "哥布林巫师",
    "Frostfire Mage": "霜火巫师",
    "Starfire Sorcerer": "星火巫师", # 全部都是巫师（
    "Fire Wizard": "火焰巫师",
    "Enchanter": "附魔师",
    "Troubling Mass": "麻烦精畸团", # TODO
    "Vampire Count": "吸血鬼伯爵", # Count是伯爵
    "Black Rider": "黑骑 饥荒", # 或者黑之骑士，感觉又很中二
    "White Rider": "白骑 瘟疫",
    "Red Rider": "红骑 战争",
    "Pale Rider": "青骑 瘟疫",
    "The Furnace": "熔炉",
    "Pillar of Bones": "骸骨之柱",
    "Pillar of Worms": "蠕虫之柱",
    "Translocator": "移形师",
    "Mechanomancer": "机械师",
    "Minos, The Golden Bull": "米诺斯，黄金公牛",
    "Chronos, Titan Immortal": "克洛诺斯，不朽泰坦",
    "Odin, Aesir Immortal": "奥丁，不朽亚萨神",
    "Gemini Twin": "双子",
    "The Mischief Maker": "恶作剧大师",
    "Slime Drake": "史莱姆龙",
    "Void Phoenix": "虚空凤凰",
    "Crucible of Pain": "痛苦坩埚",
    "Idol of Fiery Vengeance": "仇焰造像",
    "Concussive Idol": "恐慑碑像",
    "Idol of Vampirism": "吸血造像",
    "Bone Colossus": "骸骨巨像",
    "Flesh Colossus": "血肉巨像",
    "Giant Nightmare Turtle": "巨大梦魇龟", #巨型？ 目前 giant 除了魂匣都用的巨大，感觉巨型怪怪的
    "Giant Mass of Eyes": "巨大眼球集群",
    "Giant Gorgon": "巨大戈尔贡",
    "Beastking of Inferno": "炼狱兽王",
    "Ultimate Mind Devourer": "究极心灵吞噬者",
    "Giant Sack of Filth": "污秽巨囊",
    "True Lamasu": "真 拉马苏",
    "Winterbringer": "凛冬使徒",
    "Moon Mage": "月亮法师",
    "Blood Magus": "鲜血法师",
    "Deathchiller": "死寒术士",
    "Brain Tree": "脑树",
    "Rot Tree": "腐坏树",
    "Jormungandr": "耶梦加得",
    "Ophan": "座天使",
    "Pope the Frog": "青蛙教皇",
    "Insanity Queen": "疯魇皇后",
    "Mordred": "莫德雷德",
}

# 这里是散落在源代码中没有从怪物文件 dump 出来的名字，手动挡
monsters.update({
    "Fire Elemental": "火元素",
    "Starfire Elemental": "星火元素",
    "Golem": "魔像",
    "Flying Golem": "飞行魔像",
    "Skeleton": "骷髅",
    "Flying Skeleton": "飞行骷髅",
    "Wolf": "狼",
    "Ice Hound": "寒冰猎犬",
    "Clay Hound": "黏土猎犬",
    "Giant Bear": "巨熊",
    "Metallic Giant Bear": "金属巨熊",
    "Venom Bear": "毒液熊",
    "Storm Spirit": "风暴精魂",
    "Thorny Plant": "荆棘",
    "Iron Thorn": "铁荆棘",
    "Icy Thorn": "冰荆棘",
    "Orb": "法球",
    "Arcane Orb": "奥术法球",
    "Searing Orb": "灼热法球",
    "Ball Lightning": "球状闪电",
    "Ice Faery": "冰霜仙灵",
    "Frost Eyeball": "霜冻眼球",
    "Earth Elemental": "大地元素",
    "Small Worm Ball": "小型蠕虫球",
})
