dic = {
    'Fire': '火焰',
    'Lightning': '闪电',
    'Ice': '寒冰',
    'Nature': '自然',
    'Arcane': '奥术',
    'Dark': '黑暗',
    'Holy': '神圣',
    'Sorcery': '法术',
    'Conjuration': '召唤',
    'Enchantment': '附魔',
    'Word': '真言',
    'Orb': '法球',
    'Dragon': '巨龙',
    'Translocation': '移位',
    'Metallic': '金属',
    'Eye': '视线',
    'Chaos': '混沌',
    'fire': '火焰',
    'lightning': '闪电',
    'ice': '寒冰',
    'nature': '自然',
    'arcane': '奥术',
    'dark': '黑暗',
    'holy': '神圣',
    'sorcery': '法术',
    'conjuration': '召唤',
    'enchantment': '附魔',
    'word': '真言',
    'orb': '法球',
    'dragon': '巨龙',
    'translocation': '移位',
    'metallic': '金属',
    'eye': '视线',
    'chaos': '混沌',
    'poison': '毒性',
    'physical': '物理',
    'damage type': '伤害类型',

    'Damage': '伤害',
    'Max Charges': '充能上限',
    'Radius': '范围',
    'Range': '射程',

    'Chaos Ball': '混沌球',
    'Energy Ball': '能量球',
    'Ash Ball': '灰烬球',

    'Death Bolt': '死亡之箭',
    'Fireball': '火球术',
    'Icicle': '冰锥术',
    'Lightning Bolt': '闪电箭',
    'Poison Sting': '毒刺术',
    'Magic Missile': '魔法飞弹',
    'Wolf': '召狼术',
    'Annihilate': '歼灭术',
    'Blazerip': '熔刃术',
    'Boiling Blood': '热血术',
    'Chain Lightning': '闪电链',
    'Chaos Barrage': '混沌弹幕',
    'Disperse': '驱散术',
    'Eye of Fire': '火焰之眼',
    'Eye of Ice': '寒冰之眼',
    'Eye of Lightning': '闪电之眼',
    'Eye of Rage': '愤怒之眼',
    'Fan of Flames': '扇状烈焰',
    'Freeze': '冰冻术',
    'Healing Light': '治愈之光',
    'Heavenly Blast': '天堂冲击',
    'Hollow Flesh': '空心肉体',
    'Hungry Maw': '饥肠辘辘',
    'Invoke Savagery': '召唤野蛮人',
    'Magnetize': '磁化术',
    'Melt': '熔化术',
    'Petrify': '石化术',
    'Regeneration Aura': '再生光环',
    'Soul Swap': '灵魂交换',
    'Thunder Strike': '雷击术',
    'Touch of Death': '死亡之触',
    'Toxic Spores': '有毒孢子',
    'Toxin Burst': '毒素爆发',
    'Aether Swap': '以太交换',
    'Basilisk Armor': '蜥怪盔甲',
    'Blinding Light': '眩目之光',
    'Blink': '扑闪术',
    'Choir of Angels': '天使合唱',
    'Combust Poison': '燃烧毒药',
    'Darkness': '黑暗术',
    'Death Chill': '死亡之寒',
    'Devour Mind': '吞噬心灵',
    'Dominate': '支配术',
    'Earthen Sentinel': '大地哨兵',
    'Earthquake': '地震术',
    'Flame Burst': '火爆术',
    'Flame Gate': '火门术',
    'Frostfire Hydra': '霜火九头蛇',
    'Ghostball': '鬼球术',
    'Giant Bear': '召唤巨熊',
    'Glass Orb': '玻璃法球',
    'Holy Armor': '圣甲术',
    'Holy Fire': '圣火术',
    'Iceball': '冰球术',
    'Ironize': '讽刺术',
    'Lightning Halo': '闪电光环',
    'Lightning Spire': '闪电尖塔',
    'Mercurize': '汞化术',
    'Mystic Power': '神秘力量',
    'Mystic Vision': '神秘视觉',
    'Nightmare Aura': '梦魇光环',
    'Pain Mirror': '痛苦之镜',
    'Plague of Filth': '污秽瘟疫',
    'Prison of Thorns': '荆棘监狱',
    'Seal Fate': '封印命运',
    'Shrapnel Blast': '弹片爆炸',
    'Silver Spear': '银色长矛',
    'Suspend Mortality': '暂缓死亡',
    'Underworld Passage': '冥界通道',
    'Void Beam': '虚空光束',
    'Void Orb': '虚空法球',
    'Arc Lightning': '弧状闪电',
    'Blizzard': '暴风雪',
    'Bone Barrage': '白骨弹幕',
    'Call Archon': '召唤统领',
    'Call Seraph': '召唤炽天使',
    'Chimera Familiar': '奇美拉佣兽',
    'Conductance': '电导术',
    'Conjure Memories': '唤起回忆',
    'Death Gaze': '死亡凝视',
    'Death Shock': '死亡冲击',
    'Dispersion Field': '扩散场',
    'Essence Flux': '菁华异变',
    'Fiery Tormentor': '火热的折磨者',
    'Fire Drake': '火焰巨龙',
    'Ice Drake': '寒冰巨龙',
    'Ice Orb': '寒冰法球',
    'Ice Vortex': '寒冰旋涡',
    'Lightning Form': '闪电形态',
    'Lightning Storm': '闪电风暴',
    'Orb Control': '法球控制',
    'Permanence': '持久术',
    'Petrification Aura': '石化光环',
    'Purity': '纯净术',
    'Pyrostatic Pulse': '静电脉冲',
    'Searing Seal': '灼热封印',
    'Siege Golems': '攻城魔像',
    'Sight of Blood': '鲜血视线',
    'Siphon Shields': '虹吸护罩',
    'Storm Burst': '风暴爆发',
    'Storm Drake': '风暴幼龙',
    'The Restless Dead': '不息的死者',
    'Void Drake': '虚空幼龙',
    'Volcanic Eruption': '火山爆发',
    'Wall of Ice': '寒冰之墙',
    'Watcher Form': '守望者形态',
    'Wheel of Death': '死亡之轮',
    'Ball Lightning': '球状闪电',
    'Blue Lion': '蓝狮子',
    'Cantrip Cascade': '小招倾斜',
    'Chill Wind': '寒风术',
    'Death Cleave': '死亡分裂',
    'Fae Court': '仙灵宫廷',
    'Floating Eye': '漂浮的眼球',
    'Flock of Eagles': '召唤鹰群',
    'Heavenly Idol': '天堂偶像',
    'Ice Phoenix': '寒冰凤凰',
    'Mega Annihilate': '超级歼灭术',
    'Pillar of Fire': '火柱术',
    'Pyrostatic Curse': '电焰诅咒',
    'Ring of Spiders': '蜘蛛之环',
    'Slime Form': '史莱姆形态',
    'Soul Tax': '灵魂税',
    'Spider Queen': '蜘蛛女王',
    'Teleport': '传送术',
    'Dragon Roar': '巨龙咆哮',
    'Gold Drake': '黄金幼龙',
    "Heaven's Wrath": '天堂之怒',
    'Imp Swarm': '小鬼群',
    'Mystic Memory': '神秘记忆',
    'Searing Orb': '灼热法球',
    'Twilight Gaze': '暮光凝视',
    'Knightly Oath': '骑士誓言',
    'Meteor Shower': '陨石雨',
    'Multicast': '多重施法',
    'Spikeball Factory': '刺球厂',
    'Word of Beauty': '美丽真言',
    'Word of Chaos': '混沌真言',
    'Word of Ice': '寒冰真言',
    'Word of Madness': '疯狂真言',
    'Word of Undeath': '不死真言',

    'Arcane Accounting': '奥术会计',
    'Arcane Combustion': '奥术燃烧',
    'Arcane Shield': '奥术护盾',
    'Chaos Buddies': '混沌伙伴',
    'Chastisement': '惩戒',
    'Crystal Power': '水晶之力',
    'Faestone': '仙灵石',
    'Ghostfire': '鬼火',
    'Hibernation': '休眠',
    'Holy Water': '圣水',
    'Hungry Dead': '饿死鬼',
    'Megavenom': '超级毒液',
    'Minion Regeneration': '小兵再生',
    'Natural Vigour': '自然活力',
    'Paralyzing Venom': '麻痹毒液',
    'Radiant Chill': '寒气逼人',
    'Shielded Minions': '带盾小兵',
    'Spider Spawning': '蜘蛛幼崽',
    'Unholy Alliance': '不洁联盟',
    'Venom Spit': '毒液喷吐',
    'Voidflame Lantern': '虚空火灯',
    'White Flame': '白色火焰',
    'Acid Fumes': '酸雾',
    'Chaos Casting': '混沌施法',
    'Collected Agony': '收集痛苦',
    'Frozen Fragility': '冻脆',
    'Glittering Dance': '闪光之舞',
    'Horror': '恐怖',
    'Houndlord': '猎犬领主',
    'Hypocrisy': '虚伪',
    'Last Word': '遗言',
    'Lightning Frenzy': '闪电狂潮',
    'Melting Armor': '熔化盔甲',
    'Necrostatics': '尸毒学',
    'Prince of Ruin': '毁灭王子',
    'Purestrike': '纯粹打击',
    'Pyrophilia': '嗜热症',
    'Righteous March': '正义进军',
    'Searing Heat': '灼热',
    'Silkshifter': '织丝者',
    'Storm Caller': '风暴召师',
    'Thorn Garden': '荆棘花园',
    'Bone Guard': '白骨卫士',
    'Cracklevoid': '噼里啪啦',
    'Frostbite': '冻伤',
    'Ice Tap': '冰塔',
    'Icy Vengeance': '冰冷复仇',
    'Inferno Engines': '地狱火引擎',
    'Lightning Warp': '闪电扭曲',
    'Moonspeaker': '月语者',
    'Scalespinner': '龙鳞旋抗',
    'Shatter Shards': '破碎飞片',
    'Starfire': '星星之火',
    'Steam Anima': '蒸汽灵魂',
    'Arch Conjurer': '大造物师',
    'Arch Enchanter': '大附魔师',
    'Arch Sorcerer': '大法术师',
    'Dark Lord': '黑暗领主',
    'Dragon Lord': '巨龙领主',
    'Fiery Judgement': '炽热审判',
    'Fire Lord': '火焰领主',
    'Holy Thunder': '神圣雷霆',
    'Ice Lord': '寒冰领主',
    'Light Lord': '光明领主',
    'Metal Lord': '金属领主',
    'Nature Lord': '自然领主',
    'Orb Lord': '法球领主',
    'Shock Value': '冲击价值',
    'Soul Harvest': '灵魂收割',
    'Thunder Lord': '雷霆领主',
    'Translocation Master': '转移大师',
    'Unblinking Eye': '定睛之眼',
    'Void Lord': '虚空领主',
    'Void Spikes': '虚空尖塔',

    'Healing Potion': '治疗药水',
    'Teleporter': '传送器',
    'Chaos Bell': '混沌之铃',
    'Golden Stopwatch': '黄金秒表',
    'Death Dice': '死亡骰子',
    'Energy Shield': '能量护盾',
    'Stone Shield': '石质护盾',
    'Mana Potion': '魔法药水',
    'Earthquake Orb': '地震法球',
    'Dragon Horn': '巨龙号角',
    'Portal Disruptor': '传送门干扰器',
    'Shrine Disruptor': '祭祠干扰器',
    'Portal Key': '传送门钥匙',
    'Orb of Corruption': '腐败法球',
    'Elixir of Youth': '不老琼浆',
    'Youth': '永葆青春',
    'Aether Dagger': '以太匕首',
    'Oculus': '天眼',
    'Memory Enhancement': '回忆增强',
    'Draught of Memories': '回忆药剂',
    'Bag of Spikes': '一袋钉子',
    'Bag of Bags': '一袋袋子',
    'Troll Crown': '巨魔之冠',
    'Storm Troll Crown': '风暴巨魔之冠',
    'Earth Troll Crown': '大地巨魔之冠',

    'Goblin': '哥布林',
    'Bat': '蝙蝠',
    '': '',
    '': '',
}
tag_dic = {
    'Fire': 'F火焰',
    'Lightning': 'L闪电',
    'Ice': 'I寒冰',
    'Nature': 'N自然',
    'Arcane': 'A奥术',
    'Dark': 'D黑暗',
    'Holy': 'H神圣',
    'Sorcery': 'S法术',
    'Conjuration': 'C召唤',
    'Enchantment': 'E附魔',
    'Word': 'W真言',
    'Orb': 'B法球',
    'Dragon': 'R巨龙',
    'Translocation': 'T移位',
    'Metallic': 'M金属',
    'Eye': 'Y视线',
    'Chaos': 'O混沌'
}
attr_dic = {
    'radius': '范围',
    'damage': '伤害',
    'max_charges': '充能上限',
    'range': '射程',
}