all_chatter_npcs = [
	("Young Lady", "A pretty young woman", "Your an adventurer? ... oh ... giggle ...."),
	("Young Lady", "A pretty young woman", "Diamonds are beautiful!  But its not safe outside of the town..."),
	("Young Lady", "A pretty young woman", "I want to marry a man with lots of gold!"),
	("Young Lady", "A pretty young woman", "Your an adventurer? ... oh ... have you ever killed a dragon?"),
	("Young Lady", "A pretty young woman", "I want to marry an adventurer! ..."),
	("Farmer", "A stout farmer", "The land here is very dry, and the people are boring, but atleast I know where my next meal is coming from."),
	("Farmer", "A stout farmer", "My daughter has some crazy ideas about marrying an adventurer, but she'll be much better off marrying a blacksmith or a farmer."),
	("Farmer", "A stout farmer", "I love farming!"),
	("Farmer", "A stout farmer", "I hate farming."),
	("Farmer", "A stout farmer", "Diamonds?  I saw one once..."),
	("Blacksmith", "A musclebound craftsman", "I make my living selling weapons!  Nothing as powerful as your spells though."),	
	("Blacksmith", "A musclebound craftsman", "Blacksmithing is a noble profession.  Iron yearns to be smashed into something useful!"),
	("Blacksmith", "A musclebound craftsman", "There was a time I fancied becoming a wizard, but its too much memorization for me!"),
	("Old Woman", "A wrinkled old woman", "Someday youll wish you'd done somethign with your life instead of all this adventuring."),
	("Old Woman", "A wrinkled old woman", "I hope you leave here soon.  Your giving people the wrong ideas about life."),
	("Old Woman", "A wrinkled old woman", "My husband was an adventurer.  Be careful around fire imps!"),
	("Old Man", "A grey haired old man", "The portals at the edge of town?  I wouldn't go near them if I were you!"),
	("Old Man", "A grey haired old man", "They say our town began with the chance meeting of two adventurers."),
	("Adventurer", "A fellow adventurer", "I never leave any loot on the ground!"),
	("Adventurer", "A fellow adventurer", "A wise adventurer knows when to fight and when to run!"),
	("Adventurer", "A fellow adventurer", "I once found the corpse of a fellow adventurer.  There was more mana in his pouch than I could count... what could have killed such a wealthy man?  Foolishness perhaps!"),
	("Adventurer", "A fellow adventurer", "I once found the corpse of a fellow adventurer.  There were more potions and trinkets in his pouch than I could carry... what could have killed such a wealthy man?  Foolishness perhaps!"),
]
